Repository global-121/121-platform, pull requests merged in 2024-07, with the labels that each got.

#5433 Re-implement re-issue visa card
  services/121-service/module-dependencies.md
  services/121-service/src/metrics/metrics.module.ts
  services/121-service/src/metrics/metrics.service.ts
  services/121-service/src/payments/fsp-integration/intersolve-visa/dto/external/personal-data.ts
  services/121-service/src/payments/fsp-integration/intersolve-visa/dto/internal/intersolve-api/substitute-token-request.dto.ts
  services/121-service/src/payments/fsp-integration/intersolve-visa/dto/intersolve-visa-do-transfer-or-issue-card.dto.ts
  services/121-service/src/payments/fsp-integration/intersolve-visa/dto/reissue-card.dto.ts
  services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.api.service.ts
  services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.controller.ts
  services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.service.ts
  services/121-service/src/payments/payments.service.ts
  services/121-service/src/program-financial-service-provider-configurations/program-financial-service-provider-configurations.repository.ts
  services/121-service/src/registration/modules/registration-data/registration-data.module.ts
  services/121-service/src/registration/modules/registration-data/registration-data.service.ts
  services/121-service/src/registration/modules/registration-data/repositories/registration-data.scoped.repository.ts
  services/121-service/src/registration/registrations.controller.ts
  services/121-service/src/registration/registrations.module.ts
  services/121-service/src/registration/registrations.service.ts
  services/121-service/src/registration/repositories/registration-scoped.repository.ts
  services/121-service/src/registration/services/registrations-bulk.service.ts
  services/121-service/src/registration/services/registrations-import.service.ts
  services/121-service/src/transaction-job-processors/transaction-job-processors.service.ts
Labels: Intersolve Visa Reimplementation

#5506 Re-implement retrieve and update wallets and cards cron job
  services/121-service/src/cronjob/cronjob.service.ts
  services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.controller.ts
  services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.service.ts
  services/121-service/src/payments/fsp-integration/intersolve-visa/repositories/intersolve-visa-customer.scoped.repository.ts
Labels: Intersolve Visa Reimplementation

#5512 Re-implement send updated contact information
  services/121-service/module-dependencies.md
  services/121-service/src/payments/fsp-integration/intersolve-visa/dto/external/contact-information.dto.ts
  services/121-service/src/payments/fsp-integration/intersolve-visa/dto/intersolve-visa-do-transfer-or-issue-card.dto.ts
  services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.api.service.ts
  services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.controller.ts
  services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.module.ts
  services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.service.ts
  services/121-service/src/payments/fsp-integration/intersolve-visa/repositories/intersolve-visa-customer.scoped.repository.ts
  services/121-service/src/registration/registrations.controller.ts
  services/121-service/src/registration/registrations.service.ts
Labels: Intersolve Visa Reimplementation

#5527 Process feedback on re-issue card
  interfaces/Portal/src/app/components/physical-card-popup/physical-card-popup.component.ts
  interfaces/Portal/src/app/services/programs-service-api.service.ts
  services/121-service/src/payments/fsp-integration/intersolve-visa/dto/intersolve-visa-do-transfer-or-issue-card.dto.ts
  services/121-service/src/registration/registrations.controller.ts
  services/121-service/src/registration/registrations.service.ts
  services/121-service/src/registration/repositories/registration-scoped.repository.ts
  services/121-service/src/transaction-job-processors/transaction-job-processors.service.ts
Labels: Intersolve Visa Reimplementation

#5533 Send references to intersolve
  services/121-service/src/payments/fsp-integration/intersolve-visa/dto/internal/transfer.dto.ts
  services/121-service/src/payments/fsp-integration/intersolve-visa/dto/intersolve-visa-do-transfer-or-issue-card.dto.ts
  services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.api.service.ts
  services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.service.ts
  services/121-service/src/programs/repositories/program.repository.ts
  services/121-service/src/transaction-job-processors/transaction-job-processors.service.ts
Labels: Intersolve Visa Reimplementation

#5560 Fixed ApiTags for contact-information endpoint
  services/121-service/src/registration/registrations.controller.ts
Labels: Intersolve Visa Reimplementation

#5582 feat: Add ApplicationInsights logging in LogService
  interfaces/Portalicious/.env.example
  interfaces/Portalicious/angular.json
  interfaces/Portalicious/package-lock.json
  interfaces/Portalicious/package.json
  interfaces/Portalicious/src/app/components/page-layout/components/header/header.component.ts
  interfaces/Portalicious/src/app/services/log.service.ts
  interfaces/Portalicious/src/environments/environment.ts
  interfaces/Portalicious/src/environments/environment.ts.template.js
Labels: ignore-for-release

#5586 Misc. documentation, config, setup related fixes/changes for Portalicious
  README.md
  interfaces/Portal/README.md
  interfaces/Portal/staticwebapp.config.json
  interfaces/Portalicious/.env.example
  interfaces/Portalicious/.node-version
  interfaces/Portalicious/.vscode/extensions.json
  interfaces/Portalicious/.vscode/settings.json
  interfaces/Portalicious/README.md
  interfaces/Portalicious/angular.json
  interfaces/Portalicious/eslint.config.js
  interfaces/Portalicious/package-lock.json
  interfaces/Portalicious/package.json
  interfaces/Portalicious/src/app/app.routes.ts
  interfaces/Portalicious/src/app/services/http-wrapper.service.ts
  interfaces/Portalicious/src/app/services/log.service.ts
  interfaces/Portalicious/src/app/utils/dto-type.ts
  interfaces/Portalicious/src/environments/environment.ts
  interfaces/Portalicious/src/environments/environment.ts.template.js
  interfaces/Portalicious/staticwebapp.config.json
  interfaces/README.md
Labels: ignore-for-release, chore

#5568 portalicious: add localize to Portalicious
  .github/workflows/deploy_test_portalicious.yml
  e2e/playwright.portalicious.config.ts
  e2e/portalicious/pages/BasePage.ts
  e2e/portalicious/pages/HomePage.ts
  e2e/portalicious/primeng-components/PrimeDropdown.ts
  e2e/portalicious/tests/Navigation/BasicNavigation.spec.ts
  e2e/portalicious/tests/Navigation/ChangeLanguage.spec.ts
  e2e/portalicious/tests/ViewHomepage/ViewHomepage.spec.ts
  interfaces/Portalicious/.env.example
  interfaces/Portalicious/angular.json
  interfaces/Portalicious/eslint.config.js
  interfaces/Portalicious/package-lock.json
  interfaces/Portalicious/package.json
  interfaces/Portalicious/src/app/app.component.spec.ts
  interfaces/Portalicious/src/app/app.config.ts
  interfaces/Portalicious/src/app/components/health-widget/health-widget.component.html
  interfaces/Portalicious/src/app/components/page-layout/components/footer/footer.component.html
  interfaces/Portalicious/src/app/components/page-layout/components/header/header.component.html
  interfaces/Portalicious/src/app/components/page-layout/components/header/header.component.ts
  interfaces/Portalicious/src/app/components/page-layout/components/program-header/program-header.component.html
  interfaces/Portalicious/src/app/components/page-layout/components/program-header/program-header.component.ts
  interfaces/Portalicious/src/app/pages/all-projects/all-projects.component.html
  interfaces/Portalicious/src/app/pages/create-program/create-program.component.html
  interfaces/Portalicious/src/app/pages/program/program-monitoring/program-monitoring.component.html
  interfaces/Portalicious/src/app/pages/program/program-overview/program-overview.component.html
  interfaces/Portalicious/src/app/pages/program/program-payments/program-payments.component.html
  interfaces/Portalicious/src/app/pages/program/program-registrations/program-registrations.component.html
  interfaces/Portalicious/src/app/pages/program/program-team/program-team.component.html
  interfaces/Portalicious/src/app/pages/roles-and-permissions/roles-and-permissions.component.html
  interfaces/Portalicious/src/app/pages/user-settings/user-settings.component.html
  interfaces/Portalicious/src/app/pages/users/users.component.html
  interfaces/Portalicious/src/app/utils/locale.spec.ts
  interfaces/Portalicious/src/app/utils/locale.ts
  interfaces/Portalicious/src/environments/environment.ts
  interfaces/Portalicious/src/environments/environment.ts.template.js
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
  interfaces/Portalicious/src/main.ts
  interfaces/Portalicious/staticwebapp.config.json
  interfaces/Portalicious/tsconfig.app.json
  interfaces/Portalicious/tsconfig.spec.json
  services/.env.example
Labels: ignore-for-release

#5587 portalicious: address header/sidebar design feedback
  .vscode/settings.json
  interfaces/Portalicious/.vscode/extensions.json
  interfaces/Portalicious/.vscode/settings.json
  interfaces/Portalicious/README.md
  interfaces/Portalicious/src/app/app.routes.ts
  interfaces/Portalicious/src/app/components/component-guidelines.md
  interfaces/Portalicious/src/app/components/page-layout/components/footer/footer.component.html
  interfaces/Portalicious/src/app/components/page-layout/components/header/header.component.html
  interfaces/Portalicious/src/app/components/page-layout/components/header/header.component.ts
  interfaces/Portalicious/src/app/components/page-layout/components/program-header/program-header.component.html
  interfaces/Portalicious/src/app/components/page-layout/page-layout.component.html
  interfaces/Portalicious/src/app/pages/create-program/create-program.component.html
  interfaces/Portalicious/src/app/pages/create-program/create-program.component.ts
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
  interfaces/Portalicious/src/styles.scss
Labels: ignore-for-release

#5575 portalicious: login with basic auth
  .github/workflows/deploy_test_portalicious.yml
  e2e/portalicious/pages/LoginPage.ts
  e2e/portalicious/tests/Navigation/BasicNavigation.spec.ts
  e2e/portalicious/tests/Navigation/ChangeLanguage.spec.ts
  e2e/portalicious/tests/ViewHomepage/ViewHomepage.spec.ts
  interfaces/Portalicious/angular.json
  interfaces/Portalicious/eslint.config.js
  interfaces/Portalicious/package-lock.json
  interfaces/Portalicious/package.json
  interfaces/Portalicious/src/app/app.routes.ts
  interfaces/Portalicious/src/app/auth.guard.ts
  interfaces/Portalicious/src/app/components/form-error/form-error.component.html
  interfaces/Portalicious/src/app/components/form-error/form-error.component.ts
  interfaces/Portalicious/src/app/components/health-widget/health-widget.component.html
  interfaces/Portalicious/src/app/components/health-widget/health-widget.component.ts
  interfaces/Portalicious/src/app/components/logo/logo.component.html
  interfaces/Portalicious/src/app/components/logo/logo.component.ts
  interfaces/Portalicious/src/app/components/page-layout/components/header/header.component.html
  interfaces/Portalicious/src/app/components/page-layout/components/header/header.component.ts
  interfaces/Portalicious/src/app/pages/all-projects/all-projects.component.html
  interfaces/Portalicious/src/app/pages/all-projects/all-projects.component.ts
  interfaces/Portalicious/src/app/pages/login/components/cookie-banner/cookie-banner.component.html
  interfaces/Portalicious/src/app/pages/login/components/cookie-banner/cookie-banner.component.ts
  interfaces/Portalicious/src/app/pages/login/login.component.html
  interfaces/Portalicious/src/app/pages/login/login.component.ts
  interfaces/Portalicious/src/app/services/api.service.ts
  interfaces/Portalicious/src/app/services/auth.service.ts
  interfaces/Portalicious/src/app/services/http-wrapper.service.ts
  interfaces/Portalicious/src/app/services/log.service.ts
  interfaces/Portalicious/src/app/utils/locale.ts
  interfaces/Portalicious/src/assets/login.jpeg
  interfaces/Portalicious/src/favicon.ico
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
  interfaces/Portalicious/src/styles.scss
  interfaces/Portalicious/staticwebapp.config.json
  interfaces/Portalicious/tsconfig.json
Labels: ignore-for-release

#5601 Tweak login-page + cookie notice
  .vscode/settings.json
  interfaces/Portalicious/.editorconfig
  interfaces/Portalicious/.prettierrc.yml
  interfaces/Portalicious/.vscode/extensions.json
  interfaces/Portalicious/.vscode/settings.json
  interfaces/Portalicious/angular.json
  interfaces/Portalicious/package-lock.json
  interfaces/Portalicious/package.json
  interfaces/Portalicious/src/app/auth.guard.ts
  interfaces/Portalicious/src/app/components/language-switcher/language-switcher.component.html
  interfaces/Portalicious/src/app/components/language-switcher/language-switcher.component.ts
  interfaces/Portalicious/src/app/components/logo/logo.component.html
  interfaces/Portalicious/src/app/components/logo/logo.component.ts
  interfaces/Portalicious/src/app/components/page-layout/components/header/header.component.html
  interfaces/Portalicious/src/app/components/page-layout/components/header/header.component.ts
  interfaces/Portalicious/src/app/pages/login/components/cookie-banner/cookie-banner.component.html
  interfaces/Portalicious/src/app/pages/login/components/cookie-banner/cookie-banner.component.ts
  interfaces/Portalicious/src/app/pages/login/login.component.html
  interfaces/Portalicious/src/app/pages/login/login.component.ts
  interfaces/Portalicious/src/app/utils/locale.ts
  interfaces/Portalicious/src/favicon.ico
  interfaces/Portalicious/src/index.html
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
  interfaces/Portalicious/src/styles.scss
Labels: ignore-for-release

#5622 chore: Align Dev-Dependencies
  .github/dependabot.yml
  e2e/package-lock.json
  e2e/package.json
  interfaces/Portal/package-lock.json
  interfaces/Portal/package.json
  interfaces/Portalicious/.vscode/settings.json
  interfaces/Portalicious/package-lock.json
  interfaces/Portalicious/package.json
  k6/package-lock.json
  k6/package.json
  package-lock.json
  package.json
  services/121-service/package-lock.json
  services/121-service/package.json
Labels: dependencies
