Repository global-121/121-platform, pull requests merged in 2024-09, with the labels that each got.

#5747 feat: Add logout escape-hatch for (SSO→login issues
  .github/actions/build-interface/action.yml
  interfaces/Portal/src/logout/index.html
  interfaces/Portal/src/logout/logout.js
  interfaces/Portal/staticwebapp.config.json
Labels: bugfix, chore

#5710 Improvements Visa migration endpoint
  services/121-service/src/migrate-visa/migrate-visa.controller.ts
  services/121-service/src/migrate-visa/migrate-visa.service.ts
Labels: Intersolve Visa Reimplementation

#5751 feat: Add error-notice + manual trigger to force-logout from within iframe
  interfaces/Portal/src/app/pages/login/login.page.html
  interfaces/Portal/src/app/pages/login/login.page.ts
  interfaces/Portal/src/assets/i18n/en.json
  interfaces/Portal/src/assets/i18n/nl.json
  interfaces/Portal/src/logout/logout.js
Labels: bugfix

#5754 fix: Hard-code text+link to prevent translations-loading issue
  interfaces/Portal/src/app/pages/login/login.page.html
Labels: bugfix

#5738 portalicious: project monitoring page
  interfaces/Portalicious/eslint.config.js
  interfaces/Portalicious/package-lock.json
  interfaces/Portalicious/package.json
  interfaces/Portalicious/src/app/app.routes.ts
  interfaces/Portalicious/src/app/components/colored-chip/colored-chip.component.html
  interfaces/Portalicious/src/app/components/colored-chip/colored-chip.component.ts
  interfaces/Portalicious/src/app/components/data-list/data-list.component.html
  interfaces/Portalicious/src/app/components/data-list/data-list.component.ts
  interfaces/Portalicious/src/app/components/info-tooltip/info-tooltip.component.html
  interfaces/Portalicious/src/app/components/info-tooltip/info-tooltip.component.ts
  interfaces/Portalicious/src/app/components/page-layout/components/header/header.component.ts
  interfaces/Portalicious/src/app/components/page-layout/components/health-widget/health-widget.component.html
  interfaces/Portalicious/src/app/components/page-layout/components/health-widget/health-widget.component.ts
  interfaces/Portalicious/src/app/components/page-layout/components/project-header/project-header.component.ts
  interfaces/Portalicious/src/app/components/page-layout/page-layout.component.html
  interfaces/Portalicious/src/app/components/page-layout/page-layout.component.ts
  interfaces/Portalicious/src/app/domains/project/project.model.ts
  interfaces/Portalicious/src/app/pages/project/project-monitoring/metric-tile/metric-tile.component.html
  interfaces/Portalicious/src/app/pages/project/project-monitoring/metric-tile/metric-tile.component.ts
  interfaces/Portalicious/src/app/pages/project/project-monitoring/monitoring-iframe/monitoring-iframe.component.html
  interfaces/Portalicious/src/app/pages/project/project-monitoring/monitoring-iframe/monitoring-iframe.component.spec.ts
  interfaces/Portalicious/src/app/pages/project/project-monitoring/monitoring-iframe/monitoring-iframe.component.ts
  interfaces/Portalicious/src/app/pages/project/project-monitoring/project-monitoring.component.html
  interfaces/Portalicious/src/app/pages/project/project-monitoring/project-monitoring.component.ts
  interfaces/Portalicious/src/app/pages/projects-overview/project-metric-container/project-metric-container.component.html
  interfaces/Portalicious/src/app/pages/projects-overview/project-metric-container/project-metric-container.component.ts
  interfaces/Portalicious/src/app/pages/projects-overview/project-summary-card/project-summary-card.component.html
  interfaces/Portalicious/src/app/pipes/translatable-string.pipe.ts
  interfaces/Portalicious/src/app/services/translatable-string.service.ts
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
  interfaces/Portalicious/src/styles.scss
  interfaces/Portalicious/tailwind.config.ts
  services/121-service/src/metrics/dto/program-stats.dto.ts
  services/121-service/src/metrics/metrics.service.ts
  services/121-service/src/programs/dto/found-program.dto.ts
  services/121-service/src/programs/programs.service.ts
Labels: portalicious

#5741 portalicious: edit user on teams page
  interfaces/Portalicious/src/app/components/query-table/query-table.component.html
  interfaces/Portalicious/src/app/domains/project/project.api.service.ts
  interfaces/Portalicious/src/app/pages/project/project-team/add-user-form/add-user-form.component.html
  interfaces/Portalicious/src/app/pages/project/project-team/add-user-form/add-user-form.component.ts
  interfaces/Portalicious/src/app/pages/project/project-team/project-team.component.html
  interfaces/Portalicious/src/app/pages/project/project-team/project-team.component.ts
  interfaces/Portalicious/src/app/pages/projects-overview/create-project-form/create-project-form.component.html
  interfaces/Portalicious/src/app/pages/projects-overview/create-project-form/create-project-form.component.ts
  interfaces/Portalicious/src/app/pages/projects-overview/projects-overview.component.html
  interfaces/Portalicious/src/app/pages/projects-overview/projects-overview.component.ts
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
  interfaces/Portalicious/src/styles.scss
Labels: portalicious

#5767 chore: make sure PRs have the right required checks
  .github/workflows/deploy_test_portal.yml
  .github/workflows/deploy_test_portalicious.yml
  .github/workflows/test_pull_request_formatting.yml
Labels: chore

#5769 feat: show paymentCountRemaining only if enableMaxPayments is true AB…
  services/121-service/src/program-attributes/program-attributes.service.ts
Labels: enhancement

#5765 chore: fix flaky send message test
  services/121-service/src/notifications/processors/message-status-callback.processor.ts
  services/121-service/test/helpers/program.helper.ts
  services/121-service/test/payment/do-payment-fsp-voucher.test.ts
  services/121-service/test/registrations/pagination/send-message.test.ts
  services/121-service/test/registrations/send-message-with-placeholder.test.ts
  services/121-service/test/registrations/send-templated-message.test.ts
  services/mock-service/src/twilio/twilio.controller.ts
  services/mock-service/src/twilio/twilio.service.ts
Labels: chore

#5771 Add E2E-test for Logout feature(s) + Update "Getting Started" documentation
  .github/actions/build-interface/action.yml
  .gitignore
  .vscode/extensions.json
  e2e/.gitignore
  e2e/README.md
  e2e/portalicious/tests/LogOut/LogOut.spec.ts
  interfaces/Portal/_build-manual-logout.js
  interfaces/Portal/package.json
  interfaces/Portal/src/logout/README.md
  interfaces/Portal/staticwebapp.config.json
  interfaces/Portalicious/_build-manual-logout.js
  interfaces/Portalicious/package.json
  interfaces/Portalicious/src/logout/README.md
  services/.env.example
Labels: portalicious

#5782 test: Focus testing on actual URLs only
  e2e/README.md
  e2e/portalicious/tests/LogOut/LogOut.spec.ts
  interfaces/Portal/src/logout/logout.js
  interfaces/Portalicious/src/logout/logout.js
Labels: portalicious

#5788 chore: add findOne endpoint to be used in portalicious
  interfaces/Portalicious/src/app/app.routes.ts
  interfaces/Portalicious/src/app/domains/domain-api.service.ts
  interfaces/Portalicious/src/app/domains/payment/payment.api.service.ts
  interfaces/Portalicious/src/app/domains/payment/payment.model.ts
  interfaces/Portalicious/src/app/domains/project/project.model.ts
  interfaces/Portalicious/src/app/domains/registration/registration.api.service.ts
  interfaces/Portalicious/src/app/domains/registration/registration.model.ts
  interfaces/Portalicious/src/app/pages/project/project-registrations/project-registrations.component.html
  interfaces/Portalicious/src/app/pages/project/project-registrations/project-registrations.component.ts
  interfaces/Portalicious/src/app/services/http-wrapper.service.ts
  services/121-service/src/registration/dto/mapped-paginated-registration.dto.ts
  services/121-service/src/registration/registrations.controller.ts
  services/121-service/src/registration/registrations.service.ts
  services/121-service/src/registration/services/registrations-pagination.service.ts
Labels: chore, portalicious

#5778 Feat.update node version to 20
  e2e/.node-version
  e2e/package-lock.json
  e2e/tsconfig.json
  interfaces/Portal/.node-version
  interfaces/Portal/package-lock.json
  services/121-service/.eslintrc.js
  services/121-service/.node-version
  services/121-service/Dockerfile
  services/121-service/package-lock.json
  services/121-service/src/payments/payments.service.ts
  services/121-service/src/registration/dto/bulk-import.dto.ts
  services/121-service/src/registration/dto/bulk-update.dto.ts
  services/121-service/test/users/login.test.ts
  services/121-service/tsconfig.json
  services/mock-service/.eslintrc.js
  services/mock-service/.node-version
  services/mock-service/Dockerfile
  services/mock-service/package-lock.json
  services/mock-service/tsconfig.json
Labels: enhancement

#5796 fix: Align all Node.js versions
  .node-version
  k6/.node-version
Labels: chore

#5794 feat: Add change-password redirect to help Password-managers
  e2e/portalicious/tests/ChangePassword/ChangePasswordRedirect.spec.ts
  interfaces/Portalicious/staticwebapp.config.json
Labels: portalicious

#5806 fix: Add cross-platform command to build-script
  interfaces/Portalicious/package.json
Labels: bugfix, portalicious

#5807 fix: Stop testing Third-Party API in CI-tests
  e2e/portalicious/tests/CreateNewProject/CreateNewProjectSuccessfully.spec.ts
  e2e/portalicious/tests/CreateNewProject/FillInInvalidToken.spec.ts
Labels: bugfix, workaround, ignore-for-release, chore

#5797 Remove user from team
  e2e/portalicious/pages/ProjectTeam.ts
  e2e/portalicious/tests/ManageTeam/AllSystemUsersCanBeAddedToProjectTeam.spec.ts
  e2e/portalicious/tests/ManageTeam/AssignSuccessfullyRolesToUser.spec.ts
  e2e/portalicious/tests/ManageTeam/RemoveUserFromTeam.spec.ts
  services/121-service/src/scripts/scripts.controller.ts
  services/121-service/src/scripts/scripts.module.ts
  services/121-service/src/scripts/seed-helper.ts
  services/121-service/src/scripts/seed-program-test-one-admin.ts
  services/121-service/src/scripts/seed-script.enum.ts
  services/121-service/src/seed-data/organization/organization-one-admin.json
  services/121-service/src/seed-data/program/program-test-one-admin.json
Labels: portalicious

#5808 portalicious: refactor hasPermission
  interfaces/Portalicious/src/app/auth.guard.ts
  interfaces/Portalicious/src/app/components/page-layout/components/project-header/project-header.component.ts
  interfaces/Portalicious/src/app/pages/project/project-team/project-team.component.ts
  interfaces/Portalicious/src/app/services/auth.service.ts
Labels: portalicious

#5748 Portalicious: profile page
  interfaces/Portalicious/src/app/app.routes.ts
  interfaces/Portalicious/src/app/components/colored-chip/colored-chip.component.ts
  interfaces/Portalicious/src/app/components/colored-chip/colored-chip.helper.ts
  interfaces/Portalicious/src/app/components/data-list/data-list.component.html
  interfaces/Portalicious/src/app/components/data-list/data-list.component.ts
  interfaces/Portalicious/src/app/components/not-available-label/not-available-label.component.html
  interfaces/Portalicious/src/app/components/not-available-label/not-available-label.component.ts
  interfaces/Portalicious/src/app/components/page-layout/components/project-header/project-header.component.html
  interfaces/Portalicious/src/app/components/page-layout/components/project-menu/project-menu.component.html
  interfaces/Portalicious/src/app/components/page-layout/components/project-menu/project-menu.component.ts
  interfaces/Portalicious/src/app/components/page-layout/components/registration-header/registration-header.component.html
  interfaces/Portalicious/src/app/components/page-layout/components/registration-header/registration-header.component.ts
  interfaces/Portalicious/src/app/components/page-layout/components/registration-menu/registration-menu.component.html
  interfaces/Portalicious/src/app/components/page-layout/components/registration-menu/registration-menu.component.ts
  interfaces/Portalicious/src/app/components/page-layout/page-layout.component.html
  interfaces/Portalicious/src/app/components/page-layout/page-layout.component.ts
  interfaces/Portalicious/src/app/domains/registration/registration.helper.ts
  interfaces/Portalicious/src/app/pages/project/project-monitoring/project-monitoring.component.html
  interfaces/Portalicious/src/app/pages/project/project-monitoring/project-monitoring.component.ts
  interfaces/Portalicious/src/app/pages/project/project-registrations/project-registration-activity-log/project-registration-activity-log.page.html
  interfaces/Portalicious/src/app/pages/project/project-registrations/project-registration-activity-log/project-registration-activity-log.page.ts
  interfaces/Portalicious/src/app/pages/project/project-registrations/project-registration-debit-cards/project-registration-debit-cards.page.html
  interfaces/Portalicious/src/app/pages/project/project-registrations/project-registration-debit-cards/project-registration-debit-cards.page.ts
  interfaces/Portalicious/src/app/pages/project/project-registrations/project-registration-personal-information/project-registration-personal-information.page.html
  interfaces/Portalicious/src/app/pages/project/project-registrations/project-registration-personal-information/project-registration-personal-information.page.ts
  interfaces/Portalicious/src/app/pages/project/project-registrations/project-registrations.component.ts
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
  interfaces/Portalicious/src/styles.scss
Labels: portalicious

#5812 docs: Fix weird syntax-glitches
  README.md
Labels: chore

#5811 E2E test Scope visible hidden
  e2e/portalicious/pages/ProjectTeam.ts
  e2e/portalicious/tests/ManageTeam/ScopeVisibleOnlyWhenSetToTrue.spec.ts
Labels: portalicious

#5773 portalicious: add note form
  interfaces/Portalicious/src/app/components/form-field-wrapper/form-field-wrapper.component.html
  interfaces/Portalicious/src/app/components/form/form-default.component.html
  interfaces/Portalicious/src/app/components/form/form-sidebar.component.html
  interfaces/Portalicious/src/app/components/page-layout/components/registration-header/add-note-form/add-note-form.component.html
  interfaces/Portalicious/src/app/components/page-layout/components/registration-header/add-note-form/add-note-form.component.ts
  interfaces/Portalicious/src/app/components/page-layout/components/registration-header/registration-header.component.html
  interfaces/Portalicious/src/app/components/page-layout/components/registration-header/registration-header.component.ts
  interfaces/Portalicious/src/app/domains/project/project.api.service.ts
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
  interfaces/Portalicious/src/styles.scss
Labels: portalicious

#5815 ci: Make disabled tests more explicit AB#30220
  .github/workflows/test_e2e_portalicious.yml
  e2e/portalicious/tests/CreateNewProject/CreateNewProjectSuccessfully.spec.ts
  e2e/portalicious/tests/CreateNewProject/FillInInvalidToken.spec.ts
  services/.env.example
Labels: chore

#5809 feat: make a check on status change when you change the max amount of transactions
  interfaces/Portal/src/app/program/edit-person-affected-popup/edit-person-affected-popup.component.ts
  interfaces/Portal/src/assets/i18n/ar.json
  interfaces/Portal/src/assets/i18n/en.json
  interfaces/Portal/src/assets/i18n/es.json
  interfaces/Portal/src/assets/i18n/fr.json
  interfaces/Portal/src/assets/i18n/nl.json
  services/121-service/src/registration/registrations.service.ts
  services/121-service/test/registrations/update-max-payment-registration.test.ts
Labels: enhancement

#5821 feat: Add new instance's deployment workflows
  .github/workflows/deploy_client-krcs-training_all.yml
  .github/workflows/deploy_client-krcs-training_portal.yml
  .github/workflows/deploy_client-krcs-training_service.yml
Labels: github_actions, chore

#5820 portalicious: monitoring & teams review
  interfaces/Portalicious/src/app/components/data-list/data-list.component.html
  interfaces/Portalicious/src/app/components/data-list/data-list.component.ts
  interfaces/Portalicious/src/app/components/not-available-label/not-available-label.component.html
  interfaces/Portalicious/src/app/components/not-available-label/not-available-label.component.ts
  interfaces/Portalicious/src/app/components/page-layout/components/registration-header/registration-header.component.html
  interfaces/Portalicious/src/app/components/page-layout/components/registration-header/registration-header.component.ts
  interfaces/Portalicious/src/app/components/query-table/query-table.component.html
  interfaces/Portalicious/src/app/pages/project/project-monitoring/metric-tile/metric-tile.component.html
  interfaces/Portalicious/src/app/pages/project/project-monitoring/project-monitoring.component.html
  interfaces/Portalicious/src/app/pages/project/project-monitoring/project-monitoring.component.ts
  interfaces/Portalicious/src/app/pages/project/project-team/project-team.component.ts
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
  interfaces/Portalicious/tailwind.config.ts
Labels: portalicious

#5828 Do not await cache voucher AB#30339
  services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.controller.ts
Labels: chore

#5831 Fix test and cache vouchers
  services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.controller.ts
  services/121-service/test/registrations/send-message-with-placeholder.test.ts
Labels: bugfix

#5790 portalicious: activity log
  interfaces/Portalicious/src/app/components/colored-chip/colored-chip.helper.ts
  interfaces/Portalicious/src/app/components/data-list/data-list.component.html
  interfaces/Portalicious/src/app/components/data-list/data-list.component.ts
  interfaces/Portalicious/src/app/components/page-layout/components/registration-menu/registration-menu.component.ts
  interfaces/Portalicious/src/app/components/query-table/query-table.component.html
  interfaces/Portalicious/src/app/components/query-table/query-table.component.ts
  interfaces/Portalicious/src/app/components/query-table/table-cell-date/table-cell-date.component.html
  interfaces/Portalicious/src/app/components/query-table/table-cell-text/table-cell-text.component.html
  interfaces/Portalicious/src/app/components/query-table/table-cell/table-cell-chip.component.ts
  interfaces/Portalicious/src/app/components/query-table/table-cell/table-cell-date.component.ts
  interfaces/Portalicious/src/app/components/query-table/table-cell/table-cell-text.component.ts
  interfaces/Portalicious/src/app/components/query-table/table-cell/table-cell.component.ts
  interfaces/Portalicious/src/app/domains/project/project.api.service.ts
  interfaces/Portalicious/src/app/domains/registration/registration.api.service.ts
  interfaces/Portalicious/src/app/domains/registration/registration.helpers.ts
  interfaces/Portalicious/src/app/domains/registration/registration.model.ts
  interfaces/Portalicious/src/app/pages/project/project-registrations/project-registration-activity-log/components/activity-log-expanded-row/activity-log-expanded-row.component.html
  interfaces/Portalicious/src/app/pages/project/project-registrations/project-registration-activity-log/components/activity-log-expanded-row/activity-log-expanded-row.component.ts
  interfaces/Portalicious/src/app/pages/project/project-registrations/project-registration-activity-log/components/table-cell-activity.component.ts
  interfaces/Portalicious/src/app/pages/project/project-registrations/project-registration-activity-log/components/table-cell-overview.component.ts
  interfaces/Portalicious/src/app/pages/project/project-registrations/project-registration-activity-log/project-registration-activity-log.page.html
  interfaces/Portalicious/src/app/pages/project/project-registrations/project-registration-activity-log/project-registration-activity-log.page.ts
  interfaces/Portalicious/src/app/pages/project/project-team/project-team.component.html
  interfaces/Portalicious/src/app/pages/project/project-team/project-team.component.ts
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
Labels: portalicious

#5817 Add E2E tests for Safaricom refactor
  e2e/pages/Payments/PaymentsPage.ts
  e2e/pages/RegistrationDetails/RegistrationDetailsPage.ts
  e2e/tests/121-Portal/MakeNewPayment/Safaricom/MakeSuccessfulPaymentSafaricom.spec.ts
  e2e/tests/121-Portal/MakeNewPayment/Safaricom/MissingNationalIdErrorSafaricom.spec.ts
  e2e/tests/121-Portal/MakeNewPayment/Safaricom/RetryPaymentSafaricom.spec.ts
  services/121-service/test/registrations/pagination/pagination-data.ts
Labels: Intersolve Visa Reimplementation, chore

#5835 refactor note endpoint(s)
  interfaces/Portal/src/app/services/programs-service-api.service.ts
  interfaces/Portalicious/src/app/domains/project/project.api.service.ts
  services/121-service/src/notes/dto/note.dto.ts
  services/121-service/src/notes/notes.controller.ts
  services/121-service/test/helpers/program.helper.ts
Labels: chore

#5837 fix: windows specific startup cmd AB#30396
  services/.env.example
  services/docker-compose.development.yml
Labels: chore

#5824 fix: First slice of fix issues AB#30290
  services/121-service/src/actions/actions.controller.ts
  services/121-service/src/base.entity.ts
  services/121-service/src/emails/emails.api.service.ts
  services/121-service/src/events/dto/get-event.dto.ts
  services/121-service/src/events/events.controller.ts
  services/121-service/src/events/events.service.spec.ts
  services/121-service/src/events/events.service.ts
  services/121-service/src/events/utils/events.helpers.ts
  services/121-service/src/events/utils/events.mapper.ts
  services/121-service/src/exchange-rate/exchange-rate.api.service.ts
  services/121-service/src/exchange-rate/exchange-rate.service.spec.ts
  services/121-service/src/financial-service-providers/enum/financial-service-provider-name.enum.ts
  services/121-service/src/guards/authenticated-user.decorator.ts
  services/121-service/src/guards/authenticated-user.guard.spec.ts
  services/121-service/src/kobo-connect/kobo-connect.api.service.ts
  services/121-service/src/kobo-connect/kobo-connect.service.ts
  services/121-service/src/main.ts
  services/121-service/src/metrics/dto/export-details.dto.ts
  services/121-service/src/metrics/dto/file.dto.ts
  services/121-service/src/metrics/dto/registration-type.dto.ts
  services/121-service/src/metrics/dto/rolo-type.dto.ts
  services/121-service/src/metrics/metrics.controller.ts
  services/121-service/src/metrics/metrics.service.ts
  services/121-service/src/notes/notes.controller.ts
  services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.controller.ts
  services/121-service/src/payments/payments.controller.ts
  services/121-service/src/programs/programs.controller.ts
  services/121-service/src/registration/dto/update-registration.dto.ts
  services/121-service/src/registration/registrations.controller.spec.ts
  services/121-service/src/registration/registrations.controller.ts
  services/121-service/src/registration/registrations.service.ts
  services/121-service/src/shared/services/custom-http.service.ts
  services/121-service/src/user/user.controller.ts
  services/121-service/src/utils/request-helper/request-helper.helper.ts
  services/121-service/test/helpers/registration.helper.ts
  services/121-service/test/payment/payment-count-completed.test.ts
  services/121-service/test/program/create-custom-attribute.test.ts
  services/121-service/test/program/create-program-question.test.ts
  services/121-service/test/registrations/pagination/pagination-data.ts
  services/121-service/test/registrations/pagination/send-message.test.ts
Labels: bugfix, chore

#5839 Portalicious: renamed component to pages
  interfaces/Portalicious/src/app/app.routes.ts
  interfaces/Portalicious/src/app/pages/project/project-monitoring/project-monitoring.page.html
  interfaces/Portalicious/src/app/pages/project/project-monitoring/project-monitoring.page.ts
  interfaces/Portalicious/src/app/pages/project/project-payments/project-payments.page.html
  interfaces/Portalicious/src/app/pages/project/project-payments/project-payments.page.ts
  interfaces/Portalicious/src/app/pages/project/project-registrations/project-registrations.page.html
  interfaces/Portalicious/src/app/pages/project/project-registrations/project-registrations.page.ts
  interfaces/Portalicious/src/app/pages/project/project-team/project-team.page.html
  interfaces/Portalicious/src/app/pages/project/project-team/project-team.page.ts
  interfaces/Portalicious/src/app/pages/projects-overview/projects-overview.page.html
  interfaces/Portalicious/src/app/pages/projects-overview/projects-overview.page.ts
Labels: chore

#5846 Make endpoints more consistent
  interfaces/Portal/src/app/services/programs-service-api.service.ts
  services/121-service/src/registration/registrations.controller.ts
  services/121-service/test/helpers/registration.helper.ts
Labels: chore

#5850 portalicious: rename typography utility
  interfaces/Portalicious/src/app/pages/project/project-monitoring/metric-tile/metric-tile.component.html
  interfaces/Portalicious/tailwind.config.ts
Labels: portalicious

#5851 portalicious: add typecheck in CI
  .github/workflows/test_interface_portalicious.yml
  interfaces/Portalicious/tailwind.config.ts
Labels: portalicious

#5847 Notes endpoints small refactors and refactor comments
  interfaces/Portal/src/app/services/programs-service-api.service.ts
  interfaces/Portalicious/src/app/domains/project/project.api.service.ts
  services/121-service/src/notes/notes.controller.ts
  services/121-service/src/notes/notes.module.ts
  services/121-service/src/notes/notes.service.ts
  services/121-service/test/helpers/program.helper.ts
Labels: chore

#5843 Remove unused demo fsp
  services/121-service/src/scripts/seed-init.ts
  services/121-service/src/seed-data/fsp/fsp-bank.json
  services/121-service/src/seed-data/fsp/fsp-mixed-attributes.json
  services/121-service/src/seed-data/fsp/fsp-no-attributes.json
  services/121-service/src/seed-data/program/program-test-one-admin.json
  services/121-service/src/seed-data/program/program-test.json
  services/121-service/test/program/__snapshots__/create-program.test.ts.snap
Labels: chore

#5827 portalicious: personal-information page AB#29985
  interfaces/Portalicious/src/app/components/data-list/data-list.component.html
  interfaces/Portalicious/src/app/components/data-list/data-list.component.ts
  interfaces/Portalicious/src/app/components/page-layout/components/registration-header/registration-header.component.ts
  interfaces/Portalicious/src/app/domains/financial-service-provider/financial-service-provider.api.service.ts
  interfaces/Portalicious/src/app/domains/financial-service-provider/financial-service-provider.model.ts
  interfaces/Portalicious/src/app/domains/project/project.api.service.ts
  interfaces/Portalicious/src/app/domains/project/project.helper.ts
  interfaces/Portalicious/src/app/domains/project/project.model.ts
  interfaces/Portalicious/src/app/domains/registration/registration.api.service.ts
  interfaces/Portalicious/src/app/domains/registration/registration.helper.ts
  interfaces/Portalicious/src/app/domains/registration/registration.helpers.ts
  interfaces/Portalicious/src/app/pages/project/project-monitoring/project-monitoring.page.ts
  interfaces/Portalicious/src/app/pages/project/project-registrations/project-registration-activity-log/components/table-cell-activity.component.ts
  interfaces/Portalicious/src/app/pages/project/project-registrations/project-registration-activity-log/project-registration-activity-log.page.ts
  interfaces/Portalicious/src/app/pages/project/project-registrations/project-registration-personal-information/project-registration-personal-information.page.html
  interfaces/Portalicious/src/app/pages/project/project-registrations/project-registration-personal-information/project-registration-personal-information.page.ts
  interfaces/Portalicious/src/app/services/http-wrapper.service.ts
  interfaces/Portalicious/src/app/services/translatable-string.service.ts
  interfaces/Portalicious/src/app/utils/dto-type.ts
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
  interfaces/Portalicious/src/styles.scss
  services/121-service/src/registration/enum/custom-data-attributes.ts
Labels: portalicious

#5859 portalicious: handle mutation errors in confirmation dialog
  interfaces/Portalicious/src/app/components/confirmation-dialog/confirmation-dialog.component.html
  interfaces/Portalicious/src/app/components/confirmation-dialog/confirmation-dialog.component.ts
  interfaces/Portalicious/src/app/components/form/form-sidebar.component.html
  interfaces/Portalicious/src/app/domains/project/project.api.service.ts
  interfaces/Portalicious/src/app/pages/project/project-team/project-team.page.html
  interfaces/Portalicious/src/app/pages/project/project-team/project-team.page.ts
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
Labels: portalicious

#5866 fix: filter on referenceId consisting of numbers
  services/121-service/src/registration/services/registrations-pagination.service.ts
  services/121-service/src/registration/validators/registrations-input-validator.ts
Labels: bugfix

#5864 chore: fail PRs with XXX comments
  .github/workflows/test_pull_request_formatting.yml
  interfaces/Portalicious/src/app/domains/project/project.helper.ts
  interfaces/Portalicious/src/app/domains/registration/registration.api.service.ts
  interfaces/Portalicious/src/app/pages/project/project-registrations/project-registration-personal-information/project-registration-personal-information.page.ts
  services/121-service/src/registration/enum/custom-data-attributes.ts
Labels: chore
