Repository global-121/121-platform, pull requests merged in 2024-12, with the labels that each got.

#6200 portalicious: add transactions table to payment page
  interfaces/Portalicious/src/app/components/page-layout/page-layout.component.html
  interfaces/Portalicious/src/app/components/query-table/query-table.component.ts
  interfaces/Portalicious/src/app/components/registrations-table/registrations-table.component.ts
  interfaces/Portalicious/src/app/domains/domain-api.service.ts
  interfaces/Portalicious/src/app/domains/metric/metric.api.service.ts
  interfaces/Portalicious/src/app/domains/metric/metric.model.ts
  interfaces/Portalicious/src/app/domains/transaction/transaction.helper.ts
  interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.html
  interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts
  interfaces/Portalicious/src/app/services/http-wrapper.service.ts
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
  services/121-service/src/metrics/metrics.service.ts
Labels: portalicious

#6213 portalicious: export payment list
  interfaces/Portalicious/src/app/pages/project-payments/components/create-payment/create-payment.component.ts
Labels: portalicious

#6215 portalicious: reload registrations page without page hanging
  e2e/portalicious/components/TableComponent.ts
  e2e/portalicious/tests/Navigation/BasicNavigation.spec.ts
  interfaces/Portalicious/src/app/components/query-table/query-table.component.ts
Labels: portalicious

#6179 feat: Add build+tests for Content-Security-Policy config
  .github/actions/build-interface/action.yml
  .github/workflows/deploy_test_portalicious.yml
  .github/workflows/test_interface_portalicious.yml
  interfaces/Portalicious/.env.example
  interfaces/Portalicious/.gitignore
  interfaces/Portalicious/_build-deployment-configuration.mjs
  interfaces/Portalicious/_build-manual-logout.mjs
  interfaces/Portalicious/_set-env-variables.mjs
  interfaces/Portalicious/_test-deployment-configuration.mjs
  interfaces/Portalicious/_verify-deployment-configuration.mjs
  interfaces/Portalicious/eslint.config.js
  interfaces/Portalicious/package.json
  interfaces/Portalicious/staticwebapp.config.base.json
Labels: enhancement, portalicious

#6197 Chore.dependabot sprint 143
  e2e/package-lock.json
  e2e/package.json
  interfaces/Portal/package-lock.json
  interfaces/Portal/package.json
  interfaces/Portalicious/package-lock.json
  interfaces/Portalicious/package.json
  k6/package-lock.json
  k6/package.json
  package-lock.json
  package.json
  services/121-service/package-lock.json
  services/121-service/package.json
  services/121-service/src/registration/dto/bulk-import.dto.ts
  services/mock-service/package-lock.json
  services/mock-service/package.json
Labels: chore

#6229 ci: Include Portalicious in Deploy All
  .github/workflows/deploy_staging_all.yml
Labels: portalicious

#6230 fix: Enforce override loading of .env-files + ESM All the Files
  interfaces/Portalicious/_set-env-variables.mjs
  interfaces/Portalicious/src/environments/environment.ts.template.mjs
Labels: bugfix, chore

#6198 Test.k6 test retry failed jobs on startup
  .github/workflows/test_k6.yml
  k6/models/reset.js
  k6/tests/retryFailedJobsOnStartupDuringQueueProcessing.js
  services/121-service/nodemon.json
  services/121-service/package.json
  services/121-service/src/queue-registry/queue-registry.module.ts
  services/121-service/src/queue-registry/queue-registry.service.ts
  services/121-service/src/scripts/scripts.controller.ts
  services/121-service/swagger.json
  services/docker-compose.development.yml
Labels: chore

#6236 Apply hotfix/v24.12-2
  .github/dependabot.yml
  services/.env.example
  services/121-service/package-lock.json
  services/121-service/package.json
  services/121-service/src/main.ts
  services/121-service/src/shared/middleware/azure-logger.middleware.ts
  services/121-service/src/shared/services/azure-log.service.ts
  services/121-service/src/shared/services/custom-http.service.ts
  services/mock-service/src/main.ts
Labels: bugfix

#6214 portalicious: payment chart
  interfaces/Portalicious/src/app/components/page-layout/components/payment-header/payment-header.component.ts
  interfaces/Portalicious/src/app/domains/payment/payment.api.service.ts
  interfaces/Portalicious/src/app/domains/transaction/transaction.helper.ts
  interfaces/Portalicious/src/app/pages/project-payment/components/project-payment-chart/project-payment-chart.component.html
  interfaces/Portalicious/src/app/pages/project-payment/components/project-payment-chart/project-payment-chart.component.ts
  interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.html
  interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts
  interfaces/Portalicious/src/app/services/auth/strategies/msal-auth/msal-auth.strategy.ts
  interfaces/Portalicious/src/app/utils/chart.ts
  interfaces/Portalicious/src/app/utils/tailwind.ts
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
  interfaces/Portalicious/tailwind.config.ts
  services/121-service/src/payments/payments.controller.ts
  services/121-service/src/payments/payments.service.ts
  services/121-service/swagger.json
Labels: portalicious

#6248 docs: Fix URL of CPU-usage
  README.md
Labels: ignore-for-release, chore

#6247 Better error on creating users
  services/121-service/src/user/user.service.ts
Labels: bugfix

#6249 ci: Adjust grouping of Dependabot PRs (+only ignore specific versions; not everything)
  .github/dependabot.yml
Labels: dependencies

#6255 Fix double scoped repo
  services/121-service/src/registration/modules/registration-data/registration-data.module.ts
  services/121-service/src/registration/modules/registration-data/repositories/registration-data.scoped.repository.ts
Labels: bugfix

#6250 ci: Include typecheck-test before Build
  .github/actions/build-service/action.yml
  .github/workflows/test_mock-service_code.yml
  .github/workflows/test_service_api.yml
  .github/workflows/test_service_code.yml
  README.md
Labels: ignore-for-release

#6252 Chore.rm old visa wallet entity
  services/121-service/src/migration/1733316713976-RemoveOldVisaWalletEntity.ts
  services/121-service/src/payments/fsp-integration/intersolve-visa/entities/intersolve-visa-wallet.entity.ts
  services/121-service/src/scripts/sql/mock-visa-customers.sql
Labels: chore

#6256 Chore: process feedback Portalicious SSO
  interfaces/Portalicious/src/app/components/form/form-default.component.html
  interfaces/Portalicious/src/app/pages/auth-callback/auth-callback.page.html
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
Labels: portalicious

#6216 portalicious: do payment review
  interfaces/Portalicious/src/app/components/registrations-table/registrations-table.component.html
  interfaces/Portalicious/src/app/components/registrations-table/registrations-table.component.ts
  interfaces/Portalicious/src/app/pages/project-payments/components/create-payment/create-payment.component.html
  interfaces/Portalicious/src/app/pages/project-payments/components/create-payment/create-payment.component.ts
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
  interfaces/Portalicious/tailwind.config.ts
Labels: portalicious

#6278 Portalicious: add allow popup error
  interfaces/Portalicious/src/app/components/form/form.component.ts
  interfaces/Portalicious/src/app/pages/login/login.page.ts
  interfaces/Portalicious/src/app/services/auth/strategies/msal-auth/msal-auth.login.component.ts
  interfaces/Portalicious/src/app/utils/is-pop-up-blocked.ts
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
Labels: portalicious

#6251 portalicious: refactor page layout
  interfaces/Portalicious/src/app/app.routes.ts
  interfaces/Portalicious/src/app/components/page-layout/components/breadcrumbs-title/breadcrumbs-title.component.html
  interfaces/Portalicious/src/app/components/page-layout/components/breadcrumbs-title/breadcrumbs-title.component.ts
  interfaces/Portalicious/src/app/components/page-layout/components/page-layout-title-and-actions/page-layout-title-and-actions.component.html
  interfaces/Portalicious/src/app/components/page-layout/components/page-layout-title-and-actions/page-layout-title-and-actions.component.ts
  interfaces/Portalicious/src/app/components/page-layout/components/payment-header/payment-header.component.html
  interfaces/Portalicious/src/app/components/page-layout/components/registration-header/registration-header.component.html
  interfaces/Portalicious/src/app/components/page-layout/page-layout.component.html
  interfaces/Portalicious/src/app/components/page-layout/page-layout.component.ts
  interfaces/Portalicious/src/app/components/registration-page-layout/components/add-note-form/add-note-form.component.html
  interfaces/Portalicious/src/app/components/registration-page-layout/components/add-note-form/add-note-form.component.ts
  interfaces/Portalicious/src/app/components/registration-page-layout/components/registration-menu/registration-menu.component.html
  interfaces/Portalicious/src/app/components/registration-page-layout/components/registration-menu/registration-menu.component.ts
  interfaces/Portalicious/src/app/components/registration-page-layout/registration-page-layout.component.html
  interfaces/Portalicious/src/app/components/registration-page-layout/registration-page-layout.component.ts
  interfaces/Portalicious/src/app/guards/found-resource.guard.ts
  interfaces/Portalicious/src/app/guards/project-permissions-guard.ts
  interfaces/Portalicious/src/app/pages/project-payment/components/export-payment-instructions/export-payment-instructions.component.html
  interfaces/Portalicious/src/app/pages/project-payment/components/export-payment-instructions/export-payment-instructions.component.ts
  interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.html
  interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/project-registration-activity-log.page.html
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/project-registration-activity-log.page.ts
  interfaces/Portalicious/src/app/pages/project-registration-debit-cards/project-registration-debit-cards.page.html
  interfaces/Portalicious/src/app/pages/project-registration-debit-cards/project-registration-debit-cards.page.ts
  interfaces/Portalicious/src/app/pages/project-registration-personal-information/project-registration-personal-information.page.html
  interfaces/Portalicious/src/app/pages/project-registration-personal-information/project-registration-personal-information.page.ts
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
Labels: portalicious

#6276 portalicious: payment left metrics
  interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.html
  interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
Labels: portalicious

#6282 fix+refactor: Swap and Rename properties (typos) for CBE API
  services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/commercial-bank-ethiopia.api.service.ts
  services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/commercial-bank-ethiopia.mock.ts
  services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/commercial-bank-ethiopia.service.spec.ts
  services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/commercial-bank-ethiopia.service.ts
  services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/dto/commercial-bank-ethiopia-transfer-payload.dto.ts
  services/121-service/src/shared/xml/CreditTransfer.xml
  services/121-service/src/shared/xml/TransactionStatus.xml
Labels: ignore-for-release

#6280 portalicious: retry transfers
  interfaces/Portalicious/src/app/components/query-table/query-table.component.ts
  interfaces/Portalicious/src/app/components/registrations-table/registrations-table.component.html
  interfaces/Portalicious/src/app/components/registrations-table/registrations-table.component.ts
  interfaces/Portalicious/src/app/domains/metric/metric.api.service.ts
  interfaces/Portalicious/src/app/domains/metric/metric.model.ts
  interfaces/Portalicious/src/app/domains/payment/payment.api.service.ts
  interfaces/Portalicious/src/app/pages/project-payment/components/retry-transfers-dialog/retry-transfers-dialog.component.html
  interfaces/Portalicious/src/app/pages/project-payment/components/retry-transfers-dialog/retry-transfers-dialog.component.ts
  interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.html
  interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts
  interfaces/Portalicious/src/app/services/paginate-query.service.ts
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
Labels: portalicious

#6253 Refactor.cascade delete
  services/121-service/.eslintrc.js
  services/121-service/eslint-plugin-custom-rules/index.js
  services/121-service/eslint-plugin-custom-rules/rules/typeorm-cascade-ondelete.js
  services/121-service/package-lock.json
  services/121-service/package.json
  services/121-service/src/actions/action.entity.ts
  services/121-service/src/actions/utils/action.mapper.spec.ts
  services/121-service/src/base.entity.ts
  services/121-service/src/events/entities/event-attribute.entity.ts
  services/121-service/src/events/entities/event.entity.ts
  services/121-service/src/migration/1733492799598-refactor-ondelete-cascade.ts
  services/121-service/src/notes/note.entity.ts
  services/121-service/src/notifications/latest-message.entity.ts
  services/121-service/src/notifications/message-template/message-template.entity.ts
  services/121-service/src/notifications/twilio.entity.ts
  services/121-service/src/notifications/whatsapp/try-whatsapp.entity.ts
  services/121-service/src/notifications/whatsapp/whatsapp-pending-message.entity.ts
  services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/commercial-bank-ethiopia-account-enquiries.entity.ts
  services/121-service/src/payments/fsp-integration/intersolve-visa/entities/intersolve-visa-child-wallet.entity.ts
  services/121-service/src/payments/fsp-integration/intersolve-visa/entities/intersolve-visa-customer.entity.ts
  services/121-service/src/payments/fsp-integration/intersolve-visa/entities/intersolve-visa-parent-wallet.entity.ts
  services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher-instructions.entity.ts
  services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.entity.ts
  services/121-service/src/payments/fsp-integration/safaricom/entities/safaricom-transfer.entity.ts
  services/121-service/src/payments/imagecode/image-code-export-vouchers.entity.ts
  services/121-service/src/payments/transactions/latest-transaction.entity.ts
  services/121-service/src/payments/transactions/transaction.entity.ts
  services/121-service/src/program-financial-service-provider-configurations/entities/program-financial-service-provider-configuration-property.entity.ts
  services/121-service/src/program-financial-service-provider-configurations/entities/program-financial-service-provider-configuration.entity.ts
  services/121-service/src/program-financial-service-provider-configurations/program-financial-service-provider-configurations.service.spec.ts
  services/121-service/src/program-financial-service-provider-configurations/program-financial-service-provider-configurations.service.ts
  services/121-service/src/programs/program-aidworker.entity.ts
  services/121-service/src/programs/program-registration-attribute.entity.ts
  services/121-service/src/programs/program.entity.ts
  services/121-service/src/programs/programs.controller.ts
  services/121-service/src/registration/registration-attribute-data.entity.ts
  services/121-service/src/registration/registration-view.entity.ts
  services/121-service/src/registration/registration.entity.ts
  services/121-service/src/user/user.entity.ts
  services/121-service/src/user/utils/user.mapper.spec.ts
  services/121-service/test/helpers/program.helper.ts
  services/121-service/test/program/delete-program.test.ts
Labels: bugfix

#6297 add squagger
  services/121-service/src/config.ts
Labels: chore

#6298 Remove visa card id from transaction in portal
  interfaces/Portal/src/app/models/payment.model.ts
  interfaces/Portal/src/app/program/registration-activity-detail-accordion/registration-activity-detail-accordion.component.html
  interfaces/Portal/src/app/program/registration-activity-detail-accordion/registration-activity-detail-accordion.component.ts
  interfaces/Portal/src/app/shared/payment.utils.ts
  interfaces/Portal/src/assets/i18n/ar.json
  interfaces/Portal/src/assets/i18n/en.json
  interfaces/Portal/src/assets/i18n/es.json
  interfaces/Portal/src/assets/i18n/fr.json
  interfaces/Portal/src/assets/i18n/nl.json
  interfaces/Portal/src/assets/i18n/ru.json
Labels: bugfix

#6292 Chore.dependabot sprint 144
  interfaces/Portalicious/package-lock.json
  interfaces/Portalicious/package.json
  interfaces/Portalicious/src/app/components/file-upload-control/file-upload-control.component.html
  interfaces/Portalicious/src/app/components/file-upload-control/file-upload-control.component.ts
  interfaces/Portalicious/src/app/components/query-table/components/query-table-global-search/query-table-global-search.component.html
  interfaces/Portalicious/src/app/components/query-table/components/query-table-global-search/query-table-global-search.component.ts
  interfaces/Portalicious/src/app/components/query-table/query-table.component.html
  interfaces/Portalicious/src/app/components/query-table/query-table.component.ts
  interfaces/Portalicious/src/app/components/registrations-table/registrations-table.component.html
  interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.html
  interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-contents-with-custom-message/change-status-contents-with-custom-message.component.html
  interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-contents-with-custom-message/change-status-contents-with-custom-message.component.ts
  interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-contents-with-templated-message/change-status-contents-with-templated-message.component.html
  interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-contents-with-templated-message/change-status-contents-with-templated-message.component.ts
  interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-contents-without-message/change-status-contents-without-message.component.html
  interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-contents-without-message/change-status-contents-without-message.component.ts
  interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-dialog/change-status-dialog.component.html
  interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-dialog/change-status-dialog.component.ts
  interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-submit-buttons/change-status-submit-buttons.component.html
  interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-submit-buttons/change-status-submit-buttons.component.ts
  interfaces/Portalicious/src/app/pages/project-registrations/components/export-registrations/export-registrations.component.ts
  interfaces/Portalicious/src/app/pages/project-registrations/components/import-registrations/import-registrations.component.html
  interfaces/Portalicious/src/app/pages/project-registrations/components/send-message-dialog/send-message-dialog.component.ts
  interfaces/Portalicious/src/app/pages/project-team/project-team.page.html
  interfaces/Portalicious/src/app/pages/users/users.page.html
  interfaces/Portalicious/src/app/services/export.service.ts
  interfaces/Portalicious/src/app/services/paginate-query.service.ts
  services/121-service/package-lock.json
  services/121-service/package.json
Labels: chore

#6287 refactor: rename queue-registry to queues
  services/121-service/module-dependencies.md
  services/121-service/src/app.module.ts
  services/121-service/src/financial-service-provider-callback-job-processors/processors/safaricom-timeout-callback-job.processor.ts
  services/121-service/src/financial-service-provider-callback-job-processors/processors/safaricom-transfer-callback-job.processor.ts
  services/121-service/src/notifications/enum/process-names.enum.ts
  services/121-service/src/notifications/message-incoming/message-incoming.module.ts
  services/121-service/src/notifications/message-incoming/message-incoming.service.spec.ts
  services/121-service/src/notifications/message-incoming/message-incoming.service.ts
  services/121-service/src/notifications/message-queue-mapping.const.ts
  services/121-service/src/notifications/message-queues/message-queues.module.ts
  services/121-service/src/notifications/message-queues/message-queues.service.spec.ts
  services/121-service/src/notifications/message-queues/message-queues.service.ts
  services/121-service/src/notifications/processors/message-incoming.processor.ts
  services/121-service/src/notifications/processors/message-status-callback.processor.ts
  services/121-service/src/notifications/processors/message.processor.ts
  services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/commercial-bank-ethiopia.module.ts
  services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/commercial-bank-ethiopia.service.spec.ts
  services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/commercial-bank-ethiopia.service.ts
  services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/processors/commercial-bank-ethiopia.processor.ts
  services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.module.ts
  services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.service.spec.ts
  services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.service.ts
  services/121-service/src/payments/fsp-integration/intersolve-voucher/processors/intersolve-voucher.processor.ts
  services/121-service/src/payments/fsp-integration/safaricom/safaricom.module.ts
  services/121-service/src/payments/fsp-integration/safaricom/safaricom.service.spec.ts
  services/121-service/src/payments/fsp-integration/safaricom/safaricom.service.ts
  services/121-service/src/queues-registry/enum/create-message-queue-names.enum.ts
  services/121-service/src/queues-registry/enum/message-callback-queue-names.enum.ts
  services/121-service/src/queues-registry/enum/registration-queue-names.enum.ts
  services/121-service/src/queues-registry/enum/safaricom-callback-queue-names.enum.ts
  services/121-service/src/queues-registry/enum/transaction-job-queue-names.enum.ts
  services/121-service/src/queues-registry/queues-registry.module.ts
  services/121-service/src/queues-registry/queues-registry.service.ts
  services/121-service/src/registration/enum/process-name-registration.enum.ts
  services/121-service/src/registration/modules/queue-registrations-update/queue-registrations-update.module.ts
  services/121-service/src/registration/processsors/registrations-update.processor.ts
  services/121-service/src/registration/registrations.module.ts
  services/121-service/src/registration/services/queue-registrations-update.service.ts
  services/121-service/src/registration/services/registrations-import.service.ts
  services/121-service/src/scripts/scripts.module.ts
  services/121-service/src/scripts/seed-init.ts
  services/121-service/src/shared/enum/queue-process.names.enum.ts
  services/121-service/src/transaction-job-processors/processors/transaction-job-intersolve-visa.processor.ts
  services/121-service/src/transaction-job-processors/processors/transaction-job-safaricom.processor.ts
  services/121-service/src/transaction-queues/transaction-queues.module.ts
  services/121-service/src/transaction-queues/transaction-queues.service.spec.ts
  services/121-service/src/transaction-queues/transaction-queues.service.ts
Labels: chore

#6299 chore: add script to download all logs
  package.json
  tools/.env.example
  tools/.gitignore
  tools/download-logs.mjs
  tools/package-lock.json
  tools/package.json
Labels: chore

#6281 portalicious: create single payment exports AB#31323
  interfaces/Portalicious/src/app/components/page-layout/components/payment-header/payment-header.component.html
  interfaces/Portalicious/src/app/domains/payment/payment.api.service.ts
  interfaces/Portalicious/src/app/pages/project-payment/components/export-payment-instructions/export-payment-instructions.component.html
  interfaces/Portalicious/src/app/pages/project-payment/components/export-payment-instructions/export-payment-instructions.component.ts
  interfaces/Portalicious/src/app/pages/project-payment/components/single-payment-export/single-payment-export.component.html
  interfaces/Portalicious/src/app/pages/project-payment/components/single-payment-export/single-payment-export.component.ts
  interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.html
  interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts
  interfaces/Portalicious/src/app/services/export.service.ts
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
Labels: portalicious

#6310 fix: only update at intersolve when value is present
  services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.service.ts
Labels: chore

#6285 AB#30601 Personal Info generic attributes refactor
  interfaces/Portalicious/src/app/domains/project/project-attribute.helpers.ts
  interfaces/Portalicious/src/app/domains/project/project.api.service.ts
  interfaces/Portalicious/src/app/domains/project/project.helper.ts
  interfaces/Portalicious/src/app/domains/registration/registration.helper.ts
  interfaces/Portalicious/src/app/pages/project-registration-personal-information/project-registration-personal-information.page.ts
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
  services/121-service/src/registration/enum/registration-attribute.enum.ts
  services/121-service/src/shared/enum/language.enums.ts
Labels: enhancement

#6311 Hotfix/v24.12 5
  services/121-service/src/financial-service-providers/enum/financial-service-provider-name.enum.ts
  services/121-service/src/financial-service-providers/financial-service-providers-settings.const.ts
  services/121-service/src/payments/payments.service.ts
Labels: bugfix

#6313 Enable NLRC deploy again
  .github/workflows/deploy_client-nlrc_portal.yml
  .github/workflows/deploy_client-nlrc_service.yml
Labels: chore

#6307 Fix: Make sure CBE payment doesn't break on incorrect input/properties
  services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/commercial-bank-ethiopia.api.service.ts
  services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/commercial-bank-ethiopia.service.spec.ts
  services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/commercial-bank-ethiopia.service.ts
  services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/processors/commercial-bank-ethiopia.processor.spec.ts
Labels: bugfix

#6312 portalicious: fix transfer value in payment creation AB#32309
  interfaces/Portalicious/src/app/pages/project-payments/components/create-payment/create-payment.component.ts
Labels: portalicious

#6317 ci: Reduce "destined to fail" dependency combinations
  .github/dependabot.yml
Labels: dependencies

#6326 remove deletes from training in migration cascade delete
  services/121-service/src/migration/1733492799598-refactor-ondelete-cascade.ts
Labels: bugfix

#6327 payment card redesign
  interfaces/Portalicious/src/app/pages/project-payments/components/payment-summary-card/payment-summary-card.component.ts
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
Labels: portalicious

#6283 portalicious: import reconciliation data
  interfaces/Portalicious/eslint.config.js
  interfaces/Portalicious/src/app/components/file-upload-control/file-upload-control.component.html
  interfaces/Portalicious/src/app/components/import-file-dialog/import-file-dialog.component.html
  interfaces/Portalicious/src/app/components/import-file-dialog/import-file-dialog.component.ts
  interfaces/Portalicious/src/app/components/registrations-table/registrations-table.component.ts
  interfaces/Portalicious/src/app/domains/metric/metric.api.service.ts
  interfaces/Portalicious/src/app/domains/payment/payment.api.service.ts
  interfaces/Portalicious/src/app/pages/project-payment/components/import-reconciliation-data/import-reconciliation-data.component.html
  interfaces/Portalicious/src/app/pages/project-payment/components/import-reconciliation-data/import-reconciliation-data.component.ts
  interfaces/Portalicious/src/app/pages/project-payment/components/single-payment-export/single-payment-export.component.ts
  interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.html
  interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts
  interfaces/Portalicious/src/app/pages/project-registrations/components/import-registrations/import-registrations.component.html
  interfaces/Portalicious/src/app/pages/project-registrations/components/import-registrations/import-registrations.component.ts
  interfaces/Portalicious/src/app/services/download.service.ts
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
Labels: portalicious

#6325 portalicious: fix navigation post create-payment
  interfaces/Portalicious/src/app/pages/project-payments/components/create-payment/create-payment.component.ts
Labels: portalicious

#6329 fix: voucher get balance AB#32362
  services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.service.ts
Labels: bugfix

#6284 Add e2e tests for do payment in portalicious
  e2e/portalicious/pages/PaymentsPage.ts
  e2e/portalicious/pages/RegistrationsPage.ts
  e2e/portalicious/tests/DoPayment/DoSuccessfulPayment.spec.ts
  e2e/portalicious/tests/DoPayment/DoSuccessfulPaymentWithExcelFsp.spec.ts
  e2e/portalicious/tests/DoPayment/ShowPaymentSummary.spec.ts
  e2e/portalicious/tests/ExportPeopleAffectedList/ExportDuplicateRegistrations.spec.ts
  e2e/portalicious/tests/ExportPeopleAffectedList/ExportHighVolumeOfRegistrations.spec.ts
  e2e/portalicious/tests/ExportPeopleAffectedList/ExportRegistrationsDataChanges.spec.ts
  e2e/portalicious/tests/ExportPeopleAffectedList/ExportRegistrationsList.spec.ts
  e2e/portalicious/tests/ExportPeopleAffectedList/NoPermissionsForExport.spec.ts
  interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts
  interfaces/Portalicious/src/app/pages/project-payments/components/create-payment/create-payment.component.html
  interfaces/Portalicious/src/app/pages/project-payments/components/payment-summary-card/payment-summary-card.component.html
  interfaces/Portalicious/src/app/pages/project-payments/components/payment-summary-card/payment-summary-card.component.ts
  services/121-service/test/registrations/pagination/pagination-data.ts
Labels: chore, portalicious

#6333 Substituded + blocked combi
  services/121-service/src/payments/fsp-integration/intersolve-visa/mappers/visa-card-121-status-map.csv
  services/121-service/test/visa-card/issue-new-card.test.ts
Labels: bugfix

#6332 Hotfix/v24.12 9
  interfaces/Portal/src/assets/i18n/ar.json
  interfaces/Portal/src/assets/i18n/en.json
  interfaces/Portal/src/assets/i18n/es.json
  interfaces/Portal/src/assets/i18n/fr.json
  interfaces/Portal/src/assets/i18n/nl.json
  interfaces/Portal/src/assets/i18n/ru.json
  services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.service.ts
  services/121-service/src/program-attributes/program-attributes.service.ts
  services/121-service/test/program/__snapshots__/create-program.test.ts.snap
Labels: bugfix

#6334 Only remove fsp config of deleted registrations
  services/121-service/module-dependencies.md
  services/121-service/src/program-financial-service-provider-configurations/entities/program-financial-service-provider-configuration.entity.ts
  services/121-service/src/program-financial-service-provider-configurations/program-financial-service-provider-configurations.module.ts
  services/121-service/src/program-financial-service-provider-configurations/program-financial-service-provider-configurations.service.spec.ts
  services/121-service/src/program-financial-service-provider-configurations/program-financial-service-provider-configurations.service.ts
  services/121-service/swagger.json
  services/121-service/test/program/__snapshots__/manage-program-financial-service-provider-configuration.test.ts.snap
  services/121-service/test/program/manage-program-financial-service-provider-configuration.test.ts
Labels: bugfix

#6335 Hotfix/v24.12 10
  services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.api.service.ts
Labels: bugfix
