Repository global-121/121-platform, pull requests merged in 2025-06, with the labels that each got.

#6897 fix: update purple 50
  interfaces/portal/tailwind.config.ts
Labels: bugfix

#6923 Revert "feat: Use t3-env to validate ENV-vars (in Mock-Service) (#6896)"
  services/mock-service/.eslintrc.js
  services/mock-service/package-lock.json
  services/mock-service/package.json
  services/mock-service/src/config.ts
  services/mock-service/src/env.ts
  services/mock-service/src/fsp-integration/intersolve-visa/intersolve-visa.mock.service.ts
  services/mock-service/src/main.ts
  services/mock-service/tsconfig.json
Labels: bugfix

#6924 fix: Add check on requirements of Azure AD payload
  services/121-service/src/strategies/azure-ad.strategy.ts
Labels: bugfix

#6941 Frontend dependabot combined for sprint 157
  interfaces/portal/package-lock.json
  interfaces/portal/package.json
  package-lock.json
Labels: chore

#6947 Activity overview & payment page on pending/waiting state show message
  e2e/portal/tests/ViewPayment/ValidateViewPaymentsTable.spec.ts
  interfaces/portal/src/app/pages/project-payment/project-payment.page.ts
  interfaces/portal/src/app/pages/project-registration-activity-log/components/activity-log-expanded-row/activity-log-expanded-row.component.ts
  interfaces/portal/src/locale/messages.xlf
Labels: enhancement

#6938 Improve test flakiness: wait for registration changes to be complete
  services/121-service/test/helpers/registration.helper.ts
  services/121-service/test/registrations/bulk-update-registration.test.ts
Labels: chore

#6931 Add extra e2e tests for bulk update registrations
  e2e/portal/pages/RegistrationsPage.ts
  e2e/portal/tests/UpdateRegistrations/BulkUpdateOnlyVisibleForAdminPermissions.spec.ts
  e2e/portal/tests/UpdateRegistrations/BulkUpdateVisibleInActivityLog.spec.ts
  e2e/portal/tests/__screenshots__/UpdateRegistrations/BulkUpdateVisibleInActivityLog.spec.ts/exported-csv.csv
Labels: chore

#6957 fix: reset table selection and form fields on bulk update
  interfaces/portal/src/app/pages/project-registrations/components/import-registrations-menu/import-registrations-menu.component.html
  interfaces/portal/src/app/pages/project-registrations/components/import-registrations-menu/import-registrations-menu.component.ts
  interfaces/portal/src/app/pages/project-registrations/components/update-registrations/update-registrations.component.ts
  interfaces/portal/src/app/pages/project-registrations/project-registrations.page.html
Labels: bugfix

#6958 ci: Make use of defined Prettier version
  .github/workflows/test_formatting.yml
Labels: ignore-for-release, chore

#6959 Rename FinancialServiceProvider to fsp in comments and string in the BE
  services/121-service/src/fsps/fsp-settings.const.ts
  services/121-service/src/fsps/fsp-settings.helpers.ts
  services/121-service/src/fsps/fsp.controller.ts
  services/121-service/src/fsps/fsp.service.ts
  services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/commercial-bank-ethiopia.service.ts
  services/121-service/src/payments/fsp-integration/excel/excel.module.ts
  services/121-service/src/payments/payments.controller.ts
  services/121-service/src/payments/reconciliation/excel/excel-reconciliation.controller.ts
  services/121-service/src/program-fsp-configurations/dtos/program-fsp-configuration-response.dto.ts
  services/121-service/src/program-fsp-configurations/program-fsp-configurations.controller.ts
  services/121-service/src/program-fsp-configurations/program-fsp-configurations.service.spec.ts
  services/121-service/src/program-fsp-configurations/program-fsp-configurations.service.ts
  services/121-service/src/programs/programs.service.ts
  services/121-service/src/registration/registrations.controller.ts
  services/121-service/src/registration/registrations.service.ts
  services/121-service/test/program/__snapshots__/manage-program-fsp-configuration.test.ts.snap
  services/121-service/test/program/manage-program-fsp-configuration.test.ts
Labels: chore

#6966 Readme use setval
  README.md
Labels: chore

#6963 rename registered to new
  e2e/portal/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusNew.spec.ts
  e2e/portal/tests/ChangeRegistrationStatus/MovePasFromNewToValidated.spec.ts
  e2e/portal/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByDropdownSelection.spec.ts
  e2e/portal/tests/__screenshots__/ExportRegistrations/ExportRegistrationsDataChanges.spec.ts/exported-xlsx.csv
  interfaces/portal/src/app/components/colored-chip/colored-chip.helper.ts
  interfaces/portal/src/app/domains/message/message.helper.ts
  interfaces/portal/src/app/domains/registration/registration.helper.ts
  interfaces/portal/src/app/domains/registration/registration.model.ts
  interfaces/portal/src/app/pages/project-registrations/components/change-status-dialog/change-status-dialog.component.ts
  interfaces/portal/src/app/pages/project-registrations/components/import-registrations/import-registrations.component.ts
  interfaces/portal/src/locale/messages.xlf
  services/121-service/src/events/events.service.spec.ts
  services/121-service/src/metrics/metrics.service.ts
  services/121-service/src/migration/1750762936357-rename-registered-to-new.ts
  services/121-service/src/notifications/enum/message-type.enum.ts
  services/121-service/src/notifications/enum/program-notification.enum.ts
  services/121-service/src/registration/enum/registration-status.enum.ts
  services/121-service/src/registration/helpers/status-change.helper.spec.ts
  services/121-service/src/registration/helpers/status-change.helper.ts
  services/121-service/src/registration/registrations.controller.ts
  services/121-service/src/registration/registrations.service.ts
  services/121-service/src/registration/services/registrations-bulk.service.spec.ts
  services/121-service/src/registration/services/registrations-import.service.ts
  services/121-service/src/seed-data/message-template/message-template-generic.const.ts
  services/121-service/src/seed-data/message-template/message-template-nlrc-pv.const.ts
  services/121-service/test/metrics/export-list.test.ts
  services/121-service/test/program/message-template.test.ts
  services/121-service/test/registrations/delete-registration.test.ts
  services/121-service/test/registrations/pagination/update-registration-status.test.ts
Labels: enhancement

#6970 chore: consistent usage of "test:integration"
  services/121-service/jest.integration.config.js
  services/121-service/package.json
Labels: chore

#6971 Test flakiness: wait for events instead of changed registrations
  services/121-service/test/event/filter-events.test.ts
  services/121-service/test/helpers/registration.helper.ts
  services/121-service/test/registrations/delete-registration.test.ts
  services/121-service/test/registrations/pagination/update-registration-status.test.ts
Labels: bugfix

#6979 refactor and bugfix
  services/121-service/src/transaction-jobs/services/transaction-jobs-helper.service.spec.ts
  services/121-service/src/transaction-jobs/services/transaction-jobs-helper.service.ts
  services/121-service/src/transaction-jobs/services/transaction-jobs-intersolve-visa.service.ts
  services/121-service/src/transaction-jobs/services/transaction-jobs-nedbank.service.spec.ts
  services/121-service/src/transaction-jobs/services/transaction-jobs-nedbank.service.ts
  services/121-service/src/transaction-jobs/services/transaction-jobs-safaricom.service.ts
  services/121-service/test/payment/payment-count-completed.test.ts
Labels: bugfix
