Repository global-121/121-platform, pull requests merged in 2025-03, with the labels that each got.

#6577 chore: cleanup unused XML files
  services/121-service/src/shared/xml/ApprovePreOrder.xml
  services/121-service/src/shared/xml/OrderImportLine.xml
  services/121-service/src/shared/xml/TradeHeader.xml
Labels: chore

#6578 chore: remove duplicate db-resets from integration tests
  services/121-service/test/registrations/update-registration-program-financial-service-provider-configuration.test.ts
  services/121-service/test/registrations/update-registration.test.ts
Labels: chore

#6580 feat: Enable PowerBI-dashboards in DRC-Portal
  .github/workflows/deploy_client-drc_portal.yml
Labels: enhancement

#6581 chore: run Jest with colors
  services/.env.example
  services/121-service/README.md
Labels: chore

#6579 chore: refactor rtlhelper
  interfaces/Portalicious/src/app/components/form/form-sidebar.component.html
  interfaces/Portalicious/src/app/components/page-layout/components/header/header.component.html
  interfaces/Portalicious/src/app/components/query-table/components/query-table-column-management/query-table-column-management.component.html
  interfaces/Portalicious/src/app/components/query-table/components/query-table-global-search/query-table-global-search.component.html
  interfaces/Portalicious/src/app/services/rtl-helper.service.ts
Labels: chore

#6582 Remove excel fail seed and use delete program fsp config property instead
  e2e/portalicious/tests/ViewPayment/ErrorOnMissinCollumnMatchConfiguration.spec.ts
  services/121-service/src/scripts/enum/seed-script.enum.ts
  services/121-service/src/scripts/seed-configuration.const.ts
  services/121-service/src/seed-data/program/program-nlrc-pv-excel-fail.json
Labels: chore

#6591 Throw 404 instead of 500 on failed voucher retrieval
  services/121-service/src/payments/imagecode/image-code.service.ts
Labels: chore

#6584 chore: refactor rtl-friendly chevron icons
  interfaces/Portalicious/src/app/components/page-layout/page-layout.component.html
  interfaces/Portalicious/src/app/components/page-layout/page-layout.component.ts
  interfaces/Portalicious/src/app/components/query-table/query-table.component.html
  interfaces/Portalicious/src/app/services/rtl-helper.service.ts
Labels: chore

#6599 feat: show "Fail reason" in activity log when a transfer fails
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/activity-log-expanded-row/activity-log-expanded-row.component.ts
Labels: enhancement

#6600 chore: minor ui fixes on portalicious
  interfaces/Portalicious/src/app/components/card-grid/card-grid.component.html
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/table-cell-overview/table-cell-overview.component.html
  interfaces/Portalicious/src/styles.scss
Labels: chore

#6605 Fix export last payments
  interfaces/Portalicious/src/app/pages/project-payments/components/export-payments/export-payments.component.ts
Labels: bugfix

#6594 Add image credits for ZOA
  interfaces/Portalicious/src/app/pages/login/login.page.html
  interfaces/Portalicious/src/locale/messages.xlf
Labels: enhancement

#6608 feat: registration-by-reference-id endpoint
  interfaces/Portalicious/src/app/app.routes.ts
  interfaces/Portalicious/src/app/pages/registration-by-reference-id/registration-by-reference-id.page.html
  interfaces/Portalicious/src/app/pages/registration-by-reference-id/registration-by-reference-id.page.ts
Labels: enhancement

#6617 Revert "chore(deps): bump the azuremsal group across 1 directory with…
  interfaces/Portalicious/package-lock.json
  interfaces/Portalicious/package.json
  interfaces/Portalicious/src/app/services/auth/strategies/msal-auth/msal-auth.app-providers.ts
Labels: bugfix

#6612 Fix move registration from completed to declined
  services/121-service/src/registration/registrations.service.ts
Labels: chore

#6596 Turn explicit styles/layout for Left/Right into Start/End (for Arabic-compatibility)
  .github/workflows/test_e2e_portalicious.yml
  interfaces/Portalicious/.env.example
  interfaces/Portalicious/eslint.config.js
  interfaces/Portalicious/package-lock.json
  interfaces/Portalicious/package.json
  interfaces/Portalicious/src/app/app.component.html
  interfaces/Portalicious/src/app/app.component.ts
  interfaces/Portalicious/src/app/components/button-menu/button-menu.component.html
  interfaces/Portalicious/src/app/components/button-menu/button-menu.component.ts
  interfaces/Portalicious/src/app/components/file-upload-control/file-upload-control.component.html
  interfaces/Portalicious/src/app/components/file-upload-control/file-upload-control.component.ts
  interfaces/Portalicious/src/app/components/info-tooltip/info-tooltip.component.html
  interfaces/Portalicious/src/app/components/info-tooltip/info-tooltip.component.ts
  interfaces/Portalicious/src/app/components/page-layout/components/header/header.component.html
  interfaces/Portalicious/src/app/components/page-layout/page-layout.component.html
  interfaces/Portalicious/src/app/components/query-table/components/query-table-column-management/query-table-column-management.component.html
  interfaces/Portalicious/src/app/components/query-table/components/query-table-global-search/query-table-global-search.component.html
  interfaces/Portalicious/src/app/components/registration-page-layout/components/registration-duplicates-banner/registration-duplicates-banner.component.html
  interfaces/Portalicious/src/app/pages/project-payment/components/import-reconciliation-data/import-reconciliation-data.component.html
  interfaces/Portalicious/src/app/pages/project-payments/components/create-payment/create-payment.component.html
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/table-cell-overview/table-cell-overview.component.html
  interfaces/Portalicious/src/app/pages/project-registration-personal-information/components/edit-personal-information/edit-personal-information.component.html
  interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-contents-without-message/change-status-contents-without-message.component.html
  interfaces/Portalicious/src/app/pages/project-registrations/components/custom-message-control/custom-message-control.component.html
  interfaces/Portalicious/src/app/pages/project-registrations/components/export-registrations/export-registrations.component.html
  interfaces/Portalicious/src/app/pages/project-registrations/components/import-registrations/import-registrations.component.html
  interfaces/Portalicious/src/app/pages/project-registrations/components/import-registrations/import-registrations.component.ts
  interfaces/Portalicious/src/app/pages/project-registrations/project-registrations.page.html
  interfaces/Portalicious/src/app/pages/projects-overview/projects-overview.page.html
  interfaces/Portalicious/src/app/pages/projects-overview/projects-overview.page.ts
  interfaces/Portalicious/src/app/pages/snake/game/snake.component.html
  interfaces/Portalicious/src/locale/messages.xlf
  interfaces/Portalicious/src/styles.scss
Labels: enhancement

#6613 fix: Read ALL CA-certificates from App Service containter for DB-connection
  .github/actions/build-service/action.yml
  .github/workflows/deploy_client-benin_service.yml
  .github/workflows/deploy_client-demo_service.yml
  .github/workflows/deploy_client-drc_service.yml
  .github/workflows/deploy_client-eswatini_service.yml
  .github/workflows/deploy_client-ethiopia-staging_service.yml
  .github/workflows/deploy_client-ethiopia_service.yml
  .github/workflows/deploy_client-greece_service.yml
  .github/workflows/deploy_client-helpachild_service.yml
  .github/workflows/deploy_client-ivorycoast_service.yml
  .github/workflows/deploy_client-jrethiopia_service.yml
  .github/workflows/deploy_client-krcs_service.yml
  .github/workflows/deploy_client-nigeria_service.yml
  .github/workflows/deploy_client-nlrc_service.yml
  .github/workflows/deploy_client-slovakia_service.yml
  .github/workflows/deploy_client-somalia_service.yml
  .github/workflows/deploy_client-southafrica_service.yml
  .github/workflows/deploy_client-sudan_service.yml
  .github/workflows/deploy_client-togo_service.yml
  .github/workflows/deploy_client-training_service.yml
  .github/workflows/deploy_client-zambia_service.yml
  .github/workflows/deploy_staging_service.yml
  .github/workflows/deploy_test_service.yml
  services/.env.example
  services/121-service/.gitignore
  services/121-service/cert/DigiCertGlobalRootCA.crt.pem.example
  services/121-service/src/ormconfig.ts
Labels: dependencies, ignore-for-release

#6624 ops: Increase timeout of Health-check for DB
  services/121-service/src/health/health.controller.ts
Labels: dependencies, ignore-for-release, chore

#6607 Show nothing if debit card is empty
  interfaces/Portalicious/src/app/pages/project-registration-debit-cards/project-registration-debit-cards.page.html
Labels: bugfix

#6601 feat: ignore duplicates
  interfaces/Portalicious/src/app/components/registration-page-layout/components/ignore-duplicates-dialog/ignore-duplication-dialog.component.html
  interfaces/Portalicious/src/app/components/registration-page-layout/components/ignore-duplicates-dialog/ignore-duplication-dialog.component.ts
  interfaces/Portalicious/src/app/components/registration-page-layout/registration-page-layout.component.html
  interfaces/Portalicious/src/app/components/registration-page-layout/registration-page-layout.component.ts
  interfaces/Portalicious/src/app/domains/registration/registration.api.service.ts
  interfaces/Portalicious/src/locale/messages.xlf
  services/121-service/src/registration/repositories/registration-scoped.repository.ts
Labels: enhancement

#6629 Fix correct status change
  services/121-service/src/registration/registrations.service.ts
Labels: bugfix

#6630 feat: change position of fail reason in activity overview
  .vscode/settings.json
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/activity-log-expanded-row/activity-log-expanded-row.component.ts
Labels: enhancement

#6635 chore: add design review to PR description
  docs/pull_request_template.md
Labels: chore

#6611 Add e2e test for declining completed registration
  e2e/portalicious/components/TableComponent.ts
  e2e/portalicious/pages/BasePage.ts
  e2e/portalicious/pages/RegistrationsPage.ts
  e2e/portalicious/tests/ChangeRegistrationStatus/MovePasFromCompletedToDeclined.spec.ts
  e2e/portalicious/tests/ChangeRegistrationStatus/MovePasFromCompletedToIncluded.spec.ts
  e2e/portalicious/tests/ChangeRegistrationStatus/MovePasFromDeclinedToIncluded.spec.ts
  e2e/portalicious/tests/ChangeRegistrationStatus/MovePasFromIncludedToCompleted.spec.ts
  e2e/portalicious/tests/ChangeRegistrationStatus/MovePasFromIncludedToDeclined.spec.ts
  e2e/portalicious/tests/ChangeRegistrationStatus/MovePasFromIncludedToPaused.spec.ts
  e2e/portalicious/tests/ChangeRegistrationStatus/MovePasFromRegisteredToValidated.spec.ts
  services/121-service/src/registration/registrations.service.ts
  services/121-service/test/helpers/registration.helper.ts
  services/121-service/test/registrations/pagination/pagination-data.ts
Labels: chore

#6623 Fix: remove image codes after a day instead of immidiately
  services/.env.example
  services/121-service/src/cronjob/cronjob.service.ts
  services/121-service/src/payments/fsp-integration/intersolve-voucher/dto/remove-deprecated-image-codes-dto.ts
  services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.controller.ts
  services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.service.ts
  services/121-service/src/payments/imagecode/image-code.service.ts
  services/121-service/src/shared/services/custom-http.service.ts
  services/121-service/swagger.json
  services/121-service/test/helpers/program.helper.ts
  services/121-service/test/voucher/delete-deprecated-vouchers.test.ts
Labels: bugfix

#6634 [Boyscout] Align configs for sub-packages/tools (+Sort alphabetically for easier diffs)
  .vscode/extensions.json
  interfaces/Portal/.vscode/settings.json
  interfaces/Portalicious/.vscode/settings.json
  services/121-service/.vscode/settings.json
  services/mock-service/.vscode/settings.json
Labels: chore

#6627 status changes - refactor and add unit tests
  services/121-service/src/registration/helpers/status-change.helper.spec.ts
  services/121-service/src/registration/helpers/status-change.helper.ts
  services/121-service/src/registration/registrations.service.ts
  services/121-service/src/registration/services/registrations-bulk.service.ts
Labels: bugfix

#6602 Allow non required boolean values to be empty
  e2e/portalicious/tests/ChangeRegistrationStatus/MovePasFromCompletedToIncluded.spec.ts
  services/121-service/src/registration/services/registrations-import.service.ts
  services/121-service/src/registration/validators/registrations-input.validator.helper.spec.ts
  services/121-service/src/registration/validators/registrations-input.validator.helper.ts
Labels: bugfix

#6626 Test.e2e view debit cards
  e2e/portalicious/components/ConfirmationDialogComponent.ts
  e2e/portalicious/pages/RegistrationDebitCardPage.ts
  e2e/portalicious/tests/DebitCards/ManageDebitCards.spec.ts
  interfaces/Portalicious/src/app/components/registration-page-layout/registration-page-layout.component.html
  interfaces/Portalicious/src/app/pages/project-registration-debit-cards/project-registration-debit-cards.page.html
Labels: chore

#6641 fix: Include Portalicious build-steps in Deploy All workflows
  .github/workflows/deploy_client-drc_all.yml
  .github/workflows/deploy_client-greece_all.yml
  .github/workflows/deploy_client-zambia_all.yml
Labels: bugfix, ignore-for-release, chore

#6639 fix: Combine build-steps, so they share ENV-variables
  .github/actions/build-interface/action.yml
Labels: bugfix, Translations

#6643 chore: Remove unused dependencies of unused code
  .github/dependabot.yml
  services/121-service/package-lock.json
  services/121-service/package.json
  services/mock-service/package-lock.json
  services/mock-service/package.json
Labels: dependencies, chore

#6638 chore: check for dead code in portalicious with knip
  .github/workflows/test_interface_portalicious.yml
  interfaces/Portalicious/.knip.json
  interfaces/Portalicious/package-lock.json
  interfaces/Portalicious/package.json
  interfaces/Portalicious/src/app/domains/financial-service-provider/financial-service-provider.api.service.ts
  interfaces/Portalicious/src/app/domains/financial-service-provider/financial-service-provider.model.ts
  interfaces/Portalicious/src/app/domains/project/project.api.service.ts
  interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts
  interfaces/Portalicious/src/app/services/download.service.ts
  interfaces/Portalicious/src/app/services/registrations-table-column.service.ts
  interfaces/Portalicious/src/app/services/rtl-helper.service.ts
  interfaces/Portalicious/src/app/utils/dto-type.ts
  interfaces/Portalicious/src/app/utils/local-storage.ts
  interfaces/Portalicious/src/app/utils/type-helpers.ts
Labels: chore

#6658 fix: Only handle in numbers when using the currencyPipe
  interfaces/Portalicious/src/app/pages/project-registration-debit-cards/project-registration-debit-cards.page.ts
Labels: bugfix

#6659 refactor: Stricter checks for "Currency" data-list-item data-model
  interfaces/Portalicious/src/app/components/data-list/data-list.component.ts
  interfaces/Portalicious/src/app/pages/project-registration-debit-cards/project-registration-debit-cards.page.html
Labels: chore

#6637 Map tests with test ids
  e2e/portalicious/components/TableComponent.ts
  e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusCompleted.spec.ts
  e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusDeclined.spec.ts
  e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusIncluded.spec.ts
  e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusPaused.spec.ts
  e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusRegistered.spec.ts
  e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusValidated.spec.ts
  e2e/portalicious/tests/ChangeRegistrationStatus/MovePasFromCompletedToDeclined.spec.ts
  e2e/portalicious/tests/ChangeRegistrationStatus/MovePasFromCompletedToIncluded.spec.ts
  e2e/portalicious/tests/ChangeRegistrationStatus/MovePasFromDeclinedToIncluded.spec.ts
  e2e/portalicious/tests/ChangeRegistrationStatus/MovePasFromIncludedToDeclined.spec.ts
  e2e/portalicious/tests/ChangeRegistrationStatus/MovePasFromIncludedToPaused.spec.ts
  e2e/portalicious/tests/ChangeRegistrationStatus/MovePasFromRegisteredToValidated.spec.ts
  e2e/portalicious/tests/ProfilePageActivityLog/ExpandRowsOfActivityOverview.spec.ts
  e2e/portalicious/tests/ProfilePageActivityLog/FilterActivityOverviewTable.spec.ts
  e2e/portalicious/tests/RegistrationPage/InitiateActions.spec.ts
  e2e/portalicious/tests/RegistrationPage/ViewAvailableActions.spec.ts
  e2e/portalicious/tests/ViewPayment/ValidateViewPaymentsTable.spec.ts
  interfaces/Portalicious/src/app/components/query-table/query-table.component.html
Labels: chore

#6661 chore: cleanup console log
  k6/tests/findDuplicates100kRegistrations.js
Labels: chore

#6660 fix: Reduce downloads of translations (in E2E-test runs)
  .github/workflows/test_e2e_portalicious.yml
Labels: ignore-for-release, chore, Translations

#6663 test: Add (baseline) checks for downloaded translations in build
  interfaces/Portalicious/_build-download-translations.mjs
  interfaces/Portalicious/_translations.utils.mjs
  interfaces/Portalicious/_verify-build.mjs
  interfaces/Portalicious/package.json
  interfaces/Portalicious/src/app/components/language-switcher/language-switcher.component.html
  interfaces/Portalicious/src/locale/messages.xlf
Labels: enhancement, chore, Translations

#6667 Clearer error in our logs
  services/121-service/src/exchange-rates/exchange-rates.api.service.ts
Labels: chore

#6668 chore: add comments
  .github/workflows/test_k6.yml
  .github/workflows/test_k6_cronjob.yml
Labels: chore

#6640 Refactor initiate WhatsApp convo with ContentSid
  e2e/tests/121-Portal/MakeNewPayment/PV/MakeSuccessfulPaymentPV.spec.ts
  e2e/tests/121-Portal/ViewPaProfilePage/WrongLanguagesInTemplatedMessagesBug.spec.ts
  interfaces/Portal/src/app/models/message.model.ts
  services/121-service/src/migration/1701426130489-CreateAndUpdateMessageTemplates.ts
  services/121-service/src/migration/1742574202000-message-template-content-sid.ts
  services/121-service/src/notifications/message-incoming/message-incoming.service.ts
  services/121-service/src/notifications/message-job.dto.ts
  services/121-service/src/notifications/message-queues/message-queues.service.ts
  services/121-service/src/notifications/message-template/const/content-sid-message-types.const.ts
  services/121-service/src/notifications/message-template/dto/message-template.dto.ts
  services/121-service/src/notifications/message-template/message-template.entity.ts
  services/121-service/src/notifications/message-template/message-template.service.ts
  services/121-service/src/notifications/message.service.spec.ts
  services/121-service/src/notifications/message.service.ts
  services/121-service/src/notifications/whatsapp/whatsapp.service.ts
  services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.service.ts
  services/121-service/src/payments/fsp-integration/intersolve-voucher/services/intersolve-voucher-cron.service.ts
  services/121-service/src/payments/transactions/transactions.service.ts
  services/121-service/src/scripts/seed-configuration.const.ts
  services/121-service/src/scripts/seed-configuration.dto.ts
  services/121-service/src/scripts/seed-helper.ts
  services/121-service/src/seed-data/message-template/interfaces/seed-message-template-config.interface.ts
  services/121-service/src/seed-data/message-template/message-template-generic.const.ts
  services/121-service/src/seed-data/message-template/message-template-generic.json
  services/121-service/src/seed-data/message-template/message-template-nlrc-ocw.const.ts
  services/121-service/src/seed-data/message-template/message-template-nlrc-ocw.json
  services/121-service/src/seed-data/message-template/message-template-nlrc-pv.const.ts
  services/121-service/src/seed-data/message-template/message-template-nlrc-pv.json
  services/121-service/src/transaction-job-processors/transaction-job-processors.service.ts
  services/121-service/test/helpers/assert.helper.ts
  services/121-service/test/helpers/program.helper.ts
  services/121-service/test/payment/do-payment-fsp-voucher.test.ts
  services/121-service/test/program/message-template.test.ts
  services/121-service/test/registrations/pagination/send-message.test.ts
  services/121-service/test/visa-card/block-visa-card.test.ts
  services/121-service/test/visa-card/issue-new-card.test.ts
  services/121-service/test/voucher/delete-deprecated-vouchers.test.ts
  services/mock-service/src/twilio/content-sid-message-mock-map.const.ts
  services/mock-service/src/twilio/twilio.controller.ts
  services/mock-service/src/twilio/twilio.dto.ts
  services/mock-service/src/twilio/twilio.service.ts
Labels: enhancement

#6669 fix: change translation string
  interfaces/Portalicious/_verify-build.mjs
Labels: bugfix, chore

#6674 Body by content sid instead of message sid
  services/121-service/src/notifications/whatsapp/whatsapp.service.ts
  services/mock-service/src/twilio/twilio.controller.ts
  services/mock-service/src/twilio/twilio.service.ts
Labels: bugfix
