Repository global-121/121-platform, pull requests merged in 2025-01, with the labels that each got.

#6349 portalicious: add preview URL to PR description
  .github/workflows/deploy_test_portalicious.yml
  docs/pull_request_template.md
Labels: portalicious

#6331 Api tests for update contact info
  services/121-service/test/visa-card/contact-information-visa-card.test.ts
  services/mock-service/src/fsp-integration/intersolve-visa/intersolve-visa.mock.controller.ts
  services/mock-service/src/fsp-integration/intersolve-visa/intersolve-visa.mock.service.ts
Labels: chore

#6350 portalicious: fix PR description job
  .github/workflows/deploy_test_portalicious.yml
Labels: portalicious

#6330 portalicious: payment and registration page review
  .vscode/settings.json
  e2e/portalicious/pages/RegistrationsPage.ts
  interfaces/Portalicious/src/app/components/colored-chip/colored-chip.helper.ts
  interfaces/Portalicious/src/app/components/page-layout/page-layout.component.html
  interfaces/Portalicious/src/app/components/query-table/query-table.component.html
  interfaces/Portalicious/src/app/components/query-table/query-table.component.ts
  interfaces/Portalicious/src/app/components/registration-page-layout/components/add-note-form/add-note-form.component.html
  interfaces/Portalicious/src/app/components/registration-page-layout/components/add-note-form/add-note-form.component.ts
  interfaces/Portalicious/src/app/components/registration-page-layout/components/registration-menu/registration-menu.component.ts
  interfaces/Portalicious/src/app/components/registration-page-layout/registration-page-layout.component.html
  interfaces/Portalicious/src/app/components/registration-page-layout/registration-page-layout.component.ts
  interfaces/Portalicious/src/app/components/registrations-table/registrations-table.component.html
  interfaces/Portalicious/src/app/components/registrations-table/registrations-table.component.ts
  interfaces/Portalicious/src/app/domains/project/project.api.service.ts
  interfaces/Portalicious/src/app/domains/registration/registration.model.ts
  interfaces/Portalicious/src/app/pages/project-payment/components/project-payment-chart/project-payment-chart.component.html
  interfaces/Portalicious/src/app/pages/project-payment/components/project-payment-chart/project-payment-chart.component.ts
  interfaces/Portalicious/src/app/pages/project-payment/components/retry-transfers-dialog/retry-transfers-dialog.component.ts
  interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.html
  interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts
  interfaces/Portalicious/src/app/pages/project-payments/components/payment-summary-card/payment-summary-card.component.html
  interfaces/Portalicious/src/app/pages/project-payments/components/payment-summary-card/payment-summary-card.component.ts
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/activity-log-expanded-row/activity-log-expanded-row.component.ts
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/table-cell-overview.component.ts
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/project-registration-activity-log.page.html
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/project-registration-activity-log.page.ts
  interfaces/Portalicious/src/app/pages/project-registration-personal-information/project-registration-personal-information.page.ts
  interfaces/Portalicious/src/app/pages/project-registrations/project-registrations.page.ts
  interfaces/Portalicious/src/app/pages/projects-overview/components/project-summary-card/project-summary-card.component.ts
  interfaces/Portalicious/src/app/services/auth.service.ts
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
  interfaces/Portalicious/src/styles.scss
  services/121-service/src/registration/dto/mapped-paginated-registration.dto.ts
Labels: portalicious

#6353 fix: update balanceUsed on getVoucherBalance AB#32465
  services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.service.ts
Labels: chore

#6336 Chore.throw error in mock
  services/mock-service/src/fsp-integration/intersolve-visa/intersolve-visa.mock.service.ts
Labels: chore

#6339 portalicious: personal information attributes service
  interfaces/Portalicious/src/app/components/data-list/data-list.component.html
  interfaces/Portalicious/src/app/components/data-list/data-list.component.ts
  interfaces/Portalicious/src/app/domains/project/project-attribute.helpers.ts
  interfaces/Portalicious/src/app/pages/project-monitoring/project-monitoring.page.ts
  interfaces/Portalicious/src/app/pages/project-payments/components/create-payment/create-payment.component.ts
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/activity-log-expanded-row/activity-log-expanded-row.component.ts
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/table-cell-overview.component.ts
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/project-registration-activity-log.page.ts
  interfaces/Portalicious/src/app/pages/project-registration-personal-information/project-registration-personal-information.page.html
  interfaces/Portalicious/src/app/pages/project-registration-personal-information/project-registration-personal-information.page.ts
  interfaces/Portalicious/src/app/services/registration-attribute.service.ts
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
Labels: portalicious

#6340 portalicious: edit personal information
  interfaces/Portalicious/src/app/app.routes.ts
  interfaces/Portalicious/src/app/components/form-field-wrapper/form-field-wrapper.component.html
  interfaces/Portalicious/src/app/components/form-field-wrapper/form-field-wrapper.component.ts
  interfaces/Portalicious/src/app/domains/project/project-attribute.helpers.ts
  interfaces/Portalicious/src/app/domains/registration/registration.api.service.ts
  interfaces/Portalicious/src/app/guards/pending-changes.guard.ts
  interfaces/Portalicious/src/app/pages/login/components/cookie-banner/cookie-banner.component.ts
  interfaces/Portalicious/src/app/pages/project-registration-personal-information/components/edit-personal-information/edit-personal-information.component.html
  interfaces/Portalicious/src/app/pages/project-registration-personal-information/components/edit-personal-information/edit-personal-information.component.ts
  interfaces/Portalicious/src/app/pages/project-registration-personal-information/project-registration-personal-information.page.html
  interfaces/Portalicious/src/app/pages/project-registration-personal-information/project-registration-personal-information.page.ts
  interfaces/Portalicious/src/app/pipes/translatable-string.pipe.ts
  interfaces/Portalicious/src/app/services/registration-attribute.service.ts
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
  services/121-service/src/registration/dto/update-registration.dto.ts
Labels: portalicious

#6361 chore(deps): Align Azure MSAL package versions
  .github/dependabot.yml
  interfaces/Portal/package-lock.json
  interfaces/Portal/package.json
  interfaces/Portalicious/package-lock.json
  interfaces/Portalicious/package.json
Labels: dependencies, chore

#6369 ci: Prevent failing workflow runs of Dependabot-PRs
  .github/workflows/deploy_test_portalicious.yml
Labels: dependencies, ignore-for-release

#6370 allow nullable for non required dropdown fields
  interfaces/Portalicious/src/app/pages/project-registration-personal-information/components/edit-personal-information/edit-personal-information.component.html
Labels: portalicious

#6372 chore: tanstack + eslint upgrade AB#32202
  interfaces/Portalicious/package-lock.json
  interfaces/Portalicious/package.json
  interfaces/Portalicious/src/app/domains/domain-api.service.ts
  interfaces/Portalicious/src/app/guards/found-resource.guard.ts
  interfaces/Portalicious/src/app/pages/project-payment/components/import-reconciliation-data/import-reconciliation-data.component.ts
  interfaces/Portalicious/src/app/pages/project-registration-debit-cards/project-registration-debit-cards.page.ts
  interfaces/Portalicious/src/app/pages/project-registrations/components/import-registrations/import-registrations.component.ts
  interfaces/Portalicious/src/app/services/auth/strategies/msal-auth/msal-auth.strategy.ts
  interfaces/Portalicious/src/app/services/export.service.ts
  interfaces/Portalicious/src/app/services/messaging.service.ts
  interfaces/Portalicious/src/app/services/registration-attribute.service.ts
Labels: chore

#6357 portalicious: redline integration
  interfaces/Portalicious/eslint.config.js
  interfaces/Portalicious/src/app/app.routes.ts
  interfaces/Portalicious/src/app/components/page-layout/components/registration-lookup-menu/registration-lookup-menu.component.html
  interfaces/Portalicious/src/app/components/page-layout/components/registration-lookup-menu/registration-lookup-menu.component.ts
  interfaces/Portalicious/src/app/components/page-layout/page-layout.component.html
  interfaces/Portalicious/src/app/components/page-layout/page-layout.component.ts
  interfaces/Portalicious/src/app/components/registration-page-layout/registration-page-layout.component.html
  interfaces/Portalicious/src/app/components/registration-page-layout/registration-page-layout.component.ts
  interfaces/Portalicious/src/app/components/tabs-menu/tabs-menu.component.html
  interfaces/Portalicious/src/app/domains/project/project.api.service.ts
  interfaces/Portalicious/src/app/domains/registration/registration.api.service.ts
  interfaces/Portalicious/src/app/pages/registration-lookup/registration-lookup.page.html
  interfaces/Portalicious/src/app/pages/registration-lookup/registration-lookup.page.ts
  interfaces/Portalicious/src/app/services/registration-lookup.service.ts
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
Labels: portalicious

#6352 Add E2E test for "Table should be a filtered list"
  e2e/portalicious/components/TableComponent.ts
  e2e/portalicious/tests/ViewPayment/ValidateViewPaymentsTable.spec.ts
Labels: chore, portalicious

#6362 Generic attributes api test filtering all of them
  services/121-service/test/registrations/pagination/filter-registration.test.ts
Labels: chore

#6371 fix: Self-host fonts
  .github/workflows/deploy_staging_portalicious.yml
  .github/workflows/deploy_test_portalicious.yml
  interfaces/Portalicious/_build-deployment-configuration.mjs
  interfaces/Portalicious/angular.json
  interfaces/Portalicious/src/assets/fonts/montserrat-v29-cyrillic_cyrillic-ext_latin_latin-ext_vietnamese-100.woff2
  interfaces/Portalicious/src/assets/fonts/montserrat-v29-cyrillic_cyrillic-ext_latin_latin-ext_vietnamese-100italic.woff2
  interfaces/Portalicious/src/assets/fonts/montserrat-v29-cyrillic_cyrillic-ext_latin_latin-ext_vietnamese-200.woff2
  interfaces/Portalicious/src/assets/fonts/montserrat-v29-cyrillic_cyrillic-ext_latin_latin-ext_vietnamese-200italic.woff2
  interfaces/Portalicious/src/assets/fonts/montserrat-v29-cyrillic_cyrillic-ext_latin_latin-ext_vietnamese-300.woff2
  interfaces/Portalicious/src/assets/fonts/montserrat-v29-cyrillic_cyrillic-ext_latin_latin-ext_vietnamese-300italic.woff2
  interfaces/Portalicious/src/assets/fonts/montserrat-v29-cyrillic_cyrillic-ext_latin_latin-ext_vietnamese-500.woff2
  interfaces/Portalicious/src/assets/fonts/montserrat-v29-cyrillic_cyrillic-ext_latin_latin-ext_vietnamese-500italic.woff2
  interfaces/Portalicious/src/assets/fonts/montserrat-v29-cyrillic_cyrillic-ext_latin_latin-ext_vietnamese-600.woff2
  interfaces/Portalicious/src/assets/fonts/montserrat-v29-cyrillic_cyrillic-ext_latin_latin-ext_vietnamese-600italic.woff2
  interfaces/Portalicious/src/assets/fonts/montserrat-v29-cyrillic_cyrillic-ext_latin_latin-ext_vietnamese-700.woff2
  interfaces/Portalicious/src/assets/fonts/montserrat-v29-cyrillic_cyrillic-ext_latin_latin-ext_vietnamese-700italic.woff2
  interfaces/Portalicious/src/assets/fonts/montserrat-v29-cyrillic_cyrillic-ext_latin_latin-ext_vietnamese-800.woff2
  interfaces/Portalicious/src/assets/fonts/montserrat-v29-cyrillic_cyrillic-ext_latin_latin-ext_vietnamese-800italic.woff2
  interfaces/Portalicious/src/assets/fonts/montserrat-v29-cyrillic_cyrillic-ext_latin_latin-ext_vietnamese-900.woff2
  interfaces/Portalicious/src/assets/fonts/montserrat-v29-cyrillic_cyrillic-ext_latin_latin-ext_vietnamese-900italic.woff2
  interfaces/Portalicious/src/assets/fonts/montserrat-v29-cyrillic_cyrillic-ext_latin_latin-ext_vietnamese-italic.woff2
  interfaces/Portalicious/src/assets/fonts/montserrat-v29-cyrillic_cyrillic-ext_latin_latin-ext_vietnamese-regular.woff2
  interfaces/Portalicious/src/assets/fonts/open-sans-v40-cyrillic_cyrillic-ext_greek_greek-ext_hebrew_latin_latin-ext_math_symbols_vietnamese-300.woff2
  interfaces/Portalicious/src/assets/fonts/open-sans-v40-cyrillic_cyrillic-ext_greek_greek-ext_hebrew_latin_latin-ext_math_symbols_vietnamese-300italic.woff2
  interfaces/Portalicious/src/assets/fonts/open-sans-v40-cyrillic_cyrillic-ext_greek_greek-ext_hebrew_latin_latin-ext_math_symbols_vietnamese-500.woff2
  interfaces/Portalicious/src/assets/fonts/open-sans-v40-cyrillic_cyrillic-ext_greek_greek-ext_hebrew_latin_latin-ext_math_symbols_vietnamese-500italic.woff2
  interfaces/Portalicious/src/assets/fonts/open-sans-v40-cyrillic_cyrillic-ext_greek_greek-ext_hebrew_latin_latin-ext_math_symbols_vietnamese-600.woff2
  interfaces/Portalicious/src/assets/fonts/open-sans-v40-cyrillic_cyrillic-ext_greek_greek-ext_hebrew_latin_latin-ext_math_symbols_vietnamese-600italic.woff2
  interfaces/Portalicious/src/assets/fonts/open-sans-v40-cyrillic_cyrillic-ext_greek_greek-ext_hebrew_latin_latin-ext_math_symbols_vietnamese-700.woff2
  interfaces/Portalicious/src/assets/fonts/open-sans-v40-cyrillic_cyrillic-ext_greek_greek-ext_hebrew_latin_latin-ext_math_symbols_vietnamese-700italic.woff2
  interfaces/Portalicious/src/assets/fonts/open-sans-v40-cyrillic_cyrillic-ext_greek_greek-ext_hebrew_latin_latin-ext_math_symbols_vietnamese-800.woff2
  interfaces/Portalicious/src/assets/fonts/open-sans-v40-cyrillic_cyrillic-ext_greek_greek-ext_hebrew_latin_latin-ext_math_symbols_vietnamese-800italic.woff2
  interfaces/Portalicious/src/assets/fonts/open-sans-v40-cyrillic_cyrillic-ext_greek_greek-ext_hebrew_latin_latin-ext_math_symbols_vietnamese-italic.woff2
  interfaces/Portalicious/src/assets/fonts/open-sans-v40-cyrillic_cyrillic-ext_greek_greek-ext_hebrew_latin_latin-ext_math_symbols_vietnamese-regular.woff2
  interfaces/Portalicious/src/fonts.css
  interfaces/Portalicious/src/index.html
  interfaces/Portalicious/tailwind.config.ts
Labels: portalicious

#6376 portalicious: fix tailwind colors
  interfaces/Portalicious/tailwind.config.ts
Labels: portalicious

#6358 refactor: get balance via fspconfigid of registration AB#32518
  services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.service.ts
  services/121-service/src/program-financial-service-provider-configurations/program-financial-service-provider-configurations.repository.ts
  services/121-service/test/helpers/intersolve-voucher.helper.ts
  services/121-service/test/payment/do-payment-fsp-voucher.test.ts
  services/121-service/test/voucher/get-balance.test.ts
Labels: chore

#6303 test: unit test PoC for isTokenValid
  .github/workflows/test_service_api.yml
  package-lock.json
  package.json
  services/121-service/README.md
  services/121-service/package.json
  services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.api.service.ts
  services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.module.ts
  services/121-service/src/payments/fsp-integration/safaricom/safaricom.module.ts
  services/121-service/src/payments/fsp-integration/safaricom/safaricom.service.spec.ts
  services/121-service/src/payments/fsp-integration/safaricom/safaricom.service.ts
  services/121-service/src/payments/fsp-integration/safaricom/services/safaricom.api.helper.service.spec.ts
  services/121-service/src/payments/fsp-integration/safaricom/services/safaricom.api.helper.service.ts
  services/121-service/src/payments/fsp-integration/safaricom/services/safaricom.api.service.spec.ts
  services/121-service/src/payments/fsp-integration/safaricom/services/safaricom.api.service.ts
  services/121-service/src/program-financial-service-provider-configurations/program-financial-service-provider-configurations.service.spec.ts
  services/121-service/src/registration/modules/registration-data/registration-data.service.ts
  services/121-service/src/utils/token/token-validation.service.spec.ts
  services/121-service/src/utils/token/token-validation.service.ts
Labels: chore

#6356 K6 floating point test visa
  k6/models/initalize-payment.js
  k6/models/payments.js
  k6/tests/payment100kRegistrationOCW.js
  k6/tests/payment100kRegistrationSafaricom.js
  k6/tests/performanceDuringPayment.js
  k6/tests/retryFailedJobsOnStartupDuringQueueProcessing.js
  k6/tests/statusChangePaymentInLargeProgram.js
  services/121-service/src/queues-registry/queues-registry.service.ts
Labels: chore

#6380 Max payments fix
  services/121-service/src/registration/interfaces/validate-registration-error-object.interface.ts
  services/121-service/src/registration/validators/registrations-input-validator.spec.ts
  services/121-service/src/registration/validators/registrations-input-validator.ts
Labels: chore

#6378 remove demo program
  services/121-service/src/scripts/seed-configuration.const.ts
  services/121-service/src/seed-data/program/program-demo.json
  services/121-service/src/seed-data/program/program-validation.json
  services/121-service/test/payment/do-payment-fsp-excel.test.ts
  services/121-service/test/registrations/import-registration.test.ts
  services/121-service/test/registrations/pagination/pagination-data.ts
Labels: chore

#6384 return no access on non nummeric programIds
  services/121-service/src/user/user.service.ts
Labels: bugfix

#6385 feat: Always show "no results" as fallback-content in Lookup-page
  interfaces/Portalicious/src/app/components/page-layout/components/registration-lookup-menu/registration-lookup-menu.component.html
  interfaces/Portalicious/src/app/components/page-layout/components/registration-lookup-menu/registration-lookup-menu.component.ts
  interfaces/Portalicious/src/app/pages/registration-lookup/registration-lookup.page.html
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
Labels: portalicious

#6388 feat: Allow control of pop-ups from iframes in Twilio Flex in config-builder
  interfaces/Portalicious/_build-deployment-configuration.mjs
  interfaces/Portalicious/_test-deployment-configuration.mjs
  interfaces/Portalicious/_verify-deployment-configuration.mjs
Labels: bugfix, portalicious

#6395 Chore.exhange rates api test
  services/.env.example
  services/121-service/module-dependencies.md
  services/121-service/src/app.module.ts
  services/121-service/src/cronjob/cronjob.module.ts
  services/121-service/src/cronjob/cronjob.service.ts
  services/121-service/src/exchange-rates/exchange-rates.api.service.ts
  services/121-service/src/exchange-rates/exchange-rates.controller.ts
  services/121-service/src/exchange-rates/exchange-rates.service.spec.ts
  services/121-service/src/exchange-rates/exchange-rates.service.ts
  services/121-service/swagger.json
  services/121-service/test/exchange-rates/exchange-rates.test.ts
  services/121-service/test/helpers/organization.helper.ts
  services/mock-service/src/app.module.ts
  services/mock-service/src/exchange-rates/exchange-rates-mock.controller.ts
  services/mock-service/src/exchange-rates/exchange-rates-mock.module.ts
  services/mock-service/src/exchange-rates/exchange-rates-mock.service.ts
Labels: chore

#6389 Fix.k6 error message
  .github/workflows/test_k6_cronjob.yml
  k6/run-all-tests.sh
Labels: chore

#6394 fix: Allow pop-ups more broadly
  interfaces/Portalicious/_build-deployment-configuration.mjs
  interfaces/Portalicious/_test-deployment-configuration.mjs
  interfaces/Portalicious/_verify-deployment-configuration.mjs
Labels: ignore-for-release

#6402 chore: Remove unused instances
  .github/workflows/deploy_client-krcs-training_all.yml
  .github/workflows/deploy_client-krcs-training_portal.yml
  .github/workflows/deploy_client-krcs-training_service.yml
  .github/workflows/deploy_client-southsudan_all.yml
  .github/workflows/deploy_client-southsudan_portal.yml
  .github/workflows/deploy_client-southsudan_service.yml
  .github/workflows/deploy_client-zimbabwe_all.yml
  .github/workflows/deploy_client-zimbabwe_portal.yml
  .github/workflows/deploy_client-zimbabwe_service.yml
Labels: ignore-for-release

#6399 Portalicious: Easter egg Snake
  interfaces/Portalicious/src/app/app.routes.ts
  interfaces/Portalicious/src/app/pages/snake/game/snake.component.html
  interfaces/Portalicious/src/app/pages/snake/game/snake.component.ts
  interfaces/Portalicious/src/app/pages/snake/snake.page.html
  interfaces/Portalicious/src/app/pages/snake/snake.page.ts
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
Labels: portalicious

#6403 ci: Add deployment-status update permissions to all "all"-workflows
  .github/workflows/deploy_client-demo_portalicious.yml
  .github/workflows/deploy_client-drc_all.yml
  .github/workflows/deploy_client-greece_all.yml
  .github/workflows/deploy_client-helpachild_all.yml
  .github/workflows/deploy_client-jrethiopia_all.yml
  .github/workflows/deploy_client-krcs_all.yml
  .github/workflows/deploy_client-nlrc_all.yml
  .github/workflows/deploy_client-slovakia_all.yml
  .github/workflows/deploy_client-southafrica_all.yml
  .github/workflows/deploy_client-training_all.yml
  .github/workflows/deploy_client-zambia_all.yml
Labels: ignore-for-release, chore

#6381 portalicious: filters from backend
  interfaces/Portalicious/src/app/components/registrations-table/registrations-table.component.ts
  interfaces/Portalicious/src/app/domains/project/project.api.service.ts
  interfaces/Portalicious/src/app/services/registrations-table-column.service.ts
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
  services/121-service/src/programs/dto/found-program.dto.ts
Labels: portalicious

#6404 fix: Make sure to test for automated-popup-opening + set proper popup…
  interfaces/Portalicious/_build-deployment-configuration.mjs
  interfaces/Portalicious/_test-deployment-configuration.mjs
  interfaces/Portalicious/_verify-deployment-configuration.mjs
  interfaces/Portalicious/src/app/services/auth/strategies/msal-auth/msal-auth.login.component.ts
  interfaces/Portalicious/src/app/utils/are-popups-blocked.ts
  interfaces/Portalicious/src/app/utils/is-pop-up-blocked.ts
Labels: portalicious

#6406 Portalicious fix: convert cents to euros
  interfaces/Portalicious/src/app/pages/project-registration-debit-cards/project-registration-debit-cards.page.ts
Labels: portalicious

#6407 Portalicious chore: update 'status' translation
  interfaces/Portalicious/src/app/components/registration-page-layout/registration-page-layout.component.ts
  interfaces/Portalicious/src/app/services/registrations-table-column.service.ts
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
Labels: portalicious

#6408 chore: swap 'Time and date' & 'Done by' columns
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/project-registration-activity-log.page.ts
Labels: portalicious

#6412 Improved translation export buttons for payments
  interfaces/Portal/src/assets/i18n/es.json
Labels: chore

#6409 feat: Add Privacy-notice page + links
  interfaces/Portalicious/src/app/app.routes.ts
  interfaces/Portalicious/src/app/components/page-layout/components/footer/footer.component.html
  interfaces/Portalicious/src/app/components/page-layout/components/footer/footer.component.ts
  interfaces/Portalicious/src/app/components/page-layout/components/header/header.component.html
  interfaces/Portalicious/src/app/components/page-layout/components/header/header.component.ts
  interfaces/Portalicious/src/app/pages/login/login.page.html
  interfaces/Portalicious/src/app/pages/login/login.page.ts
  interfaces/Portalicious/src/app/pages/privacy/privacy.page.html
  interfaces/Portalicious/src/app/pages/privacy/privacy.page.ts
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
Labels: portalicious

#6411 portalicious: open registration in new tab
  e2e/portalicious/pages/RegistrationsPage.ts
  e2e/portalicious/tests/ViewAndManagePeopleAffected/OpenRegistrationInNewTab.spec.ts
  interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts
  interfaces/Portalicious/src/app/pages/project-registrations/project-registrations.page.ts
Labels: portalicious

#6413 Nedbank cert readme.md
  services/121-service/src/payments/fsp-integration/nedbank/README.md
Labels: chore

#6417 fix: column order registration table
  interfaces/Portalicious/src/app/components/query-table/query-table.component.ts
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/project-registration-activity-log.page.ts
  interfaces/Portalicious/src/app/services/registrations-table-column.service.ts
Labels: chore, portalicious

#6418 chore: create eswatini instance
  .github/workflows/deploy_client-eswatini_all.yml
  .github/workflows/deploy_client-eswatini_portal.yml
  .github/workflows/deploy_client-eswatini_service.yml
Labels: chore

#6390 Change error checks in K6 tests
  k6/run-all-tests.sh
  k6/tests/getProgramWithManyAttributes.js
  k6/tests/import1000Registrations.js
  k6/tests/payment100kRegistrationOCW.js
  k6/tests/payment100kRegistrationSafaricom.js
  k6/tests/performanceDuringPayment.js
  k6/tests/retryFailedJobsOnStartupDuringQueueProcessing.js
  k6/tests/statusChangePaymentInLargeProgram.js
Labels: bugfix

#6405 portalicious: theming feedback
  .vscode/settings.json
  e2e/portalicious/components/TableComponent.ts
  e2e/portalicious/tests/ExportPeopleAffectedList/ExportDuplicateRegistrations.spec.ts
  e2e/portalicious/tests/ExportPeopleAffectedList/ExportHighVolumeOfRegistrations.spec.ts
  e2e/portalicious/tests/ExportPeopleAffectedList/ExportRegistrationsDataChanges.spec.ts
  e2e/portalicious/tests/ExportPeopleAffectedList/ExportRegistrationsList.spec.ts
  e2e/portalicious/tests/SendMessage/SendTemplatedMessage.spec.ts
  interfaces/Portalicious/.vscode/settings.json
  interfaces/Portalicious/eslint.config.js
  interfaces/Portalicious/src/app/app.theme.ts
  interfaces/Portalicious/src/app/components/button-menu/button-menu.component.html
  interfaces/Portalicious/src/app/components/card-summary-metrics-container/card-summary-metrics-container.component.html
  interfaces/Portalicious/src/app/components/colored-chip/colored-chip.component.ts
  interfaces/Portalicious/src/app/components/confirmation-dialog/confirmation-dialog.component.html
  interfaces/Portalicious/src/app/components/form-field-wrapper/form-field-wrapper.component.html
  interfaces/Portalicious/src/app/components/form/form-default.component.html
  interfaces/Portalicious/src/app/components/metric-container/metric-container.component.html
  interfaces/Portalicious/src/app/components/page-layout/components/header/header.component.html
  interfaces/Portalicious/src/app/components/page-layout/components/header/header.component.ts
  interfaces/Portalicious/src/app/components/page-layout/components/project-menu/project-menu.component.html
  interfaces/Portalicious/src/app/components/query-table/components/query-table-column-management/query-table-column-management.component.html
  interfaces/Portalicious/src/app/components/query-table/components/query-table-global-search/query-table-global-search.component.html
  interfaces/Portalicious/src/app/components/query-table/query-table.component.html
  interfaces/Portalicious/src/app/components/query-table/query-table.component.ts
  interfaces/Portalicious/src/app/domains/registration/registration.helper.ts
  interfaces/Portalicious/src/app/pages/login/login.page.html
  interfaces/Portalicious/src/app/pages/project-payment/components/project-payment-chart/project-payment-chart.component.ts
  interfaces/Portalicious/src/app/pages/project-payments/components/export-payments/export-payments.component.html
  interfaces/Portalicious/src/app/pages/project-payments/components/export-payments/export-payments.component.ts
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/activity-log-expanded-row/activity-log-expanded-row.component.html
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/activity-log-expanded-row/activity-log-expanded-row.component.ts
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/activity-log-voucher-dialog/activity-log-voucher-dialog.component.html
  interfaces/Portalicious/src/app/pages/project-registrations/components/custom-message-control/custom-message-control.component.html
  interfaces/Portalicious/src/app/pages/project-registrations/components/export-registrations/export-registrations.component.html
  interfaces/Portalicious/src/app/pages/project-registrations/components/export-registrations/export-registrations.component.ts
  interfaces/Portalicious/src/app/pages/project-registrations/project-registrations.page.html
  interfaces/Portalicious/src/app/pages/project-registrations/project-registrations.page.ts
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
  interfaces/Portalicious/src/styles.scss
  interfaces/Portalicious/tailwind.config.ts
Labels: portalicious

#6416 chore: update angular to fix vite alert
  interfaces/Portalicious/package-lock.json
  interfaces/Portalicious/package.json
Labels: chore, portalicious

#6306 fix: make make programFspConfigId nullable in relations AB#32262
  services/121-service/module-dependencies.md
  services/121-service/package.json
  services/121-service/src/financial-service-providers/enum/financial-service-provider-name.enum.ts
  services/121-service/src/financial-service-providers/financial-service-providers-settings.const.ts
  services/121-service/src/migration/1734524945346-MakeProgramFspConfigNullableForeignKey.ts
  services/121-service/src/payments/payments.service.ts
  services/121-service/src/payments/transactions/transaction.entity.ts
  services/121-service/src/program-financial-service-provider-configurations/entities/program-financial-service-provider-configuration.entity.ts
  services/121-service/src/program-financial-service-provider-configurations/program-financial-service-provider-configurations.module.ts
  services/121-service/src/program-financial-service-provider-configurations/program-financial-service-provider-configurations.service.spec.ts
  services/121-service/src/program-financial-service-provider-configurations/program-financial-service-provider-configurations.service.ts
  services/121-service/src/registration/registration.entity.ts
  services/121-service/swagger.json
  services/121-service/test/program/__snapshots__/manage-program-financial-service-provider-configuration.test.ts.snap
  services/121-service/test/program/manage-program-financial-service-provider-configuration.test.ts
Labels: bugfix

#6415 Chore: transfer 'overview' change in activity log
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/table-cell-overview.component.ts
Labels: chore, portalicious

#6421 Add e2e tests for graph transfer value
  e2e/portalicious/pages/PaymentsPage.ts
  e2e/portalicious/tests/Navigation/ProjectMonitoring/AllElementsOfProjectMonitoringPageDisplayCorrectData.spec.ts
  e2e/portalicious/tests/ViewPayment/GraphDisplaysCorrectPaymentAmount.spec.ts
Labels: chore, portalicious

#6422 AB#32984 Seed admin only
  services/121-service/src/scripts/enum/seed-script.enum.ts
  services/121-service/src/scripts/scripts.service.ts
  services/121-service/src/scripts/seed-configuration.const.ts
  services/121-service/src/scripts/seed-configuration.dto.ts
Labels: chore

#6431 Portalicious SSO: add logging + fix COOP setting
  interfaces/Portalicious/_build-deployment-configuration.mjs
  interfaces/Portalicious/_test-deployment-configuration.mjs
  interfaces/Portalicious/_verify-deployment-configuration.mjs
  interfaces/Portalicious/src/app/services/auth/strategies/msal-auth/msal-auth.strategy.ts
Labels: chore, portalicious

#6429 ci: Automatically re-test a PR on updating labels
  .github/workflows/test_pull_request_formatting.yml
Labels: enhancement

#6434 chore: create ivorycoast workflows
  .github/workflows/deploy_client-ivorycoast_all.yml
  .github/workflows/deploy_client-ivorycoast_portal.yml
  .github/workflows/deploy_client-ivorycoast_service.yml
Labels: enhancement

#6382 Refactor: FSP reconciliation module
  interfaces/Portal/src/app/services/programs-service-api.service.ts
  interfaces/Portalicious/src/app/domains/payment/payment.api.service.ts
  services/121-service/module-dependencies.md
  services/121-service/src/app.module.ts
  services/121-service/src/cronjob/cronjob.service.ts
  services/121-service/src/financial-service-provider-callback-job-processors/financial-service-provider-callback-job-processors.module.ts
  services/121-service/src/financial-service-providers/financial-service-providers-settings.const.ts
  services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/commercial-bank-ethiopia.controller.ts
  services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/commercial-bank-ethiopia.service.ts
  services/121-service/src/payments/fsp-integration/excel/excel.service.ts
  services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.module.ts
  services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.controller.ts
  services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.service.ts
  services/121-service/src/payments/fsp-integration/intersolve-voucher/services/intersolve-voucher-cron.service.ts
  services/121-service/src/payments/fsp-integration/safaricom/safaricom.module.ts
  services/121-service/src/payments/fsp-integration/safaricom/safaricom.service.spec.ts
  services/121-service/src/payments/fsp-integration/safaricom/safaricom.service.ts
  services/121-service/src/payments/payments.controller.ts
  services/121-service/src/payments/payments.service.ts
  services/121-service/src/payments/reconciliation/commercial-bank-ethiopia-reconciliation/commercial-bank-ethiopia-reconciliation.controller.ts
  services/121-service/src/payments/reconciliation/commercial-bank-ethiopia-reconciliation/commercial-bank-ethiopia-reconciliation.module.ts
  services/121-service/src/payments/reconciliation/commercial-bank-ethiopia-reconciliation/commercial-bank-ethiopia-reconciliation.service.ts
  services/121-service/src/payments/reconciliation/excel/excel-reconciliation.controller.ts
  services/121-service/src/payments/reconciliation/excel/excel-reconciliation.module.ts
  services/121-service/src/payments/reconciliation/excel/excel-reconciliation.service.ts
  services/121-service/src/payments/reconciliation/intersolve-visa-reconciliation/intersolve-visa-reconciliation.controller.ts
  services/121-service/src/payments/reconciliation/intersolve-visa-reconciliation/intersolve-visa-reconciliation.module.ts
  services/121-service/src/payments/reconciliation/intersolve-visa-reconciliation/intersolve-visa-reconciliation.service.ts
  services/121-service/src/payments/reconciliation/intersolve-voucher-reconciliation/intersolve-voucher-reconciliation.controller.ts
  services/121-service/src/payments/reconciliation/intersolve-voucher-reconciliation/intersolve-voucher-reconciliation.module.ts
  services/121-service/src/payments/reconciliation/intersolve-voucher-reconciliation/intersolve-voucher-reconciliation.service.ts
  services/121-service/src/payments/reconciliation/safaricom-reconciliation/dtos/safaricom-timeout-callback-job.dto.ts
  services/121-service/src/payments/reconciliation/safaricom-reconciliation/dtos/safaricom-timeout-callback.dto.ts
  services/121-service/src/payments/reconciliation/safaricom-reconciliation/dtos/safaricom-transfer-callback-job.dto.ts
  services/121-service/src/payments/reconciliation/safaricom-reconciliation/dtos/safaricom-transfer-callback.dto.ts
  services/121-service/src/payments/reconciliation/safaricom-reconciliation/processors/safaricom-timeout-callback-job.processor.ts
  services/121-service/src/payments/reconciliation/safaricom-reconciliation/processors/safaricom-transfer-callback-job.processor.ts
  services/121-service/src/payments/reconciliation/safaricom-reconciliation/safaricom-reconciliation.controller.ts
  services/121-service/src/payments/reconciliation/safaricom-reconciliation/safaricom-reconciliation.module.ts
  services/121-service/src/payments/reconciliation/safaricom-reconciliation/safaricom-reconciliation.service.spec.ts
  services/121-service/src/payments/reconciliation/safaricom-reconciliation/safaricom-reconciliation.service.ts
  services/121-service/src/payments/transactions/transactions.service.ts
  services/121-service/src/queues-registry/queues-registry.module.ts
  services/121-service/swagger.json
  services/121-service/test/helpers/program.helper.ts
  services/121-service/test/helpers/registration.helper.ts
Labels: chore

#6430 Fix allow empty string values for nonRequired dropdows
  services/121-service/src/registration/validators/registrations-input-validator.spec.ts
  services/121-service/src/registration/validators/registrations-input-validator.ts
  services/121-service/test/helpers/assert.helper.ts
  services/121-service/test/registrations/bulk-update-registration.test.ts
Labels: bugfix

#6439 121-service fix: rename endpoint & check for array
  services/121-service/src/payments/reconciliation/intersolve-voucher-reconciliation/intersolve-voucher-reconciliation.controller.ts
  services/121-service/src/payments/reconciliation/intersolve-voucher-reconciliation/intersolve-voucher-reconciliation.module.ts
  services/121-service/src/payments/reconciliation/intersolve-voucher-reconciliation/intersolve-voucher-reconciliation.service.ts
  services/121-service/swagger.json
Labels: chore

#6438 portalicious: registrations are not deselected after performing an action
  e2e/portalicious/components/TableComponent.ts
  e2e/portalicious/pages/RegistrationsPage.ts
  interfaces/Portalicious/src/app/pages/project-registrations/project-registrations.page.html
Labels: portalicious

#6443 feat: Add human-readable, generic URLs for change-password
  interfaces/Portal/staticwebapp.config.json
  interfaces/Portalicious/staticwebapp.config.base.json
  services/121-service/src/emails/templates/body.helper.ts
  services/121-service/src/emails/templates/config.enum.ts
  services/121-service/src/emails/templates/createNonSsoUserTemplate.ts
  services/121-service/src/emails/templates/createSsoUserTemplate.ts
  services/121-service/src/emails/templates/passwordResetTemplate.ts
Labels: enhancement

#6440 refactor: Set all variables via GitHub-environment variables
  .github/actions/build-interface/action.yml
  .github/workflows/deploy_client-demo_portalicious.yml
  .github/workflows/deploy_client-eswatini_portal.yml
  .github/workflows/deploy_client-ivorycoast_portal.yml
  .github/workflows/deploy_client-nlrc_portalicious.yml
  .github/workflows/deploy_client-slovakia_portal.yml
  .github/workflows/deploy_client-training_portalicious.yml
  .github/workflows/deploy_staging_portalicious.yml
  .github/workflows/deploy_test_portalicious.yml
  interfaces/README.md
Labels: chore

#6442 Misc. collection of fixes/tweaks and other things...
  .github/actions/build-service/action.yml
  .github/release.yml
  .vscode/settings.json
  services/.env.example
  services/121-service/src/config.ts
  services/121-service/src/main.ts
  services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/README.md
  services/mock-service/src/main.ts
Labels: chore

#6433 portalicious: icon buttons
  interfaces/Portalicious/src/app/components/page-layout/components/header/header.component.html
  interfaces/Portalicious/src/app/components/query-table/components/query-table-global-search/query-table-global-search.component.html
  interfaces/Portalicious/src/styles.scss
Labels: portalicious

#6437 refactor: Remove deprecated/unused CSP-directives + add tests
  interfaces/Portalicious/_build-deployment-configuration.mjs
  interfaces/Portalicious/_test-deployment-configuration.mjs
  interfaces/Portalicious/_verify-deployment-configuration.mjs
Labels: chore

#6448 portalicious: fix change status "cancel" button
  interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-contents-with-custom-message/change-status-contents-with-custom-message.component.html
  interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-submit-buttons/change-status-submit-buttons.component.html
Labels: portalicious

#6447 feat: Add a central 404-page to automatically link to the root of the new Portal on old URLs
  interfaces/Portalicious/package.json
  interfaces/Portalicious/src/404.html
  interfaces/Portalicious/staticwebapp.config.base.json
Labels: enhancement, portalicious
