Repository global-121/121-platform, pull requests merged in 2025-02, with the labels that each got.

#6446 fix: REALLY let Prettier ignore generated swagger.json file + autofix
  .prettierignore
  services/121-service/.prettierignore
  services/121-service/README.md
  services/121-service/swagger.json
Labels: ignore-for-release, chore

#6449 portalicious: fix validation on change password page
  interfaces/Portalicious/src/app/services/auth/strategies/basic-auth/basic-auth.change-password.component.html
Labels: portalicious

#6450 portalicious: rtl friendly comma separated lists
  interfaces/Portalicious/src/app/components/data-list/data-list.component.ts
  interfaces/Portalicious/src/app/pages/project-payment/components/project-payment-chart/project-payment-chart.component.ts
  interfaces/Portalicious/src/app/services/registration-attribute.service.ts
  interfaces/Portalicious/src/app/services/translatable-string.service.ts
Labels: portalicious

#6463 portalicious: add timestamp to payment page table
  interfaces/Portalicious/src/app/domains/metric/metric.model.ts
  interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts
Labels: portalicious

#6451 portalicious: default numeric attributes to zero in registrations table
  interfaces/Portalicious/src/app/services/registrations-table-column.service.ts
Labels: portalicious

#6466 Fix Portalicious: show export payment report button
  interfaces/Portalicious/src/app/domains/project/project.helper.ts
  interfaces/Portalicious/src/app/pages/project-payment/components/single-payment-export/single-payment-export.component.ts
  interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.html
Labels: chore, portalicious

#6465 portalicious: align empty table message to left
  interfaces/Portalicious/src/app/components/query-table/query-table.component.html
  interfaces/Portalicious/src/app/components/registrations-table/registrations-table.component.html
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
  interfaces/Portalicious/src/styles.scss
Labels: portalicious

#6271 Add links for e2e and Azure Tests Plan documentation.
  README.md
Labels: chore

#6441 Log reason status change 121-service
  e2e/portalicious/pages/RegistrationsPage.ts
  e2e/portalicious/tests/ExportPeopleAffectedList/ExportRegistrationsDataChanges.spec.ts
  e2e/tests/121-Portal/ViewPaProfilePage/ViewActivityFspOverview.spec.ts
  interfaces/Portal/src/app/services/programs-service-api.service.ts
  interfaces/Portalicious/src/app/domains/registration/registration.api.service.ts
  interfaces/Portalicious/src/app/domains/registration/registration.helper.ts
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/activity-log-expanded-row/activity-log-expanded-row.component.ts
  interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-dialog/change-status-dialog.component.html
  interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-dialog/change-status-dialog.component.ts
  interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-reason/change-status-reason.component.html
  interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-reason/change-status-reason.component.ts
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
  services/121-service/src/activities/activities.mapper.ts
  services/121-service/src/activities/interfaces/status-change-activity.interface.ts
  services/121-service/src/events/dto/event-log-options.dto.ts
  services/121-service/src/events/events.service.spec.ts
  services/121-service/src/events/events.service.ts
  services/121-service/src/events/interfaces/event-log-options.interface.ts
  services/121-service/src/notifications/interfaces/message-content-details.interface.ts
  services/121-service/src/payments/transactions/transactions.service.ts
  services/121-service/src/registration/dto/delete-registrations.dto.ts
  services/121-service/src/registration/dto/registration-status-patch.dto.ts
  services/121-service/src/registration/registrations.controller.ts
  services/121-service/src/registration/registrations.service.ts
  services/121-service/src/registration/services/registrations-bulk.service.ts
  services/121-service/src/registration/services/registrations-import.service.ts
  services/121-service/src/registration/validators/is-optional-if.class.validator.spec.ts
  services/121-service/src/registration/validators/is-optional-if.class.validator.ts
  services/121-service/src/scripts/scripts.controller.ts
  services/121-service/src/scripts/scripts.service.ts
  services/121-service/src/scripts/seed-init.ts
  services/121-service/src/transaction-job-processors/transaction-job-processors.service.ts
  services/121-service/test/event/filter-events.test.ts
  services/121-service/test/helpers/registration.helper.ts
  services/121-service/test/metrics/export-list.test.ts
  services/121-service/test/metrics/export-payment-report.test.ts
  services/121-service/test/payment/do-payment-commercial-bank-ethiopia.test.ts
  services/121-service/test/payment/do-payment-filter.test.ts
  services/121-service/test/payment/do-payment-fsp-excel.test.ts
  services/121-service/test/payment/do-payment-fsp-safaricom.test.ts
  services/121-service/test/payment/do-payment-fsp-visa-debit/do-payment-fsp-visa-debit-error.test.ts
  services/121-service/test/payment/do-payment-fsp-visa-debit/do-payment-fsp-visa-debit-retry.test.ts
  services/121-service/test/payment/do-payment-fsp-visa-debit/do-payment-fsp-visa-debit.success.test.ts
  services/121-service/test/payment/do-payment-fsp-voucher.test.ts
  services/121-service/test/payment/do-payment.scope.test.ts
  services/121-service/test/payment/payment-count-completed.test.ts
  services/121-service/test/program/manage-program-financial-service-provider-configuration.test.ts
  services/121-service/test/registrations/delete-registration.test.ts
  services/121-service/test/registrations/pagination/filter-registration.payment.test.ts
  services/121-service/test/registrations/pagination/filter-registration.test.ts
  services/121-service/test/registrations/pagination/sort-registration.test.ts
  services/121-service/test/registrations/pagination/update-registration-status.test.ts
  services/121-service/test/registrations/send-templated-message.test.ts
  services/121-service/test/visa-card/block-visa-card.test.ts
  services/121-service/test/visa-card/load-visa-card-details.test.ts
  services/121-service/test/voucher/get-balance.test.ts
Labels: enhancement

#6464 Events: small changes and refactor todo's
  services/121-service/src/events/events.controller.ts
  services/121-service/src/events/events.service.spec.ts
  services/121-service/src/events/events.service.ts
  services/121-service/src/events/interfaces/create-from-registration-views-options.interface.ts
  services/121-service/src/payments/transactions/transactions.service.ts
  services/121-service/src/registration/registrations.service.ts
  services/121-service/src/registration/services/registrations-bulk.service.ts
  services/121-service/src/registration/services/registrations-import.service.ts
  services/121-service/src/transaction-job-processors/transaction-job-processors.service.ts
Labels: enhancement

#6473 portalicious: easier to read import errors
  interfaces/Portalicious/src/app/components/import-file-dialog/import-file-dialog.component.html
Labels: portalicious

#6468 portalicious: fix datalabels in chart
  interfaces/Portalicious/src/app/utils/chart.ts
Labels: portalicious

#6478 Fix delete teammember from team
  services/121-service/src/user/dto/assign-aw-to-program.dto.ts
  services/121-service/src/user/user.controller.ts
  services/121-service/src/user/user.service.ts
Labels: bugfix

#6480 portalicious: design fixes
  e2e/portalicious/pages/PaymentsPage.ts
  interfaces/Portalicious/src/app/app.theme.ts
  interfaces/Portalicious/src/app/components/card-with-link/card-with-link.component.html
  interfaces/Portalicious/src/app/components/data-list/data-list.component.html
  interfaces/Portalicious/src/app/components/data-list/data-list.component.ts
  interfaces/Portalicious/src/app/components/page-layout/page-layout.component.html
  interfaces/Portalicious/src/app/components/registration-page-layout/registration-page-layout.component.html
  interfaces/Portalicious/src/app/domains/payment/payment.helpers.ts
  interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.html
  interfaces/Portalicious/src/app/pages/project-payments/components/payment-summary-card/payment-summary-card.component.html
  interfaces/Portalicious/src/app/pages/project-payments/components/payment-summary-card/payment-summary-card.component.ts
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/activity-log-expanded-row/activity-log-expanded-row.component.ts
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/table-cell-overview.component.ts
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/locale/messages.xlf
  interfaces/Portalicious/tailwind.config.ts
Labels: portalicious

#6479 Chore.dependabot sprint 148
  e2e/package-lock.json
  e2e/package.json
  interfaces/Portalicious/package-lock.json
  interfaces/Portalicious/package.json
Labels: chore

#6472 portalicious: consistent cmd/ctrl+enter
  interfaces/Portalicious/src/app/components/confirmation-dialog/confirmation-dialog.component.html
  interfaces/Portalicious/src/app/components/confirmation-dialog/confirmation-dialog.component.ts
  interfaces/Portalicious/src/app/pages/project-registration-personal-information/components/edit-personal-information/edit-personal-information.component.html
  interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-dialog/change-status-dialog.component.html
  interfaces/Portalicious/src/app/pages/project-registrations/components/send-message-dialog/send-message-dialog.component.html
Labels: portalicious

#6489 Somalia github actions
  .github/workflows/deploy_client-somalia_all.yml
  .github/workflows/deploy_client-somalia_portal.yml
  .github/workflows/deploy_client-somalia_service.yml
Labels: chore

#6488 chore: add South Africa portalicious workflow
  .github/workflows/deploy_client-southafrica_all.yml
  .github/workflows/deploy_client-southafrica_portalicious.yml
Labels: chore, portalicious

#6481 Fixed last used date visa export
  services/121-service/src/registration/repositories/registration-scoped.repository.ts
  services/121-service/test/visa-card/__snapshots__/export-report.test.ts.snap
  services/121-service/test/visa-card/export-report.test.ts
Labels: bugfix

#6471 Nest js v11!
  services/121-service/package-lock.json
  services/121-service/package.json
  services/121-service/src/strategies/azure-ad.strategy.ts
  services/121-service/src/strategies/cookie-jwt.strategy.ts
  services/mock-service/package-lock.json
  services/mock-service/package.json
Labels: chore

#6499 Revert "Nest js v11!"
  services/121-service/package-lock.json
  services/121-service/package.json
  services/121-service/src/strategies/azure-ad.strategy.ts
  services/121-service/src/strategies/cookie-jwt.strategy.ts
  services/mock-service/package-lock.json
  services/mock-service/package.json
Labels: ignore-for-release, chore

#6500 fix permission to export dupes
  services/121-service/src/metrics/metrics.service.ts
Labels: bugfix

#6482 Download latest translations from Lokalise before each build
  .github/actions/build-interface/action.yml
  .github/workflows/deploy_client-demo_all.yml
  .github/workflows/deploy_client-demo_portalicious.yml
  .github/workflows/deploy_client-eswatini_all.yml
  .github/workflows/deploy_client-eswatini_portal.yml
  .github/workflows/deploy_client-ivorycoast_all.yml
  .github/workflows/deploy_client-ivorycoast_portal.yml
  .github/workflows/deploy_client-nlrc_all.yml
  .github/workflows/deploy_client-nlrc_portalicious.yml
  .github/workflows/deploy_client-slovakia_all.yml
  .github/workflows/deploy_client-slovakia_portal.yml
  .github/workflows/deploy_client-somalia_all.yml
  .github/workflows/deploy_client-somalia_portal.yml
  .github/workflows/deploy_client-southafrica_all.yml
  .github/workflows/deploy_client-southafrica_portalicious.yml
  .github/workflows/deploy_client-training_all.yml
  .github/workflows/deploy_client-training_portalicious.yml
  .github/workflows/deploy_staging_all.yml
  .github/workflows/deploy_staging_portalicious.yml
  .github/workflows/deploy_test_all.yml
  .github/workflows/deploy_test_portal.yml
  .github/workflows/deploy_test_portalicious.yml
  .github/workflows/test_e2e_portalicious.yml
  interfaces/Portalicious/.env.example
  interfaces/Portalicious/.gitignore
  interfaces/Portalicious/README.md
  interfaces/Portalicious/_build-deployment-configuration.mjs
  interfaces/Portalicious/_build-download-translations.mjs
  interfaces/Portalicious/_build-manual-logout.mjs
  interfaces/Portalicious/_test-deployment-configuration.mjs
  interfaces/Portalicious/_verify-deployment-configuration.mjs
  interfaces/Portalicious/angular.json
  interfaces/Portalicious/package-lock.json
  interfaces/Portalicious/package.json
  interfaces/Portalicious/src/app/utils/locale.ts
  interfaces/Portalicious/src/environments/environment.ts.template.mjs
  interfaces/Portalicious/src/locale/messages.fr.xlf
  interfaces/Portalicious/src/locale/messages.nl.xlf
  interfaces/Portalicious/src/main.ts
  interfaces/Portalicious/staticwebapp.config.base.json
Labels: portalicious

#6490 portalicious: tweak edit personal info
  interfaces/Portalicious/src/app/app.theme.ts
  interfaces/Portalicious/src/app/components/form-field-wrapper/form-field-wrapper.component.html
  interfaces/Portalicious/src/app/components/form-field-wrapper/form-field-wrapper.component.ts
  interfaces/Portalicious/src/app/domains/project/project-attribute.helpers.ts
  interfaces/Portalicious/src/app/pages/project-registration-personal-information/components/edit-personal-information/edit-personal-information.component.html
  interfaces/Portalicious/src/app/pages/project-registration-personal-information/components/edit-personal-information/edit-personal-information.component.ts
  interfaces/Portalicious/src/locale/messages.xlf
  interfaces/Portalicious/src/styles.scss
  interfaces/Portalicious/tailwind.config.ts
Labels: portalicious

#6508 feat: Remove special treatment of "Portalicious"-label
  .github/release.yml
  .github/workflows/test_pull_request_formatting.yml
Labels: ignore-for-release, portalicious

#6505 fix: Replace AllUsers-endpoint with Users-Search endpoint on Team-page
  interfaces/Portalicious/src/app/domains/project/project.api.service.ts
  interfaces/Portalicious/src/app/domains/user/user.api.service.ts
  interfaces/Portalicious/src/app/pages/project-team/components/add-project-team-user-form/add-project-team-user-form.component.ts
  interfaces/Portalicious/src/app/pages/project-team/project-team.page.ts
  interfaces/Portalicious/src/app/pages/users/components/add-user-form/add-user-form.component.ts
  services/121-service/src/user/user.controller.ts
Labels: bugfix

#6504 Also validate that dates are valid when matching snapshot
  services/121-service/test/commercial-bank-ethiopia/export-validation-report.test.ts
  services/121-service/test/payment/do-payment-fsp-voucher.test.ts
  services/121-service/test/visa-card/export-report.test.ts
Labels: chore

#6507 chore: Remove unused + Update dependencies
  services/mock-service/package-lock.json
  services/mock-service/package.json
Labels: dependencies

#6512 Add E2E test for Error in missing columnToMatch Configuration
  e2e/portalicious/tests/ViewPayment/ErrorOnMissinCollumnMatchConfiguration.spec.ts
  services/121-service/src/scripts/enum/seed-script.enum.ts
  services/121-service/src/scripts/seed-configuration.const.ts
  services/121-service/src/seed-data/program/program-nlrc-pv-excel-fail.json
Labels: chore

#6514 fix: regression from easter egg code
  interfaces/Portalicious/src/app/components/query-table/components/query-table-global-search/query-table-global-search.component.html
Labels: bugfix

#6517 feat: update registration not found copy
  interfaces/Portalicious/src/app/components/page-layout/page-layout.component.ts
  interfaces/Portalicious/src/locale/messages.xlf
Labels: enhancement

#6518 chore: portalicious CI not failing with broken translations
  .github/workflows/test_interface_portalicious.yml
Labels: chore

#6513 Retry payment with Excel FSP
  e2e/portalicious/components/TableComponent.ts
  e2e/portalicious/pages/BasePage.ts
  e2e/portalicious/pages/PaymentsPage.ts
  e2e/portalicious/tests/ViewPayment/ErrorOnMissinCollumnMatchConfiguration.spec.ts
  e2e/portalicious/tests/ViewPayment/RetryFailedTransfers.spec.ts
  e2e/portalicious/tests/ViewPayment/RetryPaymentWithExcelFsp.spec.ts
  e2e/portalicious/tests/ViewPayment/ValidateViewPaymentsTable.spec.ts
  e2e/test-registration-data/test-reconciliation-Excel-pv.csv
  services/121-service/test/registrations/pagination/pagination-data.ts
Labels: chore

#6520 chore: refactor colored chip helpers
  interfaces/Portalicious/src/app/components/colored-chip/colored-chip.helper.ts
  interfaces/Portalicious/src/app/domains/registration/registration.helper.ts
  interfaces/Portalicious/src/app/domains/transaction/transaction.helper.ts
  interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/activity-log-expanded-row/activity-log-expanded-row.component.ts
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/table-cell-overview.component.ts
  interfaces/Portalicious/src/locale/messages.xlf
Labels: chore

#6516 Set focus on the first form-control, but preventing "too soon" validation-errors
  interfaces/Portalicious/src/app/components/form/form-sidebar.component.html
  interfaces/Portalicious/src/app/components/form/form-sidebar.component.ts
  interfaces/Portalicious/src/app/components/page-layout/components/header/header.component.html
Labels: bugfix

#6515 feat: retry transfer in activity log
  e2e/portalicious/pages/PaymentsPage.ts
  interfaces/Portalicious/eslint.config.js
  interfaces/Portalicious/src/app/pages/project-payment/components/retry-transfers-dialog/retry-transfers-dialog.component.html
  interfaces/Portalicious/src/app/pages/project-payment/components/retry-transfers-dialog/retry-transfers-dialog.component.ts
  interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.html
  interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/table-cell-overview/table-cell-overview.component.html
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/table-cell-overview/table-cell-overview.component.ts
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/project-registration-activity-log.page.ts
  interfaces/Portalicious/src/locale/messages.xlf
  interfaces/Portalicious/src/styles.scss
Labels: enhancement

#6530 fix: registration data cache invalidation
  interfaces/Portalicious/src/app/components/registration-page-layout/components/add-note-form/add-note-form.component.ts
  interfaces/Portalicious/src/app/domains/registration/registration.api.service.ts
  interfaces/Portalicious/src/app/pages/project-registration-personal-information/components/edit-personal-information/edit-personal-information.component.ts
  interfaces/Portalicious/src/app/pages/project-registration-personal-information/project-registration-personal-information.page.html
  interfaces/Portalicious/src/app/pages/project-registration-personal-information/project-registration-personal-information.page.ts
  interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-dialog/change-status-dialog.component.ts
  interfaces/Portalicious/src/app/pages/project-registrations/components/import-registrations/import-registrations.component.ts
Labels: bugfix

#6531 fix: Hand over correct secrets/configuration values
  .github/workflows/deploy_client-ethiopia_portal.yml
Labels: bugfix

#6533 fix: Keep checkboxes in a column, align multi-line labels more prettiously
  interfaces/Portalicious/src/app/components/query-table/components/query-table-column-management/query-table-column-management.component.html
Labels: bugfix

#6532 feat: add konami code to easter egg
  interfaces/Portalicious/package-lock.json
  interfaces/Portalicious/package.json
  interfaces/Portalicious/src/app/app.component.ts
Labels: enhancement

#6475 portalicious: rename pa to registration
  interfaces/Portal/src/app/models/export-type.model.ts
  interfaces/Portal/src/app/program/export-list/export-list.component.ts
  interfaces/Portal/src/app/program/export-select/export-select.component.ts
  interfaces/Portal/src/app/services/programs-service-api.service.ts
  interfaces/Portal/src/assets/i18n/ar.json
  interfaces/Portal/src/assets/i18n/en.json
  interfaces/Portal/src/assets/i18n/es.json
  interfaces/Portal/src/assets/i18n/fr.json
  interfaces/Portal/src/assets/i18n/nl.json
  interfaces/Portal/src/assets/i18n/ru.json
  interfaces/Portalicious/src/app/domains/project/project.api.service.ts
  interfaces/Portalicious/src/app/pages/project-payments/components/create-payment/create-payment.component.ts
  interfaces/Portalicious/src/app/pages/project-registrations/components/export-registrations/export-registrations.component.html
  interfaces/Portalicious/src/app/pages/project-team/components/add-project-team-user-form/add-project-team-user-form.component.html
  interfaces/Portalicious/src/app/services/export.service.ts
  interfaces/Portalicious/src/locale/messages.xlf
  services/121-service/src/metrics/enum/export-type.enum.ts
  services/121-service/src/metrics/metrics.controller.ts
  services/121-service/src/metrics/metrics.service.ts
  services/121-service/src/migration/1739294207739-RenamePeopleAffected.ts
  services/121-service/src/program-attributes/program-attributes.service.ts
  services/121-service/src/programs/dto/create-program.dto.ts
  services/121-service/src/programs/dto/program-registration-attribute.dto.ts
  services/121-service/src/programs/dto/program-return.dto.ts
  services/121-service/src/programs/program-registration-attribute.entity.ts
  services/121-service/src/programs/programs.controller.ts
  services/121-service/src/seed-data/program/program-cbe.json
  services/121-service/src/seed-data/program/program-nedbank.json
  services/121-service/src/seed-data/program/program-nlrc-ocw.json
  services/121-service/src/seed-data/program/program-nlrc-pv.json
  services/121-service/src/seed-data/program/program-safaricom.json
  services/121-service/src/seed-data/program/program-test.json
  services/121-service/swagger.json
  services/121-service/test/metrics/export-list.test.ts
  services/121-service/test/program/__snapshots__/create-program.test.ts.snap
  services/121-service/test/program/create-program-registration-attribute.test.ts
Labels: portalicious

#6523 Fix duplicate columns in excel reconciliation service
  services/121-service/src/metrics/metrics.service.ts
  services/121-service/src/payments/reconciliation/excel/excel-reconciliation.service.ts
  services/121-service/test/payment/__snapshots__/do-payment-fsp-excel.test.ts.snap
  services/121-service/test/payment/do-payment-fsp-excel.test.ts
Labels: bugfix

#6537 fix: update export strings in K6
  k6/models/metrics.js
  k6/models/programs.js
  k6/tests/retryFailedJobsOnStartupDuringQueueProcessing.js
Labels: chore

#6535 Include Matomo-client for tracking default metrics
  .github/workflows/deploy_client-demo_portalicious.yml
  .github/workflows/deploy_staging_portalicious.yml
  .github/workflows/deploy_test_portalicious.yml
  interfaces/Portalicious/.env.example
  interfaces/Portalicious/_build-deployment-configuration.mjs
  interfaces/Portalicious/_build-download-translations.mjs
  interfaces/Portalicious/_build-manual-logout.mjs
  interfaces/Portalicious/_matomo.utils.mjs
  interfaces/Portalicious/_test-deployment-configuration.mjs
  interfaces/Portalicious/_verify-deployment-configuration.mjs
  interfaces/Portalicious/eslint.config.js
  interfaces/Portalicious/package-lock.json
  interfaces/Portalicious/package.json
  interfaces/Portalicious/src/app/app.config.ts
  interfaces/Portalicious/src/app/pages/privacy/privacy.page.html
  interfaces/Portalicious/src/app/pages/privacy/privacy.page.ts
  interfaces/Portalicious/src/environments/environment.ts
  interfaces/Portalicious/src/environments/environment.ts.template.mjs
  interfaces/Portalicious/src/locale/messages.xlf
  interfaces/Portalicious/src/logout/logout.js
  interfaces/Portalicious/tsconfig.json
Labels: enhancement

#6536 show voucher button for paper voucher
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/activity-log-expanded-row/activity-log-expanded-row.component.ts
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/table-cell-overview/table-cell-overview.component.ts
Labels: bugfix

#6521 Duplicates backend & integration tests
  .github/workflows/test_k6.yml
  k6/helpers/registration-default.data.js
  k6/models/registrations.js
  k6/run-all-tests.sh
  k6/tests/findDuplicates100kRegistrations.js
  services/121-service/src/migration/1739551473017-duplicate-status.ts
  services/121-service/src/registration/const/filter-operation.const.ts
  services/121-service/src/registration/dto/duplicate-response.dto.ts
  services/121-service/src/registration/enum/duplicate-status.enum.ts
  services/121-service/src/registration/interfaces/get-duplicates-result.interface.ts
  services/121-service/src/registration/registration-view.entity.ts
  services/121-service/src/registration/registrations.controller.ts
  services/121-service/src/registration/registrations.service.ts
  services/121-service/src/registration/repositories/registration-scoped.repository.ts
  services/121-service/src/registration/services/registrations-pagination.service.ts
  services/121-service/src/registration/validators/registrations-input-validator.spec.ts
  services/121-service/src/registration/validators/registrations-input-validator.ts
  services/121-service/src/scripts/scripts.service.ts
  services/121-service/src/scripts/seed-mock-helpers.ts
  services/121-service/src/scripts/seed-multiple-nlrc-mock.ts
  services/121-service/src/scripts/sql/mock-introduce-duplicates.sql
  services/121-service/swagger.json
  services/121-service/test/helpers/registration.helper.ts
  services/121-service/test/registrations/bulk-update-registration.test.ts
  services/121-service/test/registrations/duplicates/get-duplicates.test.ts
  services/121-service/test/registrations/duplicates/get-registration-duplicate-status.test.ts
Labels: enhancement

#6540 chore: add sudan workflows
  .github/workflows/deploy_client-sudan_all.yml
  .github/workflows/deploy_client-sudan_portal.yml
  .github/workflows/deploy_client-sudan_service.yml
Labels: chore

#6527 Fix validation consistency of null values & send contact info to intersolve for intersolve attributes only
  services/.env.example
  services/121-service/src/registration/registrations.service.ts
  services/121-service/src/registration/validators/registrations-input-validator.spec.ts
  services/121-service/src/registration/validators/registrations-input-validator.ts
Labels: bugfix

#6539 chore: add tracking service to portalicious
  interfaces/Portalicious/eslint.config.js
  interfaces/Portalicious/src/app/app.config.ts
  interfaces/Portalicious/src/app/components/privacy/privacy-copy-no-tracking.component.ts
  interfaces/Portalicious/src/app/components/privacy/privacy-copy-tracking.component.ts
  interfaces/Portalicious/src/app/pages/privacy/privacy.page.html
  interfaces/Portalicious/src/app/pages/privacy/privacy.page.ts
  interfaces/Portalicious/src/app/services/tracking.service.ts
Labels: chore

#6543 Don't round off the transfer values
  interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts
Labels: bugfix

#6498 Intersolve visa physical card data endpoint change (Merge after 26 of February)
  services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.api.service.ts
  services/mock-service/src/fsp-integration/intersolve-visa/intersolve-visa.mock.controller.ts
  services/mock-service/src/fsp-integration/intersolve-visa/intersolve-visa.mock.service.ts
Labels: chore

#6546 deploy demo + training
  .github/workflows/deploy_all_demo+training.yml
  .github/workflows/deploy_portals_demo+training.yml
Labels: enhancement

#6549 chore: add workflows for Togo + Benin + Nigeria
  .github/workflows/deploy_client-benin_all.yml
  .github/workflows/deploy_client-benin_portal.yml
  .github/workflows/deploy_client-benin_service.yml
  .github/workflows/deploy_client-nigeria_all.yml
  .github/workflows/deploy_client-nigeria_portal.yml
  .github/workflows/deploy_client-nigeria_service.yml
  .github/workflows/deploy_client-togo_all.yml
  .github/workflows/deploy_client-togo_portal.yml
  .github/workflows/deploy_client-togo_service.yml
Labels: chore

#6538 Refactor move logic to registration action menu service
  interfaces/Portalicious/src/app/domains/registration/registration.model.ts
  interfaces/Portalicious/src/app/pages/project-registrations/project-registrations.page.ts
  interfaces/Portalicious/src/app/services/registration-action-menu.service.ts
Labels: chore

#6553 chore: upgrade primeng to 19.09
  interfaces/Portalicious/package-lock.json
  interfaces/Portalicious/package.json
  interfaces/Portalicious/src/app/components/query-table/query-table.component.html
Labels: chore

#6554 chore: add matomo to portalicious deploy yaml vars
  .github/workflows/deploy_client-benin_portal.yml
  .github/workflows/deploy_client-eswatini_portal.yml
  .github/workflows/deploy_client-ethiopia_portal.yml
  .github/workflows/deploy_client-ivorycoast_portal.yml
  .github/workflows/deploy_client-krcs_portalicious.yml
  .github/workflows/deploy_client-nigeria_portal.yml
  .github/workflows/deploy_client-nlrc_portalicious.yml
  .github/workflows/deploy_client-slovakia_portal.yml
  .github/workflows/deploy_client-somalia_portal.yml
  .github/workflows/deploy_client-southafrica_portalicious.yml
  .github/workflows/deploy_client-sudan_portal.yml
  .github/workflows/deploy_client-togo_portal.yml
  .github/workflows/deploy_client-training_portalicious.yml
Labels: chore

#6551 Revert "deploy demo + training"
  .github/workflows/deploy_all_demo+training.yml
  .github/workflows/deploy_portals_demo+training.yml
Labels: chore

#6555 chore: remove help a child from release process
  .github/workflows/deploy_client-helpachild_all.yml
  README.md
Labels: chore

#6522 feat: duplicates in portalicious
  e2e/README.md
  e2e/package-lock.json
  e2e/portalicious/pages/BasePage.ts
  e2e/portalicious/pages/RegistrationActivityLogPage.ts
  e2e/portalicious/pages/RegistrationBasePage.ts
  e2e/portalicious/pages/RegistrationPersonalInformationPage.ts
  e2e/portalicious/pages/RegistrationsPage.ts
  e2e/portalicious/tests/ViewAndManagePeopleAffected/ValidateDuplicateBadges.spec.ts
  e2e/portalicious/tests/ViewAndManagePeopleAffected/ValidateDuplicateBanner.spec.ts
  e2e/portalicious/tests/ViewAndManagePeopleAffected/ValidateDuplicateChanges.spec.ts
  e2e/portalicious/tests/ViewAndManagePeopleAffected/ValidateDuplicateChangesFor3Registrations.spec.ts
  interfaces/Portalicious/package-lock.json
  interfaces/Portalicious/package.json
  interfaces/Portalicious/src/app/app.config.ts
  interfaces/Portalicious/src/app/components/colored-chip/colored-chip.helper.ts
  interfaces/Portalicious/src/app/components/registration-page-layout/components/add-note-form/add-note-form.component.ts
  interfaces/Portalicious/src/app/components/registration-page-layout/components/registration-duplicates-banner/registration-duplicates-banner.component.html
  interfaces/Portalicious/src/app/components/registration-page-layout/components/registration-duplicates-banner/registration-duplicates-banner.component.ts
  interfaces/Portalicious/src/app/components/registration-page-layout/registration-page-layout.component.html
  interfaces/Portalicious/src/app/components/registration-page-layout/registration-page-layout.component.ts
  interfaces/Portalicious/src/app/domains/registration/registration.api.service.ts
  interfaces/Portalicious/src/app/domains/registration/registration.helper.ts
  interfaces/Portalicious/src/app/domains/registration/registration.model.ts
  interfaces/Portalicious/src/app/pages/project-registration-personal-information/components/edit-personal-information/edit-personal-information.component.ts
  interfaces/Portalicious/src/app/pages/project-registration-personal-information/project-registration-personal-information.page.html
  interfaces/Portalicious/src/app/pages/project-registration-personal-information/project-registration-personal-information.page.ts
  interfaces/Portalicious/src/app/services/registrations-table-column.service.ts
  interfaces/Portalicious/src/assets/duplicates.svg
  interfaces/Portalicious/src/locale/messages.xlf
  interfaces/Portalicious/src/styles.scss
Labels: enhancement

#6562 chore: update jrethiopia to deploy portalicious
  .github/workflows/deploy_client-jrethiopia_all.yml
  .github/workflows/deploy_client-jrethiopia_portal.yml
Labels: chore

#6560 feat: improve empty table message in "create payment" flow
  interfaces/Portalicious/src/app/components/query-table/query-table.component.html
  interfaces/Portalicious/src/app/components/registrations-table/registrations-table.component.html
  interfaces/Portalicious/src/app/components/registrations-table/registrations-table.component.ts
  interfaces/Portalicious/src/app/pages/project-registrations/project-registrations.page.html
  interfaces/Portalicious/src/app/pages/project-registrations/project-registrations.page.ts
Labels: enhancement

#6559 fix: unresponsive if no columns selected in table
  interfaces/Portalicious/src/app/components/query-table/components/query-table-column-management/query-table-column-management.component.ts
  interfaces/Portalicious/src/locale/messages.xlf
Labels: bugfix

#6558 fix: error message when attempting to re-include a registration
  interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-dialog/change-status-dialog.component.html
  interfaces/Portalicious/src/locale/messages.xlf
Labels: bugfix

#6561 fix: prevent retrying failed transfers whilst another payment is in progress
  interfaces/Portalicious/src/app/pages/project-payment/components/retry-transfers-dialog/retry-transfers-dialog.component.ts
  interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/table-cell-overview/table-cell-overview.component.ts
Labels: bugfix

#6541 Feat.action menu profile page
  e2e/portalicious/pages/BasePage.ts
  e2e/portalicious/pages/RegistrationBasePage.ts
  e2e/portalicious/tests/RegistrationPage/InitiateActions.spec.ts
  e2e/portalicious/tests/RegistrationPage/ViewAvailableActions.spec.ts
  interfaces/Portalicious/src/app/app.theme.ts
  interfaces/Portalicious/src/app/components/button-menu/button-menu.component.html
  interfaces/Portalicious/src/app/components/button-menu/button-menu.component.ts
  interfaces/Portalicious/src/app/components/registration-page-layout/registration-page-layout.component.html
  interfaces/Portalicious/src/app/components/registration-page-layout/registration-page-layout.component.ts
  interfaces/Portalicious/src/app/services/paginate-query.service.ts
  interfaces/Portalicious/src/locale/messages.xlf
  services/121-service/test/helpers/registration.helper.ts
  services/121-service/test/helpers/utility.helper.ts
Labels: enhancement
