Repository global-121/121-platform, pull requests merged in 2025-04, with the labels that each got.

#6675 remove annoying log
  services/121-service/src/notifications/lookup/lookup.service.ts
Labels: chore

#6684 tiny refactor in cron job controller
  services/121-service/src/cronjob/cronjob.controller.ts
  services/121-service/src/cronjob/cronjob.service.ts
Labels: chore

#6683 fix: Make sure the order of entity-IDs doesn't matter in equallity-check
  services/121-service/src/events/events.service.ts
Labels: bugfix

#6583 Feat.ignore duplicates
  interfaces/Portalicious/src/app/domains/registration/registration.helper.ts
  services/121-service/src/activities/activities.controller.ts
  services/121-service/src/activities/activities.mapper.ts
  services/121-service/src/activities/activities.service.ts
  services/121-service/src/activities/enum/activity-type.enum.ts
  services/121-service/src/activities/interfaces/ignored-duplicate-activity.interface.ts
  services/121-service/src/activities/types/activity.type.ts
  services/121-service/src/events/enum/event-attribute-key.enum.ts
  services/121-service/src/events/enum/event.enum.ts
  services/121-service/src/events/events.service.ts
  services/121-service/src/events/interfaces/create-for-ignored-duplicate-pair.interface.ts
  services/121-service/src/events/interfaces/registration-identifiers.interface.ts
  services/121-service/src/migration/1741263428887-unique-registration-pairs.ts
  services/121-service/src/registration/dto/create-uniques.dto.ts
  services/121-service/src/registration/registration-view.entity.ts
  services/121-service/src/registration/registrations.controller.ts
  services/121-service/src/registration/registrations.module.ts
  services/121-service/src/registration/registrations.service.spec.ts
  services/121-service/src/registration/registrations.service.ts
  services/121-service/src/registration/repositories/registration-scoped.repository.ts
  services/121-service/src/registration/repositories/unique-registration-pair.repository.ts
  services/121-service/src/registration/unique-registration-pair.entity.ts
  services/121-service/src/scripts/sql/mock-introduce-duplicates.sql
  services/121-service/swagger.json
  services/121-service/test/helpers/registration.helper.ts
  services/121-service/test/registrations/duplicates/__snapshots__/create-registration-uniques-errors.test.ts.snap
  services/121-service/test/registrations/duplicates/create-registration-uniques-errors.test.ts
  services/121-service/test/registrations/duplicates/create-registration-uniques.test.ts
  services/121-service/test/registrations/duplicates/get-duplicates.test.ts
  services/121-service/test/registrations/duplicates/get-registration-duplicate-status.test.ts
Labels: enhancement

#6692 fix: RTL-issues with spacing and placement of icons/menus/buttons
  e2e/portalicious/tests/Navigation/BasicNavigation.spec.ts
  interfaces/Portalicious/README.md
  interfaces/Portalicious/angular.json
  interfaces/Portalicious/src/app/app.component.ts
  interfaces/Portalicious/src/app/components/confirmation-dialog/confirmation-dialog.component.html
  interfaces/Portalicious/src/app/components/data-list/data-list.component.html
  interfaces/Portalicious/src/app/components/fullscreen-spinner/fullscreen-spinner.component.html
  interfaces/Portalicious/src/app/components/logo/logo.component.html
  interfaces/Portalicious/src/app/components/query-table/query-table.component.html
  interfaces/Portalicious/src/app/components/registration-page-layout/registration-page-layout.component.html
  interfaces/Portalicious/src/app/pages/auth-callback/auth-callback.page.html
  interfaces/Portalicious/src/app/pages/project-payment/components/import-reconciliation-data/import-reconciliation-data.component.html
  interfaces/Portalicious/src/app/pages/project-payment/components/import-reconciliation-data/import-reconciliation-data.component.ts
  interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.html
  interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts
  interfaces/Portalicious/src/app/pages/project-payments/components/create-payment/create-payment.component.html
  interfaces/Portalicious/src/app/pages/project-payments/components/create-payment/create-payment.component.ts
  interfaces/Portalicious/src/app/pages/project-payments/project-payments.page.html
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/activity-log-voucher-dialog/activity-log-voucher-dialog.component.html
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/activity-log-voucher-dialog/activity-log-voucher-dialog.component.ts
  interfaces/Portalicious/src/app/pages/project-registration-debit-cards/project-registration-debit-cards.page.html
  interfaces/Portalicious/src/app/pages/project-registration-debit-cards/project-registration-debit-cards.page.ts
  interfaces/Portalicious/src/app/pages/project-registration-personal-information/components/edit-personal-information/edit-personal-information.component.html
  interfaces/Portalicious/src/app/pages/project-registration-personal-information/components/edit-personal-information/edit-personal-information.component.ts
  interfaces/Portalicious/src/app/pages/project-registration-personal-information/project-registration-personal-information.page.html
  interfaces/Portalicious/src/app/pages/project-registration-personal-information/project-registration-personal-information.page.ts
  interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-contents-with-custom-message/change-status-contents-with-custom-message.component.html
  interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-dialog/change-status-dialog.component.html
  interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-submit-buttons/change-status-submit-buttons.component.html
  interfaces/Portalicious/src/app/pages/project-registrations/components/custom-message-control/custom-message-control.component.ts
  interfaces/Portalicious/src/app/pages/project-registrations/components/send-message-dialog/send-message-dialog.component.html
  interfaces/Portalicious/src/app/pages/project-registrations/project-registrations.page.html
  interfaces/Portalicious/src/app/pages/project-registrations/project-registrations.page.ts
  interfaces/Portalicious/src/app/pages/project-team/project-team.page.html
  interfaces/Portalicious/src/app/pages/project-team/project-team.page.ts
  interfaces/Portalicious/src/app/pages/users/users.page.html
  interfaces/Portalicious/src/app/pages/users/users.page.ts
  interfaces/Portalicious/src/locale/messages.xlf
  interfaces/Portalicious/src/styles.scss
Labels: enhancement, Translations

#6682 feat: make old card number copiable
  interfaces/Portalicious/src/app/pages/project-registration-debit-cards/project-registration-debit-cards.page.html
  interfaces/Portalicious/src/app/pages/project-registration-debit-cards/project-registration-debit-cards.page.ts
Labels: enhancement

#6685 Add E2E tests for view, filter and sort registrations in table
  e2e/portalicious/components/TableComponent.ts
  e2e/portalicious/pages/RegistrationsPage.ts
  e2e/portalicious/tests/ImportRegistrations/ImportRegistrationsSuccessfully.spec.ts
  e2e/portalicious/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByDate.spec.ts
  e2e/portalicious/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByDropdownSelection.spec.ts
  e2e/portalicious/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByFsp.spec.ts
  e2e/portalicious/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByNumberInput.spec.ts
  e2e/portalicious/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByText.spec.ts
  services/121-service/test/registrations/pagination/pagination-data.ts
Labels: chore

#6689 Improve error for cronjob authentication failure
  services/121-service/src/cronjob/cronjob.controller.ts
  services/121-service/src/cronjob/cronjob.service.spec.ts
  services/121-service/src/cronjob/cronjob.service.ts
  services/121-service/src/utils/axios/axios-calls.service.spec.ts
  services/121-service/src/utils/axios/axios-calls.service.ts
  services/121-service/test/cronjob/cronjobs.test.ts
  services/121-service/test/payment/do-payment-fsp-nedbank.test.ts
Labels: chore

#6705 Update default roles on export
  services/121-service/src/scripts/seed-init.ts
Labels: enhancement

#6699 docs: Improve README for working with translations
  interfaces/Portalicious/README.md
Labels: chore, Translations

#6706 Add default kobo validation role
  e2e/portalicious/tests/ManageTeam/AllSystemUsersCanBeAddedToProjectTeam.spec.ts
  e2e/portalicious/tests/ManageTeam/AllUsersAssignedShouldBeVisible.spec.ts
  e2e/portalicious/tests/ManageTeam/AssignSuccessfullyRolesToUser.spec.ts
  e2e/portalicious/tests/ManageTeam/RemoveUserFromTeam.spec.ts
  e2e/portalicious/tests/Users/ViewUsersPage.spec.ts
  services/.env.example
  services/121-service/src/scripts/seed-helper.ts
  services/121-service/src/scripts/seed-init.ts
  services/121-service/src/user/user-role.enum.ts
Labels: enhancement

#6711 E2E test for advanced filtering by date cherry pick
  e2e/portalicious/components/TableComponent.ts
  e2e/portalicious/pages/RegistrationsPage.ts
  e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusCompleted.spec.ts
  e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusDeclined.spec.ts
  e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusIncluded.spec.ts
  e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusPaused.spec.ts
  e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusRegistered.spec.ts
  e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusValidated.spec.ts
  e2e/portalicious/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByDate.spec.ts
  e2e/portalicious/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByDropdownSelection.spec.ts
Labels: chore

#6694 Get registration by numeric of date range in portalicious
  e2e/portalicious/components/TableComponent.ts
  e2e/portalicious/pages/RegistrationsPage.ts
  e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusCompleted.spec.ts
  e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusDeclined.spec.ts
  e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusIncluded.spec.ts
  e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusPaused.spec.ts
  e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusRegistered.spec.ts
  e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusValidated.spec.ts
  e2e/portalicious/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByDate.spec.ts
  e2e/portalicious/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByDropdownSelection.spec.ts
  e2e/portalicious/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByNumberInput.spec.ts
  interfaces/Portalicious/package-lock.json
  interfaces/Portalicious/package.json
  interfaces/Portalicious/src/app/components/query-table/query-table.component.html
  interfaces/Portalicious/src/app/components/query-table/query-table.component.ts
  interfaces/Portalicious/src/app/components/registration-page-layout/registration-page-layout.component.html
  interfaces/Portalicious/src/app/domains/project/project-attribute.helpers.ts
  interfaces/Portalicious/src/app/domains/project/project.api.service.ts
  interfaces/Portalicious/src/app/services/paginate-query.service.spec.ts
  interfaces/Portalicious/src/app/services/paginate-query.service.ts
  interfaces/Portalicious/src/app/services/registration-attribute.service.ts
  interfaces/Portalicious/src/app/services/registrations-table-column.service.ts
  interfaces/Portalicious/src/app/utils/local-time-to-utc-time.ts
  interfaces/Portalicious/src/locale/messages.xlf
  services/121-service/src/registration/enum/registration-attribute.enum.ts
  services/121-service/src/registration/services/registrations-pagination.service.ts
Labels: enhancement, chore

#6713 Enable debugger for Mock Service and Integration Tests
  .vscode/launch.json
  services/121-service/README.md
  services/121-service/package.json
  services/docker-compose.development.yml
  services/mock-service/package.json
Labels: chore

#6717 fix: Align cookie security settings between login/out endpoints
  services/121-service/src/user/user.controller.ts
  services/121-service/src/user/user.service.ts
Labels: bugfix

#6686 chore: Upgrade Portalicious dependencies
  .github/dependabot.yml
  e2e/portalicious/pages/RegistrationsPage.ts
  interfaces/Portalicious/_build-download-translations.mjs
  interfaces/Portalicious/angular.json
  interfaces/Portalicious/eslint.config.mjs
  interfaces/Portalicious/package-lock.json
  interfaces/Portalicious/package.json
  interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-dialog/change-status-dialog.component.ts
  interfaces/Portalicious/src/app/pages/project-registrations/components/custom-message-preview/custom-message-preview.component.html
  interfaces/Portalicious/src/app/services/messaging.service.ts
  interfaces/Portalicious/tailwind.config.ts
Labels: dependencies, chore

#6709 Replace old-Portals with 🆕-Portals (for Demo, Training, DRC, Greece, Kenya/KRCS, SouthAfrica, Zambia)
  .github/workflows/deploy_client-demo_all.yml
  .github/workflows/deploy_client-demo_portal.yml
  .github/workflows/deploy_client-demo_portalicious.yml
  .github/workflows/deploy_client-drc_all.yml
  .github/workflows/deploy_client-drc_portal.yml
  .github/workflows/deploy_client-drc_portalicious.yml
  .github/workflows/deploy_client-greece_all.yml
  .github/workflows/deploy_client-greece_portal.yml
  .github/workflows/deploy_client-greece_portalicious.yml
  .github/workflows/deploy_client-krcs_all.yml
  .github/workflows/deploy_client-krcs_portal.yml
  .github/workflows/deploy_client-krcs_portalicious.yml
  .github/workflows/deploy_client-southafrica_all.yml
  .github/workflows/deploy_client-southafrica_portal.yml
  .github/workflows/deploy_client-southafrica_portalicious.yml
  .github/workflows/deploy_client-training_all.yml
  .github/workflows/deploy_client-training_portal.yml
  .github/workflows/deploy_client-training_portalicious.yml
  .github/workflows/deploy_client-zambia_all.yml
  .github/workflows/deploy_client-zambia_portal.yml
  .github/workflows/deploy_client-zambia_portalicious.yml
Labels: portalicious, other

#6707 update test data so names match the test program
  e2e/test-registration-data/test-registrations-westeros-20.csv
  services/121-service/src/seed-data/program/program-test.json
  services/121-service/test/payment/__snapshots__/do-payment-fsp-excel.test.ts.snap
  services/121-service/test/registrations/pagination/pagination-data.ts
Labels: chore

#6715 Total Payment Amounts: round, then sum
  interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts
  services/121-service/src/payments/payments.service.ts
Labels: bugfix

#6729 changed ux on date filters
  e2e/portalicious/components/TableComponent.ts
  e2e/portalicious/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByDate.spec.ts
  interfaces/Portalicious/src/app/components/query-table/query-table.component.ts
  interfaces/Portalicious/src/locale/messages.xlf
Labels: chore

#6730 Upgrade Portalicious dependencies
  interfaces/Portalicious/eslint.config.mjs
  interfaces/Portalicious/package-lock.json
  interfaces/Portalicious/package.json
Labels: dependencies, chore

#6731 Upgrade dependencies Mock-Service
  services/mock-service/package-lock.json
  services/mock-service/package.json
Labels: dependencies

#6656 fix: ignore-duplicates frontend
  e2e/portalicious/pages/BasePage.ts
  e2e/portalicious/tests/ViewAndManagePeopleAffected/IgnoreDuplicates.spec.ts
  interfaces/Portalicious/src/app/components/confirmation-dialog/confirmation-dialog.component.html
  interfaces/Portalicious/src/app/components/confirmation-dialog/confirmation-dialog.component.ts
  interfaces/Portalicious/src/app/components/registration-page-layout/components/ignore-duplicates-dialog/ignore-duplication-dialog.component.html
  interfaces/Portalicious/src/app/components/registration-page-layout/components/ignore-duplicates-dialog/ignore-duplication-dialog.component.ts
  interfaces/Portalicious/src/app/components/registration-page-layout/registration-page-layout.component.html
  interfaces/Portalicious/src/app/components/registration-page-layout/registration-page-layout.component.ts
  interfaces/Portalicious/src/app/domains/registration/registration.api.service.ts
  interfaces/Portalicious/src/app/domains/registration/registration.helper.ts
  interfaces/Portalicious/src/app/domains/registration/registration.model.ts
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/activity-log-expanded-row/activity-log-expanded-row.component.ts
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/table-cell-overview/table-cell-overview.component.ts
  interfaces/Portalicious/src/app/pages/project-registration-personal-information/components/edit-personal-information/edit-personal-information.component.html
  interfaces/Portalicious/src/app/pages/project-registration-personal-information/components/edit-personal-information/edit-personal-information.component.ts
  interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-reason/change-status-reason.component.html
  interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-reason/change-status-reason.component.ts
  interfaces/Portalicious/src/app/pages/project-registrations/components/export-registrations/export-registrations.component.html
  interfaces/Portalicious/src/app/pages/project-registrations/components/export-registrations/export-registrations.component.ts
  interfaces/Portalicious/src/locale/messages.xlf
  services/121-service/src/migration/1743597529999-created-ignore-duplication-permission.ts
  services/121-service/src/registration/registrations.controller.ts
  services/121-service/src/registration/repositories/registration-scoped.repository.ts
  services/121-service/src/scripts/seed-init.ts
  services/121-service/src/user/enum/permission.enum.ts
Labels: enhancement

#6736 Add config for a merge-queue to auto-rebase/merge PRs
  .github/workflows/test_e2e_portal.yml
  .github/workflows/test_e2e_portalicious.yml
  .github/workflows/test_formatting.yml
  .github/workflows/test_interface_portal.yml
  .github/workflows/test_interface_portalicious.yml
  .github/workflows/test_k6.yml
  .github/workflows/test_mock-service_code.yml
  .github/workflows/test_service_api.yml
  .github/workflows/test_service_code.yml
  .github/workflows/test_workflows.yml
Labels: ignore-for-release, chore

#6739 feat: add link to ignored activity log
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/table-cell-overview/table-cell-overview.component.html
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/table-cell-overview/table-cell-overview.component.ts
  interfaces/Portalicious/src/locale/messages.xlf
Labels: enhancement

#6740 feat: default sort by registrationProgramId -> descending in registrations table
  e2e/portalicious/tests/DoPayment/ShowPaymentSummary.spec.ts
  interfaces/Portalicious/eslint.config.mjs
  interfaces/Portalicious/src/app/components/registrations-table/registrations-table.component.html
Labels: enhancement

#6718 Add E2E test for editing registration information
  e2e/portalicious/helpers/PersonalInformationFields.ts
  e2e/portalicious/pages/RegistrationActivityLogPage.ts
  e2e/portalicious/pages/RegistrationPersonalInformationPage.ts
  e2e/portalicious/tests/EditRegistration/EditRegistration.spec.ts
  e2e/portalicious/tests/EditRegistration/EditRegistrationFsp.spec.ts
  e2e/portalicious/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByText.spec.ts
  interfaces/Portalicious/src/app/components/data-list/data-list.component.html
  interfaces/Portalicious/src/app/components/data-list/data-list.component.ts
  interfaces/Portalicious/src/app/components/form-field-wrapper/form-field-wrapper.component.html
  interfaces/Portalicious/src/app/components/form-field-wrapper/form-field-wrapper.component.ts
  interfaces/Portalicious/src/app/pages/project-registration-personal-information/components/edit-personal-information/edit-personal-information.component.html
Labels: chore

#6753 ci: Make downloading translations configurable from the ENV-variables in GitHub-environments
  .github/actions/build-interface/action.yml
  .github/workflows/deploy_client-benin_portal.yml
  .github/workflows/deploy_client-demo_portal.yml
  .github/workflows/deploy_client-drc_portal.yml
  .github/workflows/deploy_client-eswatini_portal.yml
  .github/workflows/deploy_client-ethiopia_portal.yml
  .github/workflows/deploy_client-greece_portal.yml
  .github/workflows/deploy_client-ivorycoast_portal.yml
  .github/workflows/deploy_client-jrethiopia_portal.yml
  .github/workflows/deploy_client-krcs_portal.yml
  .github/workflows/deploy_client-nigeria_portal.yml
  .github/workflows/deploy_client-nlrc_portalicious.yml
  .github/workflows/deploy_client-slovakia_portal.yml
  .github/workflows/deploy_client-somalia_portal.yml
  .github/workflows/deploy_client-southafrica_portal.yml
  .github/workflows/deploy_client-sudan_portal.yml
  .github/workflows/deploy_client-togo_portal.yml
  .github/workflows/deploy_client-training_portal.yml
  .github/workflows/deploy_client-zambia_portal.yml
  .github/workflows/deploy_staging_portalicious.yml
  .github/workflows/deploy_test_portalicious.yml
  .github/workflows/test_e2e_portalicious.yml
  interfaces/Portalicious/.knip.json
  interfaces/Portalicious/.vscode/extensions.json
  interfaces/Portalicious/_build-deployment-configuration.mjs
  interfaces/Portalicious/_build-download-translations.mjs
  interfaces/Portalicious/_build-manual-logout.mjs
  interfaces/Portalicious/_env.utils.mjs
  interfaces/Portalicious/_env.utils.spec.ts
  interfaces/Portalicious/_matomo.utils.mjs
  interfaces/Portalicious/_set-env-variables.mjs
  interfaces/Portalicious/_test-deployment-configuration.mjs
  interfaces/Portalicious/_verify-build.mjs
  interfaces/Portalicious/_verify-deployment-configuration.mjs
  interfaces/Portalicious/angular.json
  interfaces/Portalicious/package.json
  interfaces/Portalicious/tsconfig.spec.json
Labels: ignore-for-release, chore, Translations

#6755 Is payment empty e2e
  e2e/portalicious/pages/PaymentsPage.ts
  e2e/portalicious/tests/ViewPayments/ShowPaymentSummary.spec.ts
Labels: chore

#6754 chore: security alerts
  services/121-service/package-lock.json
  services/121-service/package.json
Labels: chore

#6759 No self assign frontend and e2e test
  e2e/portalicious/pages/ProjectTeam.ts
  e2e/portalicious/tests/ManageTeam/UserCannotAssignRolesToSelf.spec.ts
  interfaces/Portalicious/src/app/pages/project-team/components/add-project-team-user-form/add-project-team-user-form.component.html
  interfaces/Portalicious/src/app/pages/project-team/components/add-project-team-user-form/add-project-team-user-form.component.ts
  interfaces/Portalicious/src/locale/messages.xlf
Labels: enhancement

#6758 No self update
  services/121-service/src/user/helpers/throw-if-self-update.spec.ts
  services/121-service/src/user/helpers/throw-if-self-update.ts
  services/121-service/src/user/user.controller.ts
  services/121-service/test/programs/users/__snapshots__/roles.test.ts.snap
  services/121-service/test/programs/users/roles.test.ts
Labels: enhancement

#6763 fix: currency defaulting to EUR
  .github/workflows/test_pull_request_formatting.yml
  interfaces/Portalicious/src/app/app.config.ts
  interfaces/Portalicious/src/app/components/data-list/data-list.component.html
  interfaces/Portalicious/src/app/pages/project-monitoring/project-monitoring.page.html
  interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts
  interfaces/Portalicious/src/app/pages/project-payments/components/create-payment/create-payment.component.ts
  interfaces/Portalicious/src/app/pages/project-payments/components/payment-summary-card/payment-summary-card.component.ts
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/activity-log-expanded-row/activity-log-expanded-row.component.ts
  interfaces/Portalicious/src/app/pages/project-registration-activity-log/project-registration-activity-log.page.ts
  interfaces/Portalicious/src/app/pages/project-registration-debit-cards/project-registration-debit-cards.page.ts
  interfaces/Portalicious/src/app/pages/projects-overview/components/project-summary-card/project-summary-card.component.ts
Labels: bugfix

#6764 fix: Prevent timeout on CBE-endpoint triggered by Cronjob (to improve clarity in logs/monitoring)
  services/121-service/src/payments/reconciliation/commercial-bank-ethiopia-reconciliation/commercial-bank-ethiopia-reconciliation.controller.ts
  services/121-service/src/utils/soap/soap.service.ts
Labels: chore

#6771 ci: Replace external diff-check with local, specific test for translations ONLY
  .github/workflows/test_interface_portalicious.yml
Labels: enhancement, ignore-for-release, chore

#6772 fix: don't send message if option unchecked
  interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-dialog/change-status-dialog.component.ts
Labels: bugfix

#6777 fix: Remove unclear/already-resolved/blocking comment
  e2e/portalicious/helpers/PersonalInformationFields.ts
  e2e/portalicious/pages/RegistrationPersonalInformationPage.ts
  services/mock-service/src/fsp-integration/commercial-bank-ethiopia/commercial-bank-ethiopia.mock.controller.ts
Labels: bugfix, ignore-for-release

#6776 ci: Include changes to the 121-service's code to trigger Portalicious' tests
  .github/workflows/test_interface_portalicious.yml
Labels: ignore-for-release, chore

#6766 ci: Help Dependabot test for updated dependencies (not local ones)
  .github/dependabot.yml
  services/121-service/package-lock.json
  services/121-service/package.json
Labels: dependencies, ignore-for-release, chore
