Repository global-121/121-platform, pull requests merged in 2025-07, with the labels that each got.

#7000 fix: flaky do-payment-filter AB#37009
  services/121-service/test/helpers/registration.helper.ts
Labels: chore

#6981 More refactor of transaction job processor
  services/121-service/src/transaction-jobs/services/transaction-jobs-helper.service.spec.ts
  services/121-service/src/transaction-jobs/services/transaction-jobs-helper.service.ts
  services/121-service/src/transaction-jobs/services/transaction-jobs-intersolve-visa.service.ts
  services/121-service/src/transaction-jobs/services/transaction-jobs-nedbank.service.spec.ts
  services/121-service/src/transaction-jobs/services/transaction-jobs-nedbank.service.ts
  services/121-service/src/transaction-jobs/services/transaction-jobs-onafriq.service.ts
  services/121-service/src/transaction-jobs/services/transaction-jobs-safaricom.service.ts
  services/121-service/src/transaction-queues/dto/intersolve-visa-transaction-job.dto.ts
  services/121-service/src/transaction-queues/dto/nedbank-transaction-job.dto.ts
  services/121-service/src/transaction-queues/dto/onafriq-transaction-job.dto.ts
  services/121-service/src/transaction-queues/dto/safaricom-transaction-job.dto.ts
  services/121-service/src/transaction-queues/dto/shared-transaction-job.dto.ts
Labels: chore

#6999 refactor: Align Dockerfile(s) + define their own healthcheck
  .github/workflows/test_e2e_portal.yml
  .github/workflows/test_service_api.yml
  package.json
  services/121-service/Dockerfile
  services/docker-compose.development.yml
  services/docker-compose.yml
  services/mock-service/Dockerfile
Labels: ignore-for-release, chore

#6976 chore: send coverage data to QLTY
  .github/workflows/test_interface_portal.yml
  .github/workflows/test_service_api.yml
  .github/workflows/test_service_static_checks.yml
  README.md
  interfaces/portal/README.md
  interfaces/portal/angular.json
  interfaces/portal/karma.conf.js
  interfaces/portal/package.json
  services/121-service/.knip.json
  services/121-service/README.md
  services/121-service/package-lock.json
  services/121-service/package.json
Labels: chore

#7013 remove help a child exception from releases checklist
  README.md
Labels: chore

#6969 Strip unknown value on dto in controller
  services/121-service/src/main.ts
  services/121-service/src/notifications/message-incoming/message-incoming.controller.ts
  services/121-service/src/notifications/whatsapp/whatsapp.controller.ts
  services/121-service/src/payments/reconciliation/onafriq-reconciliation/onafriq-reconciliation.controller.ts
  services/121-service/src/payments/reconciliation/safaricom-reconciliation/dtos/safaricom-timeout-callback.dto.ts
  services/121-service/src/payments/reconciliation/safaricom-reconciliation/dtos/safaricom-transfer-callback.dto.ts
  services/121-service/src/payments/reconciliation/safaricom-reconciliation/safaricom-reconciliation.controller.ts
  services/121-service/src/payments/reconciliation/safaricom-reconciliation/safaricom-reconciliation.service.ts
  services/121-service/src/programs/dto/create-program.dto.ts
  services/121-service/src/programs/dto/program-registration-attribute.dto.ts
  services/121-service/src/programs/dto/update-program.dto.ts
  services/121-service/src/programs/programs.service.ts
  services/121-service/src/registration/dto/update-registration.dto.ts
  services/121-service/src/registration/registrations.controller.ts
  services/121-service/src/registration/validators/any-valid-body.validator.ts
  services/121-service/src/user/dto/create-user-role.dto.ts
  services/121-service/src/validation-pipe-options.const.ts
  services/121-service/test/middlewares/any-valid-body-decorator.test.ts
  services/121-service/test/middlewares/program-exists.interceptor.test.ts
  services/121-service/test/programs/users/roles.test.ts
Labels: bugfix

#7014 Also log kobo errors
  services/121-service/src/kobo-connect/kobo-connect.service.ts
Labels: chore

#7011 chore: knip improvements
  services/121-service/.knip.json
  services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/commercial-bank-ethiopia.service.spec.ts
  services/121-service/src/program-attributes/program-attributes.service.spec.ts
  services/121-service/src/registration/services/registrations-bulk.service.spec.ts
  services/121-service/src/utils/test-helpers/createQueryBuilderMock.helper.spec.ts
  services/121-service/src/utils/test-helpers/createQueryBuilderMock.helper.ts
  services/121-service/src/utils/unit-test.helpers.spec.ts
  services/121-service/src/utils/unit-test.helpers.ts
Labels: chore

#7015 retry flaky api test suite once
  services/121-service/test/helpers/registration.helper.ts
  services/121-service/test/payment/do-payment-filter.test.ts
  services/121-service/test/registrations/pagination/update-registration-status.test.ts
Labels: chore

#7021 test: Replace arbitrary waitFor with actual message-counting
  services/121-service/test/visa-card/block-visa-card.test.ts
Labels: ignore-for-release, chore

#7022 chore: try to fix annoying flaky block visa card test
  services/121-service/test/visa-card/block-visa-card.test.ts
Labels: chore

#6980 feat: set up event tracking
  interfaces/portal/src/app/components/confirmation-dialog/confirmation-dialog.component.ts
  interfaces/portal/src/app/pages/project-payment/components/single-payment-export/single-payment-export.component.ts
  interfaces/portal/src/app/pages/project-payments/components/export-payments/export-payments.component.ts
  interfaces/portal/src/app/pages/project-registrations/components/export-registrations/export-registrations.component.ts
  interfaces/portal/src/app/services/tracking.service.ts
Labels: enhancement

#7020 chore: try sharding E2E tests
  .github/workflows/test_e2e_portal.yml
  e2e/portal/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusCompleted.spec.ts
  e2e/portal/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusDeclined.spec.ts
  e2e/portal/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusIncluded.spec.ts
  e2e/portal/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusNew.spec.ts
  e2e/portal/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusPaused.spec.ts
  e2e/portal/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusValidated.spec.ts
  e2e/portal/tests/ChangeRegistrationStatus/MovePasFromCompletedToDeclined.spec.ts
  e2e/portal/tests/ChangeRegistrationStatus/MovePasFromCompletedToIncluded.spec.ts
  e2e/portal/tests/ChangeRegistrationStatus/MovePasFromDeclinedToIncluded.spec.ts
  e2e/portal/tests/ChangeRegistrationStatus/MovePasFromIncludedToCompleted.spec.ts
  e2e/portal/tests/ChangeRegistrationStatus/MovePasFromIncludedToDeclined.spec.ts
  e2e/portal/tests/ChangeRegistrationStatus/MovePasFromIncludedToPaused.spec.ts
  e2e/portal/tests/EditRegistration/EditRegistration.spec.ts
  e2e/portal/tests/EditRegistration/EditRegistrationFsp.spec.ts
  e2e/portal/tests/ViewFilterAndSortRegistrations/DeselectAfterChangingFilterChange.spec.ts
  e2e/portal/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByDate.spec.ts
  e2e/portal/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByDropdownSelection.spec.ts
  e2e/portal/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByFsp.spec.ts
  e2e/portal/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByNumberInput.spec.ts
  e2e/portal/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByText.spec.ts
Labels: chore

#7030 docs: Be more explicit about uuid-versions in explanations/examples
  services/.env.example
Labels: ignore-for-release, chore

#7019 chore: revert combined coverage in CI + shard integration tests
  .github/workflows/test_e2e_portal.yml
  .github/workflows/test_service_api.yml
  .github/workflows/test_service_check_migrations.yml
  .github/workflows/test_service_static_checks.yml
  services/121-service/README.md
Labels: chore

#7042 Cleanup k6 tests
  k6/tests/payment100kRegistrationIntersolveVisa.js
  k6/tests/payment100kRegistrationOCW.js
  k6/tests/payment100kRegistrationOnafriq.js
  k6/tests/payment100kRegistrationSafaricom.js
Labels: chore

#7034 Log cronjob results to Azure
  services/121-service/module-dependencies.md
  services/121-service/src/cronjob/cronjob.controller.ts
  services/121-service/src/cronjob/cronjob.module.ts
  services/121-service/src/cronjob/interfaces/cronjob-results.interface.ts
  services/121-service/src/cronjob/services/cronjob-execution-helper.service.spec.ts
  services/121-service/src/cronjob/services/cronjob-execution-helper.service.ts
  services/121-service/src/cronjob/services/cronjob-execution.service.ts
  services/121-service/src/cronjob/services/cronjob-initiate.service.spec.ts
  services/121-service/src/cronjob/services/cronjob-initiate.service.ts
  services/121-service/src/cronjob/types/cronjob-execution-method-name.type.ts
  services/121-service/src/exchange-rates/exchange-rates.controller.ts
  services/121-service/src/exchange-rates/exchange-rates.service.ts
  services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.service.ts
  services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.controller.ts
  services/121-service/src/payments/fsp-integration/intersolve-voucher/services/intersolve-voucher-cron.service.ts
  services/121-service/src/payments/reconciliation/commercial-bank-ethiopia-reconciliation/commercial-bank-ethiopia-reconciliation.controller.ts
  services/121-service/src/payments/reconciliation/commercial-bank-ethiopia-reconciliation/commercial-bank-ethiopia-reconciliation.module.ts
  services/121-service/src/payments/reconciliation/commercial-bank-ethiopia-reconciliation/commercial-bank-ethiopia-reconciliation.service.ts
  services/121-service/src/payments/reconciliation/intersolve-visa-reconciliation/intersolve-visa-reconciliation.controller.ts
  services/121-service/src/payments/reconciliation/intersolve-visa-reconciliation/intersolve-visa-reconciliation.module.ts
  services/121-service/src/payments/reconciliation/intersolve-visa-reconciliation/intersolve-visa-reconciliation.service.ts
  services/121-service/src/payments/reconciliation/intersolve-voucher-reconciliation/intersolve-voucher-reconciliation.module.ts
  services/121-service/src/payments/reconciliation/intersolve-voucher-reconciliation/intersolve-voucher-reconciliation.service.ts
  services/121-service/src/payments/reconciliation/nedbank-reconciliation/nedbank-reconciliation.controller.ts
  services/121-service/src/payments/reconciliation/nedbank-reconciliation/nedbank-reconciliation.module.ts
  services/121-service/src/payments/reconciliation/nedbank-reconciliation/nedbank-reconciliation.service.ts
  services/121-service/src/shared/services/azure-log.service.ts
  services/121-service/swagger.json
  services/121-service/test/cronjob/cronjobs.test.ts
  services/121-service/test/helpers/intersolve-voucher.helper.ts
  services/121-service/test/helpers/organization.helper.ts
  services/121-service/test/helpers/program.helper.ts
  services/121-service/test/helpers/utility.helper.ts
  services/121-service/test/voucher/delete-deprecated-vouchers.test.ts
Labels: chore

#7051 chore: also workaround onafriq sandbox cert error on test
  services/121-service/src/config.ts
  services/121-service/src/payments/fsp-integration/onafriq/services/onafriq.api.service.ts
Labels: chore

#7023 feat: generate onafriq reconcilation report AB#37169
  services/.env.example
  services/121-service/.gitignore
  services/121-service/cert/REDCROSSDRCsftpp.pub.example
  services/121-service/module-dependencies.md
  services/121-service/package-lock.json
  services/121-service/package.json
  services/121-service/src/cronjob/cronjob.controller.ts
  services/121-service/src/cronjob/cronjob.module.ts
  services/121-service/src/cronjob/services/cronjob-execution.service.ts
  services/121-service/src/cronjob/services/cronjob-initiate.service.ts
  services/121-service/src/env.ts
  services/121-service/src/migration/1751976748859-OnafriqReconciliationReport.ts
  services/121-service/src/payments/fsp-integration/onafriq/dtos/onafriq-api/onafriq-api-call-service-request-body.dto.ts
  services/121-service/src/payments/fsp-integration/onafriq/entities/onafriq-transaction.entity.ts
  services/121-service/src/payments/fsp-integration/onafriq/services/onafriq.api.helper.service.ts
  services/121-service/src/payments/reconciliation/onafriq-reconciliation/dtos/onafriq-transaction-callback-job.dto.ts
  services/121-service/src/payments/reconciliation/onafriq-reconciliation/dtos/onafriq-transaction-callback.dto.ts
  services/121-service/src/payments/reconciliation/onafriq-reconciliation/interfaces/onafriq-reconciliation-report.interface.ts
  services/121-service/src/payments/reconciliation/onafriq-reconciliation/onafriq-reconciliation.controller.ts
  services/121-service/src/payments/reconciliation/onafriq-reconciliation/onafriq-reconciliation.mapper.ts
  services/121-service/src/payments/reconciliation/onafriq-reconciliation/onafriq-reconciliation.service.ts
  services/121-service/src/transaction-jobs/services/transaction-jobs-onafriq.service.ts
  services/121-service/swagger.json
  services/121-service/test/onafriq/export-reconciliation-report.test.ts
  services/mock-service/src/fsp-integration/onafriq/onafriq.dto.ts
  services/mock-service/src/fsp-integration/onafriq/onafriq.mock.service.ts
Labels: enhancement

#7024 feat: pass visibleColumns to select query AB#37154
  e2e/portal/tests/ExportRegistrations/ExportHighVolumeOfRegistrations.spec.ts
  e2e/portal/tests/ExportRegistrations/ExportRegistrationsList.spec.ts
  e2e/portal/tests/__screenshots__/ExportRegistrations/ExportHighVolumeOfRegistrations.spec.ts/exported-xlsx.csv
  e2e/portal/tests/__screenshots__/ExportRegistrations/ExportRegistrationsList.spec.ts/exported-csv.csv
  e2e/portal/tests/__screenshots__/ExportRegistrations/ExportRegistrationsList.spec.ts/exported-xlsx.csv
  interfaces/portal/src/app/components/query-table/query-table.component.ts
  interfaces/portal/src/app/services/paginate-query.service.ts
  services/121-service/src/metrics/metrics.service.ts
Labels: enhancement

#7050 ci: Make the path-filter external-action only run on PRs, to prevent confusing errors
  .github/workflows/test_e2e_portal.yml
  .github/workflows/test_service_api.yml
Labels: ignore-for-release, chore

#7025 refactor: Remove the extraneous volumes that require double installs of dependencies
  .github/workflows/test_e2e_portal.yml
  services/docker-compose.development.yml
Labels: ignore-for-release, chore

#7063 chore: upgrade angular + primeng v20
  e2e/portal/components/TableComponent.ts
  interfaces/portal/angular.json
  interfaces/portal/package-lock.json
  interfaces/portal/package.json
  interfaces/portal/src/app/app.config.ts
  interfaces/portal/src/app/app.theme.ts
  interfaces/portal/src/app/components/query-table/query-table.component.html
  interfaces/portal/src/app/pages/project-monitoring/components/monitoring-iframe/monitoring-iframe.component.ts
  interfaces/portal/src/app/pages/project-registration-debit-cards/project-registration-debit-cards.page.ts
  interfaces/portal/src/app/pages/projects-overview/components/create-project-form/create-project-form.component.ts
  interfaces/portal/src/app/pages/projects-overview/projects-overview.page.ts
  interfaces/portal/src/app/services/rtl-helper.service.ts
  interfaces/portal/src/styles.scss
Labels: chore

#7069 chore: report coverage on all files
  interfaces/portal/karma.conf.js
  services/121-service/jest.integration.config.js
  services/121-service/jest.unit.config.js
Labels: chore

#7071 test: add deletion to bulk update test
  e2e/portal/tests/UpdateRegistrations/BulkUpdateVisibleInActivityLog.spec.ts
Labels: chore

#7074 feat: add scope column to registrations table
  e2e/portal/tests/ExportRegistrations/ExportRegistrationsList.spec.ts
  e2e/portal/tests/__screenshots__/ExportRegistrations/ExportRegistrationsList.spec.ts/exported-registrations-xlsx.csv
  e2e/portal/tests/__screenshots__/ExportRegistrations/ExportRegistrationsList.spec.ts/exported-registrations.csv
  e2e/portal/tests/__screenshots__/ExportRegistrations/ExportRegistrationsList.spec.ts/exported-selected-columns-xlsx.csv
  e2e/portal/tests/__screenshots__/ExportRegistrations/ExportRegistrationsList.spec.ts/exported-selected-columns.csv
  interfaces/portal/src/app/components/query-table/query-table.component.ts
  interfaces/portal/src/app/services/registrations-table-column.service.ts
Labels: enhancement

#7077 fix: layout issue on file uploads
  interfaces/portal/src/app/app.theme.ts
Labels: bugfix

#7055 Fix update program
  services/121-service/src/programs/dto/update-program.dto.ts
Labels: bugfix

#7081 other: remove latest export date component
  interfaces/portal/src/app/domains/project/project.api.service.ts
  interfaces/portal/src/app/pages/project-payment/components/single-payment-export/single-payment-export.component.html
  interfaces/portal/src/app/pages/project-payment/components/single-payment-export/single-payment-export.component.ts
  interfaces/portal/src/app/pages/project-payments/components/export-payments/export-payments.component.html
  interfaces/portal/src/app/pages/project-payments/components/export-payments/export-payments.component.ts
  interfaces/portal/src/app/pages/project-registrations/components/export-registrations/export-registrations.component.html
  interfaces/portal/src/app/pages/project-registrations/components/export-registrations/export-registrations.component.ts
  interfaces/portal/src/app/pages/project-registrations/components/latest-export-date/latest-export-date.component.html
  interfaces/portal/src/app/pages/project-registrations/components/latest-export-date/latest-export-date.component.ts
  interfaces/portal/src/locale/messages.xlf
  services/121-service/src/actions/actions.controller.ts
  services/121-service/src/actions/actions.module.ts
  services/121-service/src/actions/dto/action.dto.ts
  services/121-service/swagger.json
Labels: other

#7054 feat: export payments with date range
  e2e/portal/tests/ViewPayment/ExportPaymentReport.spec.ts
  e2e/portal/tests/ViewPayments/ExportPayments.spec.ts
  e2e/portal/tests/__screenshots__/ViewPayment/ExportPaymentReport.spec.ts/exported-xlsx.csv
  e2e/portal/tests/__screenshots__/ViewPayments/ExportPayments.spec.ts/exported-xlsx.csv
  interfaces/portal/src/app/domains/project/project.api.service.ts
  interfaces/portal/src/app/pages/project-payment/components/single-payment-export/single-payment-export.component.html
  interfaces/portal/src/app/pages/project-payment/components/single-payment-export/single-payment-export.component.ts
  interfaces/portal/src/app/pages/project-payments/components/export-payments/export-payments.component.html
  interfaces/portal/src/app/pages/project-payments/components/export-payments/export-payments.component.ts
  interfaces/portal/src/app/services/export.service.ts
  interfaces/portal/src/locale/messages.xlf
Labels: enhancement
