Repository global-121/121-platform, pull requests merged in 2025-10, with the labels that each got.

#7314 attempt to fix tests
  e2e/portal/tests/ProfilePageActivityLog/ExpandRowsOfActivityOverview.spec.ts
  services/121-service/test/payment/__snapshots__/do-payment-fsp-voucher.test.ts.snap
  services/121-service/test/payment/do-payment-fsp-voucher.test.ts
Labels: bugfix

#7316 native dashboard - post merge cleanup
  services/121-service/src/metrics/metrics.service.ts
  services/121-service/src/utils/dateSort.ts
  services/121-service/src/utils/to-type.helper.ts
Labels: chore

#7335 Delete pending message entity before sending it
  services/121-service/src/notifications/services/message.service.ts
Labels: bugfix

#7341 Allow AWS connect iframe for staging and test
  .github/workflows/deploy_staging_portal.yml
  .github/workflows/deploy_test_portal.yml
  interfaces/portal/.env.example
  interfaces/portal/_build-deployment-configuration.mjs
  interfaces/portal/_test-deployment-configuration.mjs
  interfaces/portal/_verify-deployment-configuration.mjs
Labels: enhancement

#7339 Fix query size eror on very large payments and enable related k6 test
  k6/run-all-tests.sh
  services/121-service/src/payments/services/payments-execution.service.ts
  services/121-service/src/payments/services/transaction-jobs-creation.service.ts
  services/121-service/src/registration/services/registrations-bulk.service.ts
Labels: bugfix

#7286 Yuri/send message to new registrations
  e2e/portal/tests/ProfilePageActivityLog/ExpandRowsOfActivityOverview.spec.ts
  interfaces/portal/src/app/domains/message/message.helper.ts
  interfaces/portal/src/locale/messages.xlf
  services/121-service/module-dependencies.md
  services/121-service/src/notifications/enum/message-type.enum.ts
  services/121-service/src/notifications/message-template/message-template.service.ts
  services/121-service/src/registration/registrations.module.ts
  services/121-service/src/registration/repositories/registration-view-scoped.repository.ts
  services/121-service/src/registration/services/registrations-bulk.service.ts
  services/121-service/src/registration/services/registrations-import.service.ts
  services/121-service/src/seed-data/message-template/demo-message-template-mobile-money.const.ts
  services/121-service/src/seed-data/message-template/message-template-generic.const.ts
  services/121-service/src/seed-data/message-template/message-template-nlrc-ocw.const.ts
  services/121-service/src/seed-data/message-template/message-template-nlrc-pv.const.ts
  services/121-service/test/helpers/program.helper.ts
  services/121-service/test/metrics/__snapshots__/export-list.test.ts.snap
  services/121-service/test/metrics/export-list.test.ts
  services/121-service/test/payment/__snapshots__/do-payment-fsp-voucher.test.ts.snap
  services/121-service/test/payment/do-payment-fsp-visa-debit/do-payment-fsp-visa-debit.success.test.ts
  services/121-service/test/payment/do-payment-fsp-voucher.test.ts
  services/121-service/test/registrations/bulk-update-registration.test.ts
  services/121-service/test/registrations/import-registration.test.ts
  services/121-service/test/registrations/pagination/send-message.test.ts
Labels: enhancement

#7352 DB errors during deployment
  README.md
Labels: chore

#7293 chore: refactor project forms
  interfaces/portal/src/app/components/import-file-dialog/import-file-dialog.component.ts
  interfaces/portal/src/app/components/page-layout-registration/components/add-note-dialog/add-note-dialog.component.ts
  interfaces/portal/src/app/components/page-layout-registration/components/ignore-duplicates-dialog/ignore-duplication-dialog.component.ts
  interfaces/portal/src/app/components/project-form-budget/project-form-budget.component.html
  interfaces/portal/src/app/components/project-form-budget/project-form-budget.component.ts
  interfaces/portal/src/app/components/project-form-information/project-form-information.component.html
  interfaces/portal/src/app/components/project-form-information/project-form-information.component.ts
  interfaces/portal/src/app/components/project-form-name/project-form-name.component.html
  interfaces/portal/src/app/components/project-form-name/project-form-name.component.ts
  interfaces/portal/src/app/domains/project/project.helper.ts
  interfaces/portal/src/app/pages/project-monitoring-files/components/monitoring-upload-file-dialog/monitoring-upload-file-dialog.component.ts
  interfaces/portal/src/app/pages/project-monitoring-files/project-monitoring-files.page.ts
  interfaces/portal/src/app/pages/project-registration-personal-information/components/edit-personal-information/edit-personal-information.component.ts
  interfaces/portal/src/app/pages/project-registrations/components/send-message-dialog/send-message-dialog.component.ts
  interfaces/portal/src/app/pages/project-registrations/components/update-registrations/update-registrations.component.ts
  interfaces/portal/src/app/pages/project-settings-information/components/project-settings-basic-information/project-settings-basic-information.component.html
  interfaces/portal/src/app/pages/project-settings-information/components/project-settings-basic-information/project-settings-basic-information.component.ts
  interfaces/portal/src/app/pages/project-settings-information/components/project-settings-budget/project-settings-budget.component.html
  interfaces/portal/src/app/pages/project-settings-information/components/project-settings-budget/project-settings-budget.component.ts
  interfaces/portal/src/app/pages/project-settings-team/components/add-project-team-user-dialog/add-project-team-user-dialog.component.ts
  interfaces/portal/src/app/pages/projects-overview/components/create-project-dialog/create-project-dialog.component.ts
  interfaces/portal/src/app/pages/users/components/add-user-dialog/add-user-dialog.component.ts
  interfaces/portal/src/app/utils/form-validation.ts
  interfaces/portal/src/locale/messages.xlf
Labels: chore

#7312 feat: Make syntax-issues less 'loud' in editor (when auto-fixable)
  .vscode/settings.json
  e2e/.vscode/settings.json
  interfaces/portal/.vscode/settings.json
  services/121-service/.vscode/settings.json
  services/mock-service/.vscode/settings.json
Labels: ignore-for-release, chore

#7294 refactor: Use built-in utilities for proper argument-handling (and future-proofing)
  .github/workflows/test_interface_portal.yml
  interfaces/portal/_set-env-variables.mjs
  interfaces/portal/_verify-deployment-configuration.mjs
  interfaces/portal/package.json
Labels: ignore-for-release, chore

#7311 feat: Add "Cloud Role name" to all telemetry of the Portal
  interfaces/portal/src/app/services/log.service.ts
Labels: chore

#7364 chore: prevent quirky undefined behaviour in FormControls
  interfaces/portal/eslint-rules/no-form-control-undefined-value.js
  interfaces/portal/eslint.config.mjs
  interfaces/portal/src/app/components/project-form-budget/project-form-budget.component.ts
  interfaces/portal/src/app/components/project-form-information/project-form-information.component.ts
  interfaces/portal/src/app/components/project-form-name/project-form-name.component.ts
  interfaces/portal/src/app/pages/project-payments/components/export-payments/export-payments.component.ts
  interfaces/portal/src/app/pages/project-registrations/components/change-status-contents-with-custom-message/change-status-contents-with-custom-message.component.ts
  interfaces/portal/src/app/pages/project-registrations/components/export-registrations/export-registrations.component.ts
  interfaces/portal/src/app/pages/project-registrations/components/send-message-dialog/send-message-dialog.component.ts
Labels: chore
