Repository global-121/121-platform, pull requests merged in 2025-08, with the labels that each got.

#7084 chore: refactor export service
  e2e/portal/tests/ViewPayments/ExportPayments.spec.ts
  e2e/portal/tests/__screenshots__/ViewPayments/ExportPayments.spec.ts/exported-xlsx.csv
  interfaces/portal/src/app/pages/project-payment/components/single-payment-export/single-payment-export.component.html
  interfaces/portal/src/app/pages/project-payment/components/single-payment-export/single-payment-export.component.ts
  interfaces/portal/src/app/pages/project-payments/components/create-payment/create-payment.component.ts
  interfaces/portal/src/app/pages/project-payments/components/export-payments/export-payments.component.html
  interfaces/portal/src/app/pages/project-payments/components/export-payments/export-payments.component.ts
  interfaces/portal/src/app/pages/project-registrations/components/export-registrations/export-registrations.component.html
  interfaces/portal/src/app/pages/project-registrations/components/export-registrations/export-registrations.component.ts
  interfaces/portal/src/app/pages/project-registrations/components/update-registrations/update-registrations.component.ts
  interfaces/portal/src/app/services/export.service.ts
  interfaces/portal/src/locale/messages.xlf
  services/121-service/src/metrics/dto/export-details.dto.ts
  services/121-service/src/metrics/metrics.controller.ts
  services/121-service/src/payments/payments.controller.ts
  services/121-service/src/registration/repositories/registration-scoped.repository.spec.ts
Labels: chore

#7104 Do not throw an error on twilio error code 21211 'to number does not exist'
  services/121-service/src/notifications/enum/twilio-error-codes.enum.ts
  services/121-service/src/notifications/message-incoming/message-incoming.service.ts
  services/121-service/src/notifications/sms/sms.service.ts
  services/121-service/src/notifications/whatsapp/whatsapp.service.ts
  services/121-service/test/registrations/pagination/send-message.test.ts
  services/mock-service/src/twilio/twilio.service.ts
Labels: bugfix

#7108 Validate export type in export list endpoint
  services/121-service/src/metrics/metrics.controller.ts
  services/121-service/test/metrics/export-list.test.ts
Labels: bugfix

#7110 chore: fix flaky export payments test
  e2e/portal/components/ExportData.ts
  e2e/portal/pages/BasePage.ts
  e2e/portal/tests/ViewPayments/ExportPayments.spec.ts
  e2e/portal/tests/__screenshots__/ViewPayments/ExportPayments.spec.ts/exported-xlsx.csv
  services/121-service/src/programs/program-attachments/program-attachments.service.ts
Labels: chore

#7076 feat: upload files on a project level
  e2e/portal/helpers/largeFileGenerator.ts
  e2e/portal/pages/ProjectMonitoringPage.ts
  e2e/portal/tests/ProjectLevelAttachments/AddAttachmentsOnProjectLevel.spec.ts
  e2e/portal/tests/ProjectLevelAttachments/DeleteAttachment.spec.ts
  e2e/portal/tests/ProjectLevelAttachments/DownloadAttachment.spec.ts
  e2e/portal/tests/__screenshots__/ProjectLevelAttachments/DownloadAttachment.spec.ts/Test-TEST-DOCUMENT-file-upload.pdf
  e2e/test-file-upload-data/test-document.docx
  e2e/test-file-upload-data/test-document.pdf
  e2e/test-file-upload-data/test-image.png
  e2e/test-file-upload-data/test-photo.jpg
  e2e/test-file-upload-data/wrong-file-format.pages
  interfaces/portal/src/app/app.routes.ts
  interfaces/portal/src/app/components/monitoring-page-layout/components/monitoring-menu/monitoring-menu.component.ts
  interfaces/portal/src/app/components/monitoring-page-layout/monitoring-page-layout.component.html
  interfaces/portal/src/app/components/registration-page-layout/registration-page-layout.component.html
  interfaces/portal/src/app/domains/project/project.api.service.ts
  interfaces/portal/src/app/domains/project/project.helper.ts
  interfaces/portal/src/app/domains/project/project.model.ts
  interfaces/portal/src/app/pages/project-monitoring-files/components/monitoring-upload-file-dialog/monitoring-upload-file-dialog.component.html
  interfaces/portal/src/app/pages/project-monitoring-files/components/monitoring-upload-file-dialog/monitoring-upload-file-dialog.component.ts
  interfaces/portal/src/app/pages/project-monitoring-files/components/table-cell-file-type.component.ts
  interfaces/portal/src/app/pages/project-monitoring-files/project-monitoring-files.page.html
  interfaces/portal/src/app/pages/project-monitoring-files/project-monitoring-files.page.ts
  interfaces/portal/src/app/pages/project-registration-activity-log/project-registration-activity-log.page.ts
  interfaces/portal/src/app/utils/unique-users.ts
  interfaces/portal/src/locale/messages.xlf
Labels: enhancement

#7114 other: upgrade to tailwind v4
  interfaces/portal/.postcssrc.json
  interfaces/portal/angular.json
  interfaces/portal/eslint.config.mjs
  interfaces/portal/package-lock.json
  interfaces/portal/package.json
  interfaces/portal/src/app/app.config.ts
  interfaces/portal/src/app/app.theme.ts
  interfaces/portal/src/app/components/card-summary-metrics-container/card-summary-metrics-container.component.html
  interfaces/portal/src/app/components/card-with-link/card-with-link.component.html
  interfaces/portal/src/app/components/data-list/data-list.component.html
  interfaces/portal/src/app/components/file-upload-control/file-upload-control.component.html
  interfaces/portal/src/app/components/form/form-sidebar.component.html
  interfaces/portal/src/app/components/import-file-dialog/import-file-dialog.component.html
  interfaces/portal/src/app/components/logo/logo.component.html
  interfaces/portal/src/app/components/metric-container/metric-container.component.html
  interfaces/portal/src/app/components/metric-tile/metric-tile.component.html
  interfaces/portal/src/app/components/monitoring-page-layout/monitoring-page-layout.component.html
  interfaces/portal/src/app/components/page-layout/components/footer/footer.component.html
  interfaces/portal/src/app/components/page-layout/components/header/header.component.html
  interfaces/portal/src/app/components/page-layout/components/project-menu/project-menu.component.html
  interfaces/portal/src/app/components/page-layout/components/registration-lookup-menu/registration-lookup-menu.component.html
  interfaces/portal/src/app/components/page-layout/page-layout.component.html
  interfaces/portal/src/app/components/query-table/components/query-table-column-management/query-table-column-management.component.html
  interfaces/portal/src/app/components/query-table/components/query-table-global-search/query-table-global-search.component.html
  interfaces/portal/src/app/components/query-table/query-table.component.html
  interfaces/portal/src/app/components/registration-page-layout/registration-page-layout.component.html
  interfaces/portal/src/app/components/registrations-table/registrations-table.component.html
  interfaces/portal/src/app/pages/login/login.page.html
  interfaces/portal/src/app/pages/privacy/privacy.page.html
  interfaces/portal/src/app/pages/project-monitoring-powerbi/project-monitoring-powerbi.page.html
  interfaces/portal/src/app/pages/project-payment/components/project-payment-chart/project-payment-chart.component.ts
  interfaces/portal/src/app/pages/project-payment/project-payment.page.html
  interfaces/portal/src/app/pages/project-payments/components/create-payment/create-payment.component.html
  interfaces/portal/src/app/pages/project-registration-activity-log/components/activity-log-voucher-dialog/activity-log-voucher-dialog.component.html
  interfaces/portal/src/app/pages/project-registration-personal-information/components/edit-personal-information/edit-personal-information.component.html
  interfaces/portal/src/app/pages/project-registrations/components/custom-message-control/custom-message-control.component.html
  interfaces/portal/src/app/pages/project-registrations/components/custom-message-preview/custom-message-preview.component.html
  interfaces/portal/src/app/pages/project-registrations/components/update-registrations/update-registrations.component.html
  interfaces/portal/src/app/utils/chart.ts
  interfaces/portal/src/app/utils/tailwind.ts
  interfaces/portal/src/styles.css
  interfaces/portal/tailwind.config.ts
Labels: other

#7113 Add GET endpoint for visible FspConfig properties
  services/121-service/src/fsps/enums/fsp-name.enum.ts
  services/121-service/src/program-fsp-configurations/dtos/program-fsp-configuration-property-response.dto.ts
  services/121-service/src/program-fsp-configurations/mappers/program-fsp-configuration.mapper.ts
  services/121-service/src/program-fsp-configurations/program-fsp-configurations.controller.ts
  services/121-service/src/program-fsp-configurations/program-fsp-configurations.service.ts
  services/121-service/swagger.json
  services/121-service/test/helpers/program-fsp-configuration.helper.ts
  services/121-service/test/program/manage-program-fsp-configuration.test.ts
Labels: enhancement

#7128 Fix: hidden properties still vissible on /api/programs/{programId}/fsp-configurations
  services/121-service/src/program-fsp-configurations/mappers/program-fsp-configuration.mapper.ts
  services/121-service/src/program-fsp-configurations/program-fsp-configurations.controller.ts
  services/121-service/src/program-fsp-configurations/program-fsp-configurations.service.ts
  services/121-service/test/program/manage-program-fsp-configuration.test.ts
Labels: bugfix

#7134 other: add subpages to payment details
  interfaces/portal/src/app/app.routes.ts
  interfaces/portal/src/app/components/page-layout-monitoring/components/monitoring-menu/monitoring-menu.component.html
  interfaces/portal/src/app/components/page-layout-monitoring/components/monitoring-menu/monitoring-menu.component.ts
  interfaces/portal/src/app/components/page-layout-monitoring/page-layout-monitoring.component.html
  interfaces/portal/src/app/components/page-layout-monitoring/page-layout-monitoring.component.ts
  interfaces/portal/src/app/components/page-layout-payment/components/import-reconciliation-data/import-reconciliation-data.component.html
  interfaces/portal/src/app/components/page-layout-payment/components/import-reconciliation-data/import-reconciliation-data.component.ts
  interfaces/portal/src/app/components/page-layout-payment/components/payment-menu/payment-menu.component.html
  interfaces/portal/src/app/components/page-layout-payment/components/payment-menu/payment-menu.component.ts
  interfaces/portal/src/app/components/page-layout-payment/components/project-payment-chart/project-payment-chart.component.html
  interfaces/portal/src/app/components/page-layout-payment/components/project-payment-chart/project-payment-chart.component.ts
  interfaces/portal/src/app/components/page-layout-payment/components/single-payment-export/single-payment-export.component.html
  interfaces/portal/src/app/components/page-layout-payment/components/single-payment-export/single-payment-export.component.ts
  interfaces/portal/src/app/components/page-layout-payment/page-layout-payment.component.html
  interfaces/portal/src/app/components/page-layout-payment/page-layout-payment.component.ts
  interfaces/portal/src/app/components/page-layout-registration/components/add-note-form/add-note-form.component.html
  interfaces/portal/src/app/components/page-layout-registration/components/add-note-form/add-note-form.component.ts
  interfaces/portal/src/app/components/page-layout-registration/components/ignore-duplicates-dialog/ignore-duplication-dialog.component.html
  interfaces/portal/src/app/components/page-layout-registration/components/ignore-duplicates-dialog/ignore-duplication-dialog.component.ts
  interfaces/portal/src/app/components/page-layout-registration/components/registration-duplicates-banner/registration-duplicates-banner.component.html
  interfaces/portal/src/app/components/page-layout-registration/components/registration-duplicates-banner/registration-duplicates-banner.component.ts
  interfaces/portal/src/app/components/page-layout-registration/components/registration-menu/registration-menu.component.html
  interfaces/portal/src/app/components/page-layout-registration/components/registration-menu/registration-menu.component.ts
  interfaces/portal/src/app/components/page-layout-registration/page-layout-registration.component.html
  interfaces/portal/src/app/components/page-layout-registration/page-layout-registration.component.ts
  interfaces/portal/src/app/pages/project-monitoring-files/project-monitoring-files.page.html
  interfaces/portal/src/app/pages/project-monitoring-files/project-monitoring-files.page.ts
  interfaces/portal/src/app/pages/project-monitoring-powerbi/project-monitoring-powerbi.page.html
  interfaces/portal/src/app/pages/project-monitoring-powerbi/project-monitoring-powerbi.page.ts
  interfaces/portal/src/app/pages/project-payment-transfer-list/components/retry-transfers-dialog/retry-transfers-dialog.component.html
  interfaces/portal/src/app/pages/project-payment-transfer-list/components/retry-transfers-dialog/retry-transfers-dialog.component.ts
  interfaces/portal/src/app/pages/project-payment-transfer-list/project-payment-transfer-list.page.html
  interfaces/portal/src/app/pages/project-payment-transfer-list/project-payment-transfer-list.page.ts
  interfaces/portal/src/app/pages/project-registration-activity-log/components/table-cell-overview/table-cell-overview.component.ts
  interfaces/portal/src/app/pages/project-registration-activity-log/project-registration-activity-log.page.html
  interfaces/portal/src/app/pages/project-registration-activity-log/project-registration-activity-log.page.ts
  interfaces/portal/src/app/pages/project-registration-debit-cards/project-registration-debit-cards.page.html
  interfaces/portal/src/app/pages/project-registration-debit-cards/project-registration-debit-cards.page.ts
  interfaces/portal/src/app/pages/project-registration-personal-information/project-registration-personal-information.page.html
  interfaces/portal/src/app/pages/project-registration-personal-information/project-registration-personal-information.page.ts
  interfaces/portal/src/locale/messages.xlf
Labels: other

#7140 Do not create unneeded internal server error when the issue is in kobo-connect
  services/121-service/src/kobo-connect/kobo-connect.api.service.ts
  services/121-service/src/kobo-connect/kobo-connect.service.ts
  services/121-service/src/programs/programs.service.ts
Labels: bugfix

#7148 feat: Airtel - add (static) payee.name in payload
  services/121-service/src/payments/fsp-integration/airtel/dtos/airtel-api-disbursement-request-body.dto.ts
  services/121-service/src/payments/fsp-integration/airtel/services/__snapshots__/airtel.api.service.spec.ts.snap
  services/121-service/src/payments/fsp-integration/airtel/services/airtel.api.service.ts
Labels: enhancement

#7136 Add api tests for intersolve voucher
  services/121-service/test/payment/__snapshots__/do-payment-fsp-voucher.test.ts.snap
  services/121-service/test/payment/do-payment-fsp-voucher.test.ts
Labels: chore

#7150 Fix a migration with faulty fk creation
  services/121-service/src/migration/1754399322187-payment-entity.ts
Labels: bugfix

#7137 adapt logic of which AH vouchers / reminder to send to paymentId refactor
  services/121-service/module-dependencies.md
  services/121-service/src/activities/activities.service.ts
  services/121-service/src/migration/1755852548143-VoucherPaymentRelation.ts
  services/121-service/src/notifications/message-incoming/message-incoming.module.ts
  services/121-service/src/notifications/message-incoming/message-incoming.service.ts
  services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.entity.ts
  services/121-service/src/payments/fsp-integration/intersolve-voucher/services/intersolve-voucher-cron.service.ts
  services/121-service/src/payments/reconciliation/nedbank-reconciliation/nedbank-reconciliation.service.ts
  services/121-service/src/payments/reconciliation/onafriq-reconciliation/onafriq-reconciliation.service.ts
  services/121-service/src/payments/reconciliation/safaricom-reconciliation/safaricom-reconciliation.service.spec.ts
  services/121-service/src/payments/reconciliation/safaricom-reconciliation/safaricom-reconciliation.service.ts
  services/121-service/src/payments/services/payments.service.spec.ts
  services/121-service/src/payments/services/payments.service.ts
  services/121-service/src/payments/transactions/transaction.repository.ts
  services/121-service/src/payments/transactions/transaction.scoped.repository.ts
  services/121-service/src/payments/transactions/transactions.module.ts
  services/121-service/src/payments/transactions/transactions.service.ts
  services/121-service/src/program-fsp-configurations/program-fsp-configurations.service.spec.ts
  services/121-service/src/transaction-jobs/services/transaction-jobs-airtel.service.spec.ts
  services/121-service/src/transaction-jobs/services/transaction-jobs-airtel.service.ts
  services/121-service/src/transaction-jobs/services/transaction-jobs-helper.service.spec.ts
  services/121-service/src/transaction-jobs/services/transaction-jobs-helper.service.ts
  services/121-service/src/transaction-jobs/services/transaction-jobs-nedbank.service.spec.ts
  services/121-service/src/transaction-jobs/services/transaction-jobs-nedbank.service.ts
  services/121-service/src/transaction-jobs/services/transaction-jobs-onafriq.service.spec.ts
  services/121-service/src/transaction-jobs/services/transaction-jobs-onafriq.service.ts
  services/121-service/src/transaction-jobs/services/transaction-jobs-safaricom.service.spec.ts
  services/121-service/src/transaction-jobs/services/transaction-jobs-safaricom.service.ts
Labels: bugfix

#7154 Split up payment service in smaller services
  services/121-service/src/payments/payments.controller.ts
  services/121-service/src/payments/payments.module.ts
  services/121-service/src/payments/services/__snapshots__/payments-reporting.service.spec.ts.snap
  services/121-service/src/payments/services/__snapshots__/payments.service.spec.ts.snap
  services/121-service/src/payments/services/payments-excel-fsp.service.ts
  services/121-service/src/payments/services/payments-execution.service.ts
  services/121-service/src/payments/services/payments-progress.helper.service.ts
  services/121-service/src/payments/services/payments-reporting.helper.service.spec.ts
  services/121-service/src/payments/services/payments-reporting.helper.service.ts
  services/121-service/src/payments/services/payments-reporting.service.spec.ts
  services/121-service/src/payments/services/payments-reporting.service.ts
  services/121-service/src/payments/services/payments.service.ts
  services/121-service/src/payments/services/transaction-jobs-creation.service.ts
Labels: chore
