Repository global-121/121-platform, pull requests merged in 2025-05, with the labels that each got.

#6774 chore: Align all cronjob-methods and responses
  services/121-service/src/exchange-rates/exchange-rates.controller.ts
  services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.controller.ts
  services/121-service/src/payments/reconciliation/commercial-bank-ethiopia-reconciliation/commercial-bank-ethiopia-reconciliation.controller.ts
  services/121-service/src/payments/reconciliation/intersolve-visa-reconciliation/intersolve-visa-reconciliation.controller.ts
  services/121-service/src/payments/reconciliation/intersolve-voucher-reconciliation/intersolve-voucher-reconciliation.controller.ts
  services/121-service/src/reconciliation/nedbank-reconciliation/nedbank-reconciliation.controller.ts
Labels: ignore-for-release, chore

#6790 Reduce downloads of translations via cache-per-day + Disable async-downloading (for now)
  .github/actions/build-interface/action.yml
  .github/workflows/deploy_client-benin_portal.yml
  .github/workflows/deploy_client-demo_portal.yml
  .github/workflows/deploy_client-drc_portal.yml
  .github/workflows/deploy_client-eswatini_portal.yml
  .github/workflows/deploy_client-ethiopia_portal.yml
  .github/workflows/deploy_client-greece_portal.yml
  .github/workflows/deploy_client-ivorycoast_portal.yml
  .github/workflows/deploy_client-jrethiopia_portal.yml
  .github/workflows/deploy_client-krcs_portal.yml
  .github/workflows/deploy_client-nigeria_portal.yml
  .github/workflows/deploy_client-nlrc_portalicious.yml
  .github/workflows/deploy_client-slovakia_portal.yml
  .github/workflows/deploy_client-somalia_portal.yml
  .github/workflows/deploy_client-southafrica_portal.yml
  .github/workflows/deploy_client-sudan_portal.yml
  .github/workflows/deploy_client-togo_portal.yml
  .github/workflows/deploy_client-training_portal.yml
  .github/workflows/deploy_client-zambia_portal.yml
  .github/workflows/deploy_staging_portalicious.yml
  .github/workflows/deploy_test_portalicious.yml
  .github/workflows/test_e2e_portalicious.yml
  interfaces/Portalicious/_build-download-translations.mjs
Labels: ignore-for-release, chore

#6797 feat: Merge/upgrade Test/Staging Portal(s)
  .github/workflows/deploy_staging_all.yml
  .github/workflows/deploy_staging_portal.yml
  .github/workflows/deploy_staging_portalicious.yml
  .github/workflows/deploy_test_all.yml
  .github/workflows/deploy_test_portal.yml
  .github/workflows/deploy_test_portalicious.yml
Labels: chore

#6767 docs: Improve README/config for readability/ease-of-use, consistent use of PA/Registration/FSP terms
  README.md
  e2e/.vscode/settings.json
  e2e/README.md
  e2e/playwright.config.ts
  package.json
  services/121-service/README.md
Labels: ignore-for-release, chore

#6789 test: Add e2e-tests for Redline-features
  e2e/portalicious/tests/Redline/ViewRegistrationPageInRedline.spec.ts
Labels: chore

#6811 ci: Add package.json to make local ESLint-plugin install in Dependabot
  services/121-service/eslint-plugin-custom-rules/package.json
Labels: dependencies, ignore-for-release

#6820 chore: an homage
  interfaces/Portalicious/src/app/utils/local-storage.ts
Labels: chore

#6822 chore: Upgrade/specify dependencies for root-tasks/scripts
  .github/dependabot.yml
  .nvmrc
  interfaces/.nvmrc
  package-lock.json
  package.json
  services/121-service/.nvmrc
Labels: dependencies, ignore-for-release, chore

#6832 View users as organization admin
  services/121-service/src/user/user.controller.ts
Labels: bugfix

#6835 Fix organisation admin for azure ad
  services/121-service/src/strategies/azure-ad.strategy.ts
Labels: bugfix

#6834 chore: remove 121-service endpoints that were only used in old portal
  services/121-service/src/events/events.controller.ts
  services/121-service/src/metrics/dto/payment-state-sum.dto.ts
  services/121-service/src/metrics/dto/registrationstatus-stats.dto.ts
  services/121-service/src/metrics/metrics.controller.ts
  services/121-service/src/metrics/metrics.service.ts
  services/121-service/src/notes/dto/create-note.dto.ts
  services/121-service/src/notes/dto/response-note.dto.ts
  services/121-service/src/notes/notes.controller.ts
  services/121-service/src/notes/notes.service.ts
  services/121-service/src/registration/registrations.controller.ts
  services/121-service/src/registration/registrations.service.ts
  services/121-service/swagger.json
  services/121-service/test/event/filter-events.test.ts
  services/121-service/test/helpers/program.helper.ts
  services/121-service/test/helpers/registration.helper.ts
  services/121-service/test/program/notes.test.ts
Labels: chore

#6810 chore: add missing properties to new transactions endpoint
  services/121-service/src/payments/dto/transaction-response.dto.ts
  services/121-service/src/payments/payments.service.spec.ts
  services/121-service/src/payments/transactions/transaction.repository.ts
  services/121-service/test/program/manage-program-financial-service-provider-configuration.test.ts
  services/121-service/test/registrations/update-registration-program-financial-service-provider-configuration.test.ts
  services/121-service/test/transactions/get-transactions.test.ts
Labels: chore

#6831 Clear selection after applying a filter
  e2e/portalicious/components/TableComponent.ts
  e2e/portalicious/tests/ViewFilterAndSortRegistrations/DeselectAfterChangingFilterChange.spec.ts
  interfaces/Portalicious/src/app/components/query-table/query-table.component.html
  interfaces/Portalicious/src/app/components/query-table/query-table.component.ts
Labels: enhancement

#6841 Remove filters per payment when getting registrations
  services/121-service/src/payments/payments.controller.ts
  services/121-service/src/program-attributes/program-attributes.service.ts
  services/121-service/src/registration/const/filter-operation.const.ts
  services/121-service/src/registration/enum/payment-filter.enum.ts
  services/121-service/src/registration/registrations.controller.spec.ts
  services/121-service/src/registration/registrations.controller.ts
  services/121-service/src/registration/services/registrations-pagination.service.ts
  services/121-service/swagger.json
  services/121-service/test/program/__snapshots__/create-program.test.ts.snap
  services/121-service/test/registrations/pagination/filter-registration.payment.test.ts
Labels: chore

#6840 chore: remove unused messages endpoint
  services/121-service/src/activities/activities.mapper.ts
  services/121-service/src/activities/activities.service.ts
  services/121-service/src/activities/interfaces/message-activity.interface.ts
  services/121-service/src/notifications/twilio-message.repository.ts
  services/121-service/src/notifications/types/twilio-message-by-registration-id.interface.ts
  services/121-service/src/payments/dto/retry-payment.dto.ts
  services/121-service/src/payments/payments.service.ts
  services/121-service/src/registration/dto/message-history.dto.ts
  services/121-service/src/registration/dto/reference-ids.dto.ts
  services/121-service/src/registration/registrations.controller.ts
  services/121-service/src/registration/registrations.service.ts
  services/121-service/swagger.json
  services/121-service/test/helpers/program.helper.ts
  services/121-service/test/helpers/registration.helper.ts
  services/121-service/test/payment/__snapshots__/do-payment-fsp-voucher.test.ts.snap
  services/121-service/test/payment/do-payment-fsp-visa-debit/do-payment-fsp-visa-debit.success.test.ts
  services/121-service/test/payment/do-payment-fsp-voucher.test.ts
  services/121-service/test/registrations/pagination/send-message.test.ts
  services/121-service/test/registrations/send-message-with-placeholder.test.ts
  services/121-service/test/registrations/send-templated-message.test.ts
  services/121-service/test/visa-card/block-visa-card.test.ts
  services/121-service/test/visa-card/issue-new-card.test.ts
  services/121-service/tsconfig.json
Labels: chore

#6843 chore: remove registrationCreatedDate
  e2e/portalicious/pages/RegistrationsPage.ts
  interfaces/Portalicious/src/app/domains/project/project-attribute.helpers.ts
  interfaces/Portalicious/src/app/services/registration-attribute.service.ts
  interfaces/Portalicious/src/locale/messages.xlf
  services/121-service/src/events/events.service.spec.ts
  services/121-service/src/events/events.service.ts
  services/121-service/src/metrics/metrics.service.ts
  services/121-service/src/migration/1746704921316-remove-registrationCreatedDate.ts
  services/121-service/src/program-attributes/program-attributes.service.ts
  services/121-service/src/registration/const/filter-operation.const.ts
  services/121-service/src/registration/enum/registration-attribute.enum.ts
  services/121-service/src/registration/registration-view.entity.ts
  services/121-service/swagger.json
  services/121-service/test/program/__snapshots__/create-program.test.ts.snap
  services/121-service/test/registrations/pagination/filter-registration.test.ts
Labels: chore

#6833 refactor: Merge E2E-test tasks/scripts/config into single Portal-mode
  .github/workflows/test_e2e_portal.yml
  README.md
  docs/pull_request_template.md
  e2e/.eslintrc.js
  e2e/README.md
  e2e/package.json
  e2e/playwright.config.ts
  e2e/playwright.portalicious.config.ts
  e2e/portalicious/components/ConfirmationDialogComponent.ts
  e2e/portalicious/components/DataListComponent.ts
  e2e/portalicious/pages/RegistrationBasePage.ts
  interfaces/Portalicious/package.json
  interfaces/Portalicious/tsconfig.json
  services/.env.example
Labels: ignore-for-release, chore

#6846 Catch errors so node does not crash
  services/121-service/src/exchange-rates/exchange-rates.controller.ts
  services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.controller.ts
  services/121-service/src/payments/reconciliation/commercial-bank-ethiopia-reconciliation/commercial-bank-ethiopia-reconciliation.controller.ts
  services/121-service/src/payments/reconciliation/intersolve-visa-reconciliation/intersolve-visa-reconciliation.controller.ts
Labels: bugfix

#6809 Remove old transaction endpoint for old portal
  services/121-service/src/payments/transactions/dto/get-transaction.dto.ts
  services/121-service/src/payments/transactions/transactions.controller.ts
  services/121-service/src/payments/transactions/transactions.module.ts
  services/121-service/src/payments/transactions/transactions.service.ts
  services/121-service/swagger.json
Labels: chore

#6847 Log errors in cronjobs to azure
  services/121-service/src/exchange-rates/exchange-rates.controller.ts
  services/121-service/src/exchange-rates/exchange-rates.module.ts
  services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.controller.ts
  services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.module.ts
  services/121-service/src/payments/reconciliation/commercial-bank-ethiopia-reconciliation/commercial-bank-ethiopia-reconciliation.controller.ts
  services/121-service/src/payments/reconciliation/commercial-bank-ethiopia-reconciliation/commercial-bank-ethiopia-reconciliation.module.ts
  services/121-service/src/payments/reconciliation/intersolve-visa-reconciliation/intersolve-visa-reconciliation.controller.ts
  services/121-service/src/payments/reconciliation/intersolve-visa-reconciliation/intersolve-visa-reconciliation.module.ts
  services/121-service/src/payments/reconciliation/intersolve-voucher-reconciliation/intersolve-voucher-reconciliation.controller.ts
Labels: bugfix

#6852 chore: make 121-service start non-detached
  README.md
  package.json
Labels: chore

#6765 Get transactions from dedicated endpoint
  services/121-service/src/payments/dto/get-transaction-response.dto.ts
  services/121-service/src/payments/payments.controller.ts
  services/121-service/src/payments/payments.service.spec.ts
  services/121-service/src/payments/payments.service.ts
  services/121-service/src/payments/transactions/dto/get-transaction.dto.ts
  services/121-service/src/payments/transactions/transaction.repository.ts
  services/121-service/src/payments/transactions/transactions.controller.ts
  services/121-service/src/payments/transactions/transactions.module.ts
  services/121-service/src/payments/transactions/transactions.service.ts
  services/121-service/src/registration/repositories/registration-scoped.repository.spec.ts
  services/121-service/src/registration/repositories/registration-scoped.repository.ts
  services/121-service/src/registration/services/registrations-pagination.service.ts
  services/121-service/swagger.json
  services/121-service/test/fixtures/user-owner.ts
  services/121-service/test/helpers/program.helper.ts
  services/121-service/test/mocks/seed-mock.test.ts
  services/121-service/test/payment/__snapshots__/do-payment-fsp-excel.test.ts.snap
  services/121-service/test/payment/do-payment-fsp-nedbank.test.ts
  services/121-service/test/payment/do-payment-fsp-visa-debit/do-payment-fsp-visa-debit.success.test.ts
  services/121-service/test/payment/do-payment-fsp-voucher.test.ts
  services/121-service/test/payment/do-payment.scope.test.ts
  services/121-service/test/program/manage-program-financial-service-provider-configuration.test.ts
  services/121-service/test/registrations/update-registration-program-financial-service-provider-configuration.test.ts
  services/121-service/test/transactions/get-transactions.test.ts
Labels: chore

#6851 fix: re-add erroneously deleted endpoint to get k6 working again
  k6/models/payments.js
  services/121-service/src/metrics/dto/registrationstatus-stats.dto.ts
  services/121-service/src/metrics/metrics.controller.ts
  services/121-service/src/metrics/metrics.service.ts
  services/121-service/swagger.json
Labels: chore

#6812 chore: use new transactions endpoint in portalicious
  interfaces/Portalicious/src/app/domains/metric/metric.api.service.ts
  interfaces/Portalicious/src/app/domains/metric/metric.model.ts
  interfaces/Portalicious/src/app/domains/payment/payment.api.service.ts
  interfaces/Portalicious/src/app/domains/payment/payment.model.ts
  interfaces/Portalicious/src/app/pages/project-monitoring/project-monitoring.page.ts
  interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.html
  interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts
  interfaces/Portalicious/src/app/pages/project-payments/components/payment-summary-card/payment-summary-card.component.ts
  interfaces/Portalicious/src/locale/messages.xlf
Labels: chore

#6819 fix: warning message when including included registrations
  interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-dialog/change-status-dialog.component.html
  interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-dialog/change-status-dialog.component.ts
  interfaces/Portalicious/src/locale/messages.xlf
Labels: bugfix

#6848 Do not allow type tel (phonenumber) in mass update (back-end)
  services/121-service/src/registration/enum/registration-validation-input-type.enum.ts
  services/121-service/src/registration/interfaces/validate-registration-config.interface.ts
  services/121-service/src/registration/registrations.controller.ts
  services/121-service/src/registration/registrations.service.ts
  services/121-service/src/registration/services/registrations-import.service.ts
  services/121-service/src/registration/validators/registrations-input-validator.spec.ts
  services/121-service/src/registration/validators/registrations-input-validator.ts
  services/121-service/test-registration-data/test-registrations-patch-OCW.csv
  services/121-service/test/registrations/bulk-update-registration.test.ts
Labels: enhancement

#6823 refactor: Use a named variable for the list, to ease translations' context
  interfaces/portal/src/app/services/registration-attribute.service.ts
  interfaces/portal/src/locale/messages.xlf
Labels: ignore-for-release, chore

#6849 feat: metrics/export-list endpoint supports "select" pagination query
  services/121-service/src/metrics/metrics.controller.ts
  services/121-service/src/metrics/metrics.service.ts
  services/121-service/src/registration/const/filter-operation.const.ts
  services/121-service/test/metrics/__snapshots__/export-list.test.ts.snap
  services/121-service/test/metrics/export-list.test.ts
Labels: enhancement

#6872 Link to the latest/only version of the 121 Manual
  interfaces/portal/src/app/components/page-layout/components/header/header.component.html
  interfaces/portal/src/app/pages/project-registrations/components/custom-message-control/custom-message-control.component.html
  interfaces/portal/src/app/pages/project-registrations/project-registrations.page.html
  interfaces/portal/src/locale/messages.xlf
Labels: enhancement

#6870 chore: Make root-level test/lint/fix commands run once without fail
  .prettierignore
  package.json
Labels: ignore-for-release, chore

#6871 chore: Skip download of unused log-files
  tools/download-logs.mjs
Labels: ignore-for-release, chore

#6873 chore: refactor e2e test export assertions
  e2e/portal/pages/BasePage.ts
  e2e/portal/pages/PaymentsPage.ts
  e2e/portal/pages/RegistrationsPage.ts
  e2e/portal/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusCompleted.spec.ts
  e2e/portal/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusDeclined.spec.ts
  e2e/portal/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusIncluded.spec.ts
  e2e/portal/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusPaused.spec.ts
  e2e/portal/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusRegistered.spec.ts
  e2e/portal/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusValidated.spec.ts
  e2e/portal/tests/ChangeRegistrationStatus/MovePasFromCompletedToDeclined.spec.ts
  e2e/portal/tests/ChangeRegistrationStatus/MovePasFromCompletedToIncluded.spec.ts
  e2e/portal/tests/ChangeRegistrationStatus/MovePasFromDeclinedToIncluded.spec.ts
  e2e/portal/tests/ChangeRegistrationStatus/MovePasFromIncludedToDeclined.spec.ts
  e2e/portal/tests/ChangeRegistrationStatus/MovePasFromIncludedToPaused.spec.ts
  e2e/portal/tests/ChangeRegistrationStatus/MovePasFromRegisteredToValidated.spec.ts
  e2e/portal/tests/DoPayment/DoSuccessfulPaymentWithExcelFsp.spec.ts
  e2e/portal/tests/EditRegistration/EditRegistration.spec.ts
  e2e/portal/tests/ExportRegistrations/ExportHighVolumeOfRegistrations.spec.ts
  e2e/portal/tests/ExportRegistrations/ExportRegistrationsDataChanges.spec.ts
  e2e/portal/tests/ExportRegistrations/ExportRegistrationsList.spec.ts
  e2e/portal/tests/ImportRegistrations/ImportRegistrationsSuccessfully.spec.ts
  e2e/portal/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByDropdownSelection.spec.ts
  e2e/portal/tests/ViewPayment/RetryPaymentWithExcelFsp.spec.ts
  e2e/portal/tests/ViewPayments/ExportPayments.spec.ts
  e2e/portal/tests/__screenshots__/DoPayment/DoSuccessfulPaymentWithExcelFsp.spec.ts/exported-xlsx.csv
  e2e/portal/tests/__screenshots__/ExportRegistrations/ExportHighVolumeOfRegistrations.spec.ts/exported-xlsx.csv
  e2e/portal/tests/__screenshots__/ExportRegistrations/ExportRegistrationsDataChanges.spec.ts/exported-xlsx.csv
  e2e/portal/tests/__screenshots__/ExportRegistrations/ExportRegistrationsList.spec.ts/exported-xlsx.csv
  e2e/portal/tests/__screenshots__/ImportRegistrations/downloadRegistrationsTemplate.spec.ts/exported-csv.csv
  e2e/portal/tests/__screenshots__/ViewPayment/RetryPaymentWithExcelFsp.spec.ts/exported-xlsx.csv
  e2e/portal/tests/__screenshots__/ViewPayments/ExportPayments.spec.ts/exported-xlsx.csv
  services/121-service/src/events/utils/events.mapper.ts
Labels: chore

#6850 feat: enable csv registration exports in portalicious
  .gitignore
  e2e/portal/components/TableComponent.ts
  e2e/portal/pages/PaymentsPage.ts
  e2e/portal/pages/RegistrationsPage.ts
  e2e/portal/tests/ExportRegistrations/ExportRegistrationsList.spec.ts
  e2e/portal/tests/ViewFilterAndSortRegistrations/DeselectAfterChangingFilterChange.spec.ts
  e2e/portal/tests/__screenshots__/ExportRegistrations/ExportRegistrationsList.spec.ts/exported-csv.csv
  interfaces/portal/package-lock.json
  interfaces/portal/package.json
  interfaces/portal/src/app/domains/metric/metric.api.service.ts
  interfaces/portal/src/app/domains/payment/payment.api.service.ts
  interfaces/portal/src/app/pages/project-payment/components/import-reconciliation-data/import-reconciliation-data.component.ts
  interfaces/portal/src/app/pages/project-registrations/components/export-registrations/export-registrations.component.html
  interfaces/portal/src/app/pages/project-registrations/components/export-registrations/export-registrations.component.ts
  interfaces/portal/src/app/services/download.service.ts
  interfaces/portal/src/app/services/export.service.ts
  interfaces/portal/src/app/utils/csv-helpers.ts
  interfaces/portal/src/locale/messages.xlf
Labels: enhancement

#6868 refactor: Rename referenceId to be less ambiguous to what it refers
  interfaces/portal/src/app/pages/project-payment/project-payment.page.ts
  services/121-service/src/payments/dto/get-transaction-response.dto.ts
  services/121-service/src/payments/payments.service.spec.ts
  services/121-service/src/payments/transactions/transaction.repository.ts
  services/121-service/src/scoped.repository.spec.ts
  services/121-service/test/helpers/intersolve-voucher.helper.ts
  services/121-service/test/helpers/program.helper.ts
  services/121-service/test/mocks/seed-mock.test.ts
  services/121-service/test/payment/do-payment-filter.test.ts
  services/121-service/test/payment/do-payment-fsp-commercial-bank-ethiopia.test.ts
  services/121-service/test/payment/do-payment-fsp-excel.test.ts
  services/121-service/test/payment/do-payment-fsp-nedbank.test.ts
  services/121-service/test/payment/do-payment-fsp-safaricom.test.ts
  services/121-service/test/payment/do-payment-fsp-visa-debit/do-payment-fsp-visa-debit-error.test.ts
  services/121-service/test/payment/do-payment-fsp-visa-debit/do-payment-fsp-visa-debit-retry.test.ts
  services/121-service/test/payment/do-payment-fsp-visa-debit/do-payment-fsp-visa-debit.success.test.ts
  services/121-service/test/payment/do-payment.scope.test.ts
  services/121-service/test/payment/payment-count-completed.test.ts
  services/121-service/test/program/manage-program-financial-service-provider-configuration.test.ts
  services/121-service/test/programs/registrations/scoped.test.ts
  services/121-service/test/registrations/update-registration-program-financial-service-provider-configuration.test.ts
  services/121-service/test/transactions/get-transactions.test.ts
Labels: chore

#6889 refactor: Replace manual flags with central npm-config
  .github/actions/build-interface/action.yml
  .github/actions/build-service/action.yml
  .github/workflows/test_e2e_portal.yml
  .github/workflows/test_interface_portal.yml
  .github/workflows/test_k6.yml
  .github/workflows/test_k6_cronjob.yml
  .github/workflows/test_mock-service_code.yml
  .github/workflows/test_service_code.yml
  .npmrc
  e2e/.npmrc
  interfaces/portal/.npmrc
  k6/.npmrc
  package.json
  services/121-service/.npmrc
  services/121-service/package.json
  services/mock-service/.npmrc
  services/mock-service/package.json
Labels: ignore-for-release, chore

#6892 refactor: Catch any errors from Lokalise API (to see if we run into new limits and have to go async)
  interfaces/portal/_build-download-translations.mjs
Labels: ignore-for-release, chore

#6891 chore: centralise "editable attributes" information
  interfaces/portal/src/app/pages/project-registration-personal-information/components/edit-personal-information/edit-personal-information.component.ts
  interfaces/portal/src/app/services/registration-attribute.service.ts
Labels: chore

#6888 test: add e2e permissions checks on payments page
  e2e/portal/tests/ViewPayments/ExportPayments.spec.ts
Labels: chore

#6893 chore: update E2E docs with performance best practice
  e2e/README.md
Labels: chore
