Repository global-121/121-platform, pull requests merged in 2025-09, with the labels that each got.

#7164 chore: update snapshots of specific e2e files
  e2e/README.md
  e2e/package.json
Labels: chore

#7158 Post merge review niels small changes
  services/121-service/src/metrics/metrics.controller.ts
  services/121-service/src/metrics/metrics.service.ts
  services/121-service/src/payments/services/__snapshots__/payments-reporting.service.spec.ts.snap
  services/121-service/src/payments/services/payments-reporting.service.spec.ts
  services/121-service/src/payments/services/payments-reporting.service.ts
  services/121-service/src/registration/mappers/registration-views.mapper.spec.ts
  services/121-service/src/registration/mappers/registration-views.mapper.ts
Labels: chore

#7163 remove scripts
  services/121-service/src/scripts.ts
Labels: chore

#7130 fix: don't error out on invalid CSV and return better error message
  services/121-service/src/utils/file-import/file-import.service.spec.ts
  services/121-service/src/utils/file-import/file-import.service.ts
Labels: bugfix

#7188 chore: better multiselect options with icons in query table
  interfaces/portal/src/app/components/query-table/query-table.component.html
  interfaces/portal/src/app/components/query-table/query-table.component.ts
  interfaces/portal/src/app/pages/project-monitoring-files/components/table-cell-file-type.component.ts
  interfaces/portal/src/app/pages/project-monitoring-files/project-monitoring-files.page.ts
  interfaces/portal/src/app/pages/project-payment-log/components/table-cell-payment-event-activity.component.ts
  interfaces/portal/src/app/pages/project-payment-log/project-payment-log.page.ts
  interfaces/portal/src/app/pages/project-payment-transfer-list/project-payment-transfer-list.page.ts
  interfaces/portal/src/app/pages/project-registration-activity-log/components/table-cell-activity.component.ts
  interfaces/portal/src/app/pages/project-registration-activity-log/project-registration-activity-log.page.ts
  interfaces/portal/src/app/services/registrations-table-column.service.ts
  services/121-service/src/payments/payment-events/dtos/payment-events-return.dto.ts
  services/121-service/src/payments/payment-events/mappers/payment-events.mapper.spec.ts
  services/121-service/src/payments/payment-events/mappers/payment-events.mapper.ts
  services/121-service/test/payments/payment-events.test.ts
Labels: chore

#7187 Frontend dependencies
  interfaces/portal/karma.conf.js
  interfaces/portal/package-lock.json
  interfaces/portal/package.json
Labels: chore

#7201 fix: add accept headers to disburse call
  services/121-service/src/payments/fsp-integration/airtel/services/__snapshots__/airtel.api.service.spec.ts.snap
  services/121-service/src/payments/fsp-integration/airtel/services/airtel.api.service.spec.ts
  services/121-service/src/payments/fsp-integration/airtel/services/airtel.api.service.ts
Labels: chore

#7197 chore: refactor table management to use p-drawer directly
  e2e/portal/pages/RegistrationsPage.ts
  interfaces/portal/src/app/components/query-table/components/query-table-column-management/query-table-column-management.component.html
  interfaces/portal/src/app/components/query-table/components/query-table-column-management/query-table-column-management.component.ts
Labels: chore

#7160 Extra validation on from and to date for payment export
  interfaces/portal/src/app/domains/metric/metric.api.service.ts
  services/121-service/src/metrics/metrics.controller.ts
  services/121-service/src/payments/payments.controller.ts
  services/121-service/src/payments/transactions/dto/get-transaction-query.dto.ts
  services/121-service/src/registration-events/dto/get-registration-event-query.dto.ts
  services/121-service/src/registration-events/dto/registration-event-search-options.dto.ts
  services/121-service/src/registration-events/registration-events.controller.ts
  services/121-service/swagger.json
  services/121-service/test/helpers/program.helper.ts
  services/121-service/test/registration-event/filter-registration-events.test.ts
  services/121-service/test/transactions/export-transactions.test.ts
Labels: chore

#7224 Refactor CBE to use the transaction job processor
  interfaces/portal/src/app/components/data-list/data-list.component.ts
  interfaces/portal/src/app/components/skeleton-inline/skeleton-inline.component.ts
  services/121-service/module-dependencies.md
  services/121-service/src/fsps/fsp-settings.const.ts
  services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/commercial-bank-ethiopia.module.ts
  services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/dto/commercial-bank-ethiopia-job.dto.ts
  services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/dto/commercial-bank-ethiopia-transfer-payload.dto.ts
  services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/interfaces/create-credit-transfer-or-get-transaction-status-params.interface.ts
  services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/processors/commercial-bank-ethiopia.processor.spec.ts
  services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/processors/commercial-bank-ethiopia.processor.ts
  services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/services/commercial-bank-ethiopia.api.service.ts
  services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/services/commercial-bank-ethiopia.service.spec.ts
  services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/services/commercial-bank-ethiopia.service.ts
  services/121-service/src/payments/services/payments-execution.service.ts
  services/121-service/src/payments/services/transaction-jobs-creation.service.ts
  services/121-service/src/queues-registry/queues-registry.module.ts
  services/121-service/src/transaction-jobs/processors/transaction-jobs-commercial-bank-ethiopia.processor.ts
  services/121-service/src/transaction-jobs/services/transaction-jobs-commercial-bank-ethiopia.service.spec.ts
  services/121-service/src/transaction-jobs/services/transaction-jobs-commercial-bank-ethiopia.service.ts
  services/121-service/src/transaction-jobs/services/transaction-jobs-helper.service.spec.ts
  services/121-service/src/transaction-jobs/services/transaction-jobs-helper.service.ts
  services/121-service/src/transaction-jobs/transaction-jobs.module.ts
  services/121-service/src/transaction-queues/dto/commercial-bank-ethiopia-transaction-job.dto.ts
  services/121-service/src/transaction-queues/dto/intersolve-visa-transaction-job.dto.ts
  services/121-service/src/transaction-queues/dto/nedbank-transaction-job.dto.ts
  services/121-service/src/transaction-queues/dto/onafriq-transaction-job.dto.ts
  services/121-service/src/transaction-queues/dto/safaricom-transaction-job.dto.ts
  services/121-service/src/transaction-queues/dto/shared-transaction-job.dto.ts
  services/121-service/src/transaction-queues/transaction-queues.service.ts
  services/121-service/src/utils/getRandomValue.helper.spec.ts
  services/121-service/src/utils/getRandomValue.helper.ts
  services/121-service/src/utils/random-value.helper.spec.ts
  services/121-service/src/utils/random-value.helper.ts
  services/121-service/src/utils/waitFor.helper.ts
Labels: chore

#7186 feat: logout on deprecated permissions
  interfaces/portal/src/app/services/auth.service.spec.ts
  interfaces/portal/src/app/services/auth.service.ts
Labels: bugfix

#7226 chore: fix typo
  services/121-service/src/payments/reconciliation/excel/excel-reconciliation.controller.ts
  services/121-service/src/payments/reconciliation/excel/excel-reconciliation.module.ts
  services/121-service/src/payments/reconciliation/excel/excel-reconciliation.service.ts
Labels: chore

#7227 Upgrade (dev-)dependencies + config to get less lint-issues
  interfaces/portal/.knip.json
  interfaces/portal/eslint.config.mjs
  interfaces/portal/package-lock.json
  interfaces/portal/package.json
  interfaces/portal/tsconfig.json
Labels: chore

#7233 feat: block export fsp instructions while in progress
  interfaces/portal/src/app/components/page-layout-payment/components/import-reconciliation-data/import-reconciliation-data.component.html
  interfaces/portal/src/app/components/page-layout-payment/components/import-reconciliation-data/import-reconciliation-data.component.ts
  interfaces/portal/src/locale/messages.xlf
  services/121-service/module-dependencies.md
  services/121-service/src/payments/payments.controller.ts
  services/121-service/src/payments/payments.module.ts
  services/121-service/src/payments/reconciliation/excel/excel-reconciliation.controller.ts
  services/121-service/src/payments/reconciliation/excel/excel-reconciliation.module.ts
  services/121-service/src/payments/reconciliation/excel/excel-reconciliation.service.spec.ts
  services/121-service/src/payments/reconciliation/excel/excel-reconciliation.service.ts
  services/121-service/src/payments/services/payments-excel-fsp.service.spec.ts
  services/121-service/src/payments/services/payments-excel-fsp.service.ts
Labels: enhancement

#7256 chore: data migration for phoneNumberPayment
  services/121-service/package.json
  services/121-service/src/migration/1758014323364-PhoneNumberPaymentOnafriq.ts
Labels: chore

#7257 fix: Use new "instance-121"-elements from Status-page
  tools/check-versions.mjs
  tools/download-logs.mjs
Labels: ignore-for-release, chore

#7156 Intersolve update customer name on registration update
  services/.env.example
  services/121-service/src/payments/fsp-integration/intersolve-visa/dtos/intersolve-api/customer-individual-intersolve-api.dto.ts
  services/121-service/src/payments/fsp-integration/intersolve-visa/dtos/intersolve-api/get-customer-individual-intersolve-api.dto.ts
  services/121-service/src/payments/fsp-integration/intersolve-visa/enums/intersolve-visa-121-error-text.enum.ts
  services/121-service/src/payments/fsp-integration/intersolve-visa/interfaces/send-updated-contact-information-params.interface.ts
  services/121-service/src/payments/fsp-integration/intersolve-visa/services/intersolve-visa.api.service.ts
  services/121-service/src/payments/fsp-integration/intersolve-visa/services/intersolve-visa.service.ts
  services/121-service/src/registration/services/registrations.service.ts
  services/121-service/test/visa-card/visa-customer-information-update.test.ts
  services/mock-service/src/fsp-integration/intersolve-visa/intersolve-visa.mock.controller.ts
  services/mock-service/src/fsp-integration/intersolve-visa/intersolve-visa.mock.service.ts
Labels: enhancement

#7258 feat: edit copy in "edit project team user" dialogs
  interfaces/portal/src/app/pages/project-team/components/add-project-team-user-dialog/add-project-team-user-dialog.component.html
  interfaces/portal/src/app/pages/project-team/components/add-project-team-user-dialog/add-project-team-user-dialog.component.ts
  interfaces/portal/src/locale/messages.xlf
Labels: enhancement

#7268 fix: CBE transfer migration
  services/121-service/src/migration/1757420276256-CbeTransferEntity.ts
Labels: chore

#7271 chore: second attempt to fix ExportRegistrationList
  e2e/portal/pages/RegistrationsPage.ts
Labels: chore

#7272 chore: fix flaky ExportPayments test
  e2e/portal/tests/ViewPayments/ExportPayments.spec.ts
Labels: chore

#7274 Hardcode estimatedAnnualPaymentVolumeMajorUnit for intersolve individual
  services/121-service/src/payments/fsp-integration/intersolve-visa/services/intersolve-visa.api.service.ts
  services/121-service/src/payments/fsp-integration/intersolve-visa/services/intersolve-visa.service.ts
Labels: bugfix

#7261 fix: Make checks around (error-)status/response-codes easier to read, less error-prone = less (unnecessary) noise in the logs
  services/121-service/src/notifications/dto/twilio.dto.ts
  services/121-service/src/notifications/enum/twilio-error-codes.enum.ts
  services/121-service/src/notifications/message-incoming/message-incoming.service.ts
  services/121-service/src/notifications/sms/sms.service.ts
  services/121-service/src/notifications/whatsapp/whatsapp.service.ts
  services/121-service/src/payments/transactions/repositories/latest-transaction.repository.ts
  services/121-service/src/payments/transactions/transactions.service.ts
  services/121-service/src/registration/modules/registration-utilts/registration-utils.service.ts
  services/121-service/src/shared/enum/postgres-status-codes.enum.ts
  services/121-service/src/user/user.service.ts
  services/121-service/src/utils/comparison.helper.spec.ts
  services/121-service/src/utils/comparison.helper.ts
  services/121-service/test/registrations/pagination/send-message.test.ts
  services/mock-service/src/twilio/twilio.dto.ts
  services/mock-service/src/twilio/twilio.service.ts
Labels: bugfix

#7262 feat: project settings -> basic information page
  e2e/portal/components/PrimeNGDatePicker.ts
  e2e/portal/pages/BasePage.ts
  e2e/portal/pages/PaymentsPage.ts
  e2e/portal/pages/ProjectSettingsPage.ts
  e2e/portal/pages/ProjectTeamPage.ts
  e2e/portal/pages/RegistrationsPage.ts
  e2e/portal/tests/DebitCards/ManageDebitCards.spec.ts
  e2e/portal/tests/ManageTeam/AllSystemUsersCanBeAddedToProjectTeam.spec.ts
  e2e/portal/tests/ManageTeam/AllUsersAssignedShouldBeVisible.spec.ts
  e2e/portal/tests/ManageTeam/AssignSuccessfullyRolesToUser.spec.ts
  e2e/portal/tests/ManageTeam/RemoveUserFromTeam.spec.ts
  e2e/portal/tests/ManageTeam/ScopeVisibleOnlyWhenSetToTrue.spec.ts
  e2e/portal/tests/ManageTeam/UserCannotAssignRolesToSelf.spec.ts
  e2e/portal/tests/ProjectSettings/ProjectInformation/EditProjectInformation.spec.ts
  e2e/portal/tests/ProjectSettings/ProjectInformation/EditProjectScope.spec.ts
  interfaces/portal/src/app/app.routes.ts
  interfaces/portal/src/app/components/card-editable/card-editable.component.html
  interfaces/portal/src/app/components/card-editable/card-editable.component.ts
  interfaces/portal/src/app/components/data-list/data-list.component.html
  interfaces/portal/src/app/components/form-field-wrapper/form-field-wrapper.component.html
  interfaces/portal/src/app/components/page-layout-project-settings/page-layout-project-settings.component.html
  interfaces/portal/src/app/components/page-layout-project-settings/page-layout-project-settings.component.ts
  interfaces/portal/src/app/components/page-layout/components/project-menu/project-menu.component.ts
  interfaces/portal/src/app/domains/project/project.api.service.ts
  interfaces/portal/src/app/pages/project-settings-information/components/project-settings-basic-information/project-settings-basic-information.component.html
  interfaces/portal/src/app/pages/project-settings-information/components/project-settings-basic-information/project-settings-basic-information.component.ts
  interfaces/portal/src/app/pages/project-settings-information/components/project-settings-budget/project-settings-budget.component.html
  interfaces/portal/src/app/pages/project-settings-information/components/project-settings-budget/project-settings-budget.component.ts
  interfaces/portal/src/app/pages/project-settings-information/project-settings-information.page.html
  interfaces/portal/src/app/pages/project-settings-information/project-settings-information.page.ts
  interfaces/portal/src/app/pages/project-settings-team/project-settings-team.page.html
  interfaces/portal/src/app/pages/project-settings-team/project-settings-team.page.ts
  interfaces/portal/src/app/services/registrations-table-column.service.ts
  interfaces/portal/src/locale/messages.xlf
Labels: enhancement

#7279 Refactor registration bulk service
  services/121-service/src/registration/registrations.controller.spec.ts
  services/121-service/src/registration/registrations.controller.ts
  services/121-service/src/registration/services/registrations-bulk.service.spec.ts
  services/121-service/src/registration/services/registrations-bulk.service.ts
Labels: chore

#7283 fix: Prevent any stray spaces to break the Matomo-integration
  interfaces/portal/.knip.json
  interfaces/portal/_matomo.utils.mjs
  interfaces/portal/_matomo.utils.spec.ts
  interfaces/portal/_test-deployment-configuration.mjs
  interfaces/portal/_verify-deployment-configuration.mjs
Labels: chore

#7292 Remove 'allow new registrations' feature
  services/121-service/src/migration/1758867764225-remove-allow-new-registration-feature.ts
  services/121-service/src/programs/dto/create-program.dto.ts
  services/121-service/src/programs/dto/program-return.dto.ts
  services/121-service/src/programs/dto/update-program.dto.ts
  services/121-service/src/programs/entities/program.entity.ts
  services/121-service/src/programs/programs.service.ts
  services/121-service/src/registration/services/registrations.service.ts
  services/121-service/src/seed-data/program/program-cbe.json
  services/121-service/src/seed-data/program/program-nlrc-ocw.json
  services/121-service/test/program/__snapshots__/create-program.test.ts.snap
  services/121-service/test/program/create-program.test.ts
  services/121-service/test/program/update-program.test.ts
  services/121-service/test/registrations/import-registration.test.ts
Labels: chore

#7308 chore: fix date formatting issue in E2E tests
  e2e/portal/tests/DebitCards/ManageDebitCards.spec.ts
  e2e/portal/tests/ProjectSettings/ProjectInformation/EditProjectInformation.spec.ts
Labels: chore

#7142 feat: add internal dashboard to portal
  e2e/portal/pages/ProjectMonitoringPage.ts
  e2e/portal/tests/Dashboard/AllElementsOfProjectMonitoringPageDisplayCorrectData.spec.ts
  interfaces/portal/src/app/app.routes.ts
  interfaces/portal/src/app/components/page-layout-monitoring/components/monitoring-menu/monitoring-menu.component.ts
  interfaces/portal/src/app/components/page-layout-registration/components/ignore-duplicates-dialog/ignore-duplication-dialog.component.ts
  interfaces/portal/src/app/domains/metric/metric.api.service.ts
  interfaces/portal/src/app/domains/metric/metric.model.ts
  interfaces/portal/src/app/pages/project-monitoring-dashboard/components/amount-sent-per-month-chart/amount-sent-per-month-chart.component.html
  interfaces/portal/src/app/pages/project-monitoring-dashboard/components/amount-sent-per-month-chart/amount-sent-per-month-chart.component.ts
  interfaces/portal/src/app/pages/project-monitoring-dashboard/components/payments-aggregate-chart/payments-aggregate-chart.component.html
  interfaces/portal/src/app/pages/project-monitoring-dashboard/components/payments-aggregate-chart/payments-aggregate-chart.component.ts
  interfaces/portal/src/app/pages/project-monitoring-dashboard/components/registrations-by-creation-date-chart/registrations-by-creation-date-chart.component.html
  interfaces/portal/src/app/pages/project-monitoring-dashboard/components/registrations-by-creation-date-chart/registrations-by-creation-date-chart.component.ts
  interfaces/portal/src/app/pages/project-monitoring-dashboard/components/registrations-per-duplicate-status-chart/registrations-per-duplicate-status-chart.component.html
  interfaces/portal/src/app/pages/project-monitoring-dashboard/components/registrations-per-duplicate-status-chart/registrations-per-duplicate-status-chart.component.ts
  interfaces/portal/src/app/pages/project-monitoring-dashboard/components/registrations-per-status-chart/registrations-per-status-chart.component.html
  interfaces/portal/src/app/pages/project-monitoring-dashboard/components/registrations-per-status-chart/registrations-per-status-chart.component.ts
  interfaces/portal/src/app/pages/project-monitoring-dashboard/project-monitoring-dashboard.page.html
  interfaces/portal/src/app/pages/project-monitoring-dashboard/project-monitoring-dashboard.page.ts
  interfaces/portal/src/app/pages/project-payments/components/create-payment/create-payment.component.ts
  interfaces/portal/src/app/pages/project-registration-personal-information/project-registration-personal-information.page.ts
  interfaces/portal/src/app/pages/project-registrations/components/change-status-dialog/change-status-dialog.component.ts
  interfaces/portal/src/app/pages/project-registrations/components/import-registrations/import-registrations.component.ts
  interfaces/portal/src/app/pages/project-registrations/components/update-registrations/update-registrations.component.ts
  interfaces/portal/src/locale/messages.xlf
  interfaces/portal/tsconfig.json
  services/121-service/package-lock.json
  services/121-service/package.json
  services/121-service/src/metrics/dto/payment-aggregate.dto.ts
  services/121-service/src/metrics/dto/registrationstatus-stats.dto.ts
  services/121-service/src/metrics/metrics.controller.ts
  services/121-service/src/metrics/metrics.service.ts
  services/121-service/src/payments/payments.controller.ts
  services/121-service/src/payments/services/payments-reporting.service.ts
  services/121-service/src/pipes/assert-date.pipe.spec.ts
  services/121-service/src/pipes/assert-date.pipe.ts
  services/121-service/src/pipes/assert-iso8601.pipe.spec.ts
  services/121-service/src/pipes/assert-iso8601.pipe.ts
  services/121-service/src/pipes/assert-positive-number.pipe.spec.ts
  services/121-service/src/pipes/assert-positive-number.pipe.ts
  services/121-service/src/utils/dateSort.ts
  services/121-service/src/utils/to-type.helper.ts
  services/121-service/swagger.json
  services/121-service/test/metrics/get-native-dashboard-data.test.ts
Labels: enhancement

#7310 fix: Remove warnings around path-handling in Mock-Service
  services/mock-service/src/fsp-integration/airtel/airtel.mock.controller.ts
Labels: ignore-for-release, chore
